# Ejercicio 3: Modelo Vectorial y TF-IDF  
**Nombre:** Alexis Bautista  
**Fecha de Entrega:** 29 de abril del 2026

## Objetivo de la práctica

- Comprender el modelo vectorial como base para representar documentos y consultas.
- Calcular la matriz TF-IDF para el corpus `data/01_corpus_turismo_500.txt`
- Calcular la matriz TF-IDF para el corpus `Gutenberg 1000`

### Paso 1: Calcular la matriz TF-IDF para el corpus `data/01_corpus_turismo_500.txt`

En este caso se uso el archivo `data/El arte de amar.txt`

In [1]:
with open("data/El arte de amar.txt", "r", encoding="utf-8") as documento:
    contenido = documento.read()

Primero se creo un indice invertido para conocer el numero de veces que aparece un termino en el documento

In [2]:
# convertir todo en minusculas y separar el texto en una lista de palabras
lista_de_palabras = contenido.lower().split()

nombre_documento = "El arte de amar.txt"
indice_invertido = {}

# construccion indice invertido
for palabra in lista_de_palabras:
    
    if palabra not in indice_invertido:
        # Crear palabra en el diccionario principal
        # Su valor será un sub-diccionario con el nombre del doc y el conteo inicial de 1
        indice_invertido[palabra] = {nombre_documento: 1}
        
    else:
        # Acceder a la palabra, luego a su sub-diccionario del documento actual, y sumamos 1
        indice_invertido[palabra][nombre_documento] += 1

print (indice_invertido)

{'nota': {'El arte de amar.txt': 2}, 'de': {'El arte de amar.txt': 1004}, 'transcripción': {'El arte de amar.txt': 2}, '*': {'El arte de amar.txt': 6}, 'las': {'El arte de amar.txt': 467}, 'cursivas': {'El arte de amar.txt': 1}, 'se': {'El arte de amar.txt': 330}, 'muestran': {'El arte de amar.txt': 2}, 'entre': {'El arte de amar.txt': 28}, '_subrayados_.': {'El arte de amar.txt': 1}, 'los': {'El arte de amar.txt': 531}, 'errores': {'El arte de amar.txt': 2}, 'imprenta': {'El arte de amar.txt': 1}, 'han': {'El arte de amar.txt': 15}, 'sido': {'El arte de amar.txt': 9}, 'corregidos.': {'El arte de amar.txt': 1}, 'la': {'El arte de amar.txt': 834}, 'ortografía': {'El arte de amar.txt': 1}, 'del': {'El arte de amar.txt': 178}, 'texto': {'El arte de amar.txt': 2}, 'original': {'El arte de amar.txt': 4}, 'ha': {'El arte de amar.txt': 45}, 'modernizada': {'El arte de amar.txt': 2}, 'acuerdo': {'El arte de amar.txt': 1}, 'con': {'El arte de amar.txt': 445}, 'normas': {'El arte de amar.txt': 1}, 'publicadas': {'El arte de amar.txt': 1}, 'en': {'El arte de amar.txt': 534}, '2010': {'El arte de amar.txt': 1}, 'por': {'El arte de amar.txt': 213}, 'real': {'El arte de amar.txt': 1}, 'academia': {'El arte de amar.txt': 1}, 'española.': {'El arte de amar.txt': 1}, 'también': {'El arte de amar.txt': 35}, 'nombres': {'El arte de amar.txt': 3}, 'propios,': {'El arte de amar.txt': 1}, 'tanto': {'El arte de amar.txt': 14}, 'lugares': {'El arte de amar.txt': 4}, 'como': {'El arte de amar.txt': 101}, 'personajes.': {'El arte de amar.txt': 1}, 'notas': {'El arte de amar.txt': 2}, 'a': {'El arte de amar.txt': 632}, 'pie': {'El arte de amar.txt': 5}, 'página': {'El arte de amar.txt': 1}, 'renemeradas': {'El arte de amar.txt': 1}, 'y': {'El arte de amar.txt': 773}, 'colocadas': {'El arte de amar.txt': 1}, 'tras': {'El arte de amar.txt': 2}, 'el': {'El arte de amar.txt': 717}, 'párrafo': {'El arte de amar.txt': 1}, 'que': {'El arte de amar.txt': 632}, 'contiene': {'El arte de amar.txt': 3}, 'su': {'El arte de amar.txt': 228}, 'llamada.': {'El arte de amar.txt': 1}, 'páginas': {'El arte de amar.txt': 1}, 'blanco': {'El arte de amar.txt': 6}, 'eliminadas.': {'El arte de amar.txt': 1}, 'arte': {'El arte de amar.txt': 25}, 'amar.': {'El arte de amar.txt': 6}, 'traductor': {'El arte de amar.txt': 1}, 'ovidio': {'El arte de amar.txt': 9}, 'sus': {'El arte de amar.txt': 140}, 'obras': {'El arte de amar.txt': 2}, 'escrito': {'El arte de amar.txt': 2}, 'otras': {'El arte de amar.txt': 23}, 'plumas': {'El arte de amar.txt': 3}, 'más': {'El arte de amar.txt': 97}, 'bien': {'El arte de amar.txt': 28}, 'cortadas': {'El arte de amar.txt': 1}, 'mía;': {'El arte de amar.txt': 1}, 'así': {'El arte de amar.txt': 38}, 'fuera': {'El arte de amar.txt': 6}, 'temeridad': {'El arte de amar.txt': 2}, 'querer': {'El arte de amar.txt': 1}, 'añadir,': {'El arte de amar.txt': 1}, 'o': {'El arte de amar.txt': 47}, 'superfluidad': {'El arte de amar.txt': 1}, 'copiar': {'El arte de amar.txt': 1}, 'eruditos': {'El arte de amar.txt': 1}, 'emprendieron': {'El arte de amar.txt': 1}, 'aquel': {'El arte de amar.txt': 24}, 'trabajo.': {'El arte de amar.txt': 1}, 'demás': {'El arte de amar.txt': 7}, 'comentarios': {'El arte de amar.txt': 1}, 'rapsodias': {'El arte de amar.txt': 1}, 'no': {'El arte de amar.txt': 341}, 'son': {'El arte de amar.txt': 39}, 'ya': {'El arte de amar.txt': 50}, 'gusto': {'El arte de amar.txt': 3}, 'nuestro': {'El arte de amar.txt': 8}, 'siglo;': {'El arte de amar.txt': 1}, 'cual,': {'El arte de amar.txt': 1}, 'todos,': {'El arte de amar.txt': 3}, 'aspira': {'El arte de amar.txt': 1}, 'instruirse': {'El arte de amar.txt': 1}, 'solidez': {'El arte de amar.txt': 1}, 'es': {'El arte de amar.txt': 136}, 'necesario': {'El arte de amar.txt': 5}, 'recurra': {'El arte de amar.txt': 1}, 'fuentes,': {'El arte de amar.txt': 1}, 'sin': {'El arte de amar.txt': 67}, 'contentarse': {'El arte de amar.txt': 2}, 'vagas': {'El arte de amar.txt': 1}, 'repeticiones,': {'El arte de amar.txt': 2}, 'noticias': {'El arte de amar.txt': 1}, 'tal': {'El arte de amar.txt': 16}, 'vez': {'El arte de amar.txt': 18}, 'corrompidas.': {'El arte de amar.txt': 1}, 'pero': {'El arte de amar.txt': 75}, 'yo': {'El arte de amar.txt': 32}, 'traduzco': {'El arte de amar.txt': 1}, 'un': {'El arte de amar.txt': 85}, 'poema': {'El arte de amar.txt': 4}, 'ovidio,': {'El arte de amar.txt': 1}, 'andar': {'El arte de amar.txt': 3}, 'manos': {'El arte de amar.txt': 14}, 'mis': {'El arte de amar.txt': 29}, 'lectores': {'El arte de amar.txt': 1}, 'habrá': {'El arte de amar.txt': 5}, 'muchos': {'El arte de amar.txt': 12}, 'oído': {'El arte de amar.txt': 2}, 'siquiera': {'El arte de amar.txt': 1}, 'nombre;': {'El arte de amar.txt': 3}, 'otros': {'El arte de amar.txt': 19}, 'apenas': {'El arte de amar.txt': 11}, 'tienen': {'El arte de amar.txt': 10}, 'idea': {'El arte de amar.txt': 2}, 'superficial': {'El arte de amar.txt': 1}, 'él': {'El arte de amar.txt': 22}, 'poesías.': {'El arte de amar.txt': 1}, 'he': {'El arte de amar.txt': 27}, 'aquí': {'El arte de amar.txt': 17}, 'qué': {'El arte de amar.txt': 28}, 'puedo': {'El arte de amar.txt': 2}, 'pasar': {'El arte de amar.txt': 3}, 'todo': {'El arte de amar.txt': 29}, 'silencio': {'El arte de amar.txt': 3}, 'algunas': {'El arte de amar.txt': 11}, 'circunstancias': {'El arte de amar.txt': 2}, 'este': {'El arte de amar.txt': 46}, 'meritísimo': {'El arte de amar.txt': 1}, 'autor.': {'El arte de amar.txt': 1}, 'p.': {'El arte de amar.txt': 1}, 'nasón,': {'El arte de amar.txt': 1}, 'caballero': {'El arte de amar.txt': 1}, 'romano,': {'El arte de amar.txt': 1}, 'nació': {'El arte de amar.txt': 3}, 'sulmona,': {'El arte de amar.txt': 1}, 'ciudad': {'El arte de amar.txt': 5}, 'abruzo,': {'El arte de amar.txt': 1}, 'cuarenta': {'El arte de amar.txt': 1}, 'tres': {'El arte de amar.txt': 8}, 'años': {'El arte de amar.txt': 6}, 'antes': {'El arte de amar.txt': 13}, 'era': {'El arte de amar.txt': 38}, 'vulgar,': {'El arte de amar.txt': 1}, 'mismo': {'El arte de amar.txt': 24}, 'día': {'El arte de amar.txt': 18}, 'fue': {'El arte de amar.txt': 34}, 'muerto': {'El arte de amar.txt': 2}, 'elocuente': {'El arte de amar.txt': 3}, 'cicerón.': {'El arte de amar.txt': 1}, 'roma,': {'El arte de amar.txt': 2}, 'donde': {'El arte de amar.txt': 21}, 'llevado': {'El arte de amar.txt': 1}, 'corta': {'El arte de amar.txt': 1}, 'edad,': {'El arte de amar.txt': 4}, 'dio': {'El arte de amar.txt': 7}, 'letras': {'El arte de amar.txt': 5}, 'bajo': {'El arte de amar.txt': 4}, 'dirección': {'El arte de amar.txt': 1}, 'plocio': {'El arte de amar.txt': 1}, 'gripo;': {'El arte de amar.txt': 1}, 'mostrando': {'El arte de amar.txt': 1}, 'agudo': {'El arte de amar.txt': 1}, 'ingenio,': {'El arte de amar.txt': 2}, 'dieciséis': {'El arte de amar.txt': 1}, 'le': {'El arte de amar.txt': 55}, 'enviaron': {'El arte de amar.txt': 1}, 'atenas,': {'El arte de amar.txt': 2}, 'estudió': {'El arte de amar.txt': 1}, 'ciencias,': {'El arte de amar.txt': 1}, 'perfeccionó': {'El arte de amar.txt': 2}, 'lengua': {'El arte de amar.txt': 7}, 'griega.': {'El arte de amar.txt': 1}, 'escuelas': {'El arte de amar.txt': 1}, 'atenienses': {'El arte de amar.txt': 1}, 'eran': {'El arte de amar.txt': 10}, 'entonces': {'El arte de amar.txt': 24}, 'frecuentadas': {'El arte de amar.txt': 1}, 'juventud': {'El arte de amar.txt': 3}, 'romana,': {'El arte de amar.txt': 1}, 'autor': {'El arte de amar.txt': 3}, 'latino': {'El arte de amar.txt': 2}, 'formase': {'El arte de amar.txt': 1}, 'ellas.': {'El arte de amar.txt': 5}, 'quiso': {'El arte de amar.txt': 1}, 'padre': {'El arte de amar.txt': 11}, 'obligarle': {'El arte de amar.txt': 1}, 'seguir': {'El arte de amar.txt': 2}, 'carrera': {'El arte de amar.txt': 2}, 'foro,': {'El arte de amar.txt': 4}, 'efecto': {'El arte de amar.txt': 4}, 'obedecerle': {'El arte de amar.txt': 1}, 'siguió': {'El arte de amar.txt': 1}, 'algún': {'El arte de amar.txt': 8}, 'tiempo,': {'El arte de amar.txt': 3}, 'hasta': {'El arte de amar.txt': 11}, 'padre,': {'El arte de amar.txt': 7}, 'abandonó': {'El arte de amar.txt': 1}, 'deliciosas': {'El arte de amar.txt': 1}, 'musas,': {'El arte de amar.txt': 2}, 'llamaba': {'El arte de amar.txt': 2}, 'innata': {'El arte de amar.txt': 1}, 'inclinación.': {'El arte de amar.txt': 1}, 'tuvo': {'El arte de amar.txt': 3}, 'maestros': {'El arte de amar.txt': 1}, 'filosofía': {'El arte de amar.txt': 3}, 'porcio': {'El arte de amar.txt': 1}, 'latrón,': {'El arte de amar.txt': 1}, 'retórica': {'El arte de amar.txt': 1}, 'marcelo': {'El arte de amar.txt': 1}, 'fusco,': {'El arte de amar.txt': 1}, 'gramática': {'El arte de amar.txt': 1}, 'julio': {'El arte de amar.txt': 1}, 'grecino,': {'El arte de amar.txt': 1}, 'profesores': {'El arte de amar.txt': 1}, 'llevaban': {'El arte de amar.txt': 1}, 'aplauso': {'El arte de amar.txt': 4}, 'roma.': {'El arte de amar.txt': 3}, 'bueno': {'El arte de amar.txt': 2}, 'e': {'El arte de amar.txt': 6}, 'ingenioso': {'El arte de amar.txt': 1}, 'orador,': {'El arte de amar.txt': 1}, 'afluente': {'El arte de amar.txt': 1}, 'patético': {'El arte de amar.txt': 1}, 'poeta,': {'El arte de amar.txt': 2}, 'engrandecía': {'El arte de amar.txt': 1}, 'animaba': {'El arte de amar.txt': 1}, 'cuantos': {'El arte de amar.txt': 3}, 'asuntos': {'El arte de amar.txt': 1}, 'encomendaba': {'El arte de amar.txt': 1}, 'pluma;': {'El arte de amar.txt': 1}, 'demasiadas': {'El arte de amar.txt': 1}, 'flores': {'El arte de amar.txt': 4}, 'exornó': {'El arte de amar.txt': 1}, 'versos,': {'El arte de amar.txt': 4}, 'prodigadas': {'El arte de amar.txt': 1}, 'facilidad': {'El arte de amar.txt': 1}, 'ardiente': {'El arte de amar.txt': 1}, 'fecunda': {'El arte de amar.txt': 1}, 'imaginación,': {'El arte de amar.txt': 1}, 'apartaron': {'El arte de amar.txt': 1}, 'noble': {'El arte de amar.txt': 1}, 'sencilla': {'El arte de amar.txt': 2}, 'majestad': {'El arte de amar.txt': 1}, 'arte.': {'El arte de amar.txt': 5}, 'dicen': {'El arte de amar.txt': 5}, 'tenía': {'El arte de amar.txt': 7}, 'amor': {'El arte de amar.txt': 34}, 'propio,': {'El arte de amar.txt': 1}, 'solo': {'El arte de amar.txt': 29}, 'desconocía,': {'El arte de amar.txt': 1}, 'sino': {'El arte de amar.txt': 26}, 'amaba': {'El arte de amar.txt': 2}, 'defectos,': {'El arte de amar.txt': 1}, 'negándose': {'El arte de amar.txt': 1}, 'corregirlos,': {'El arte de amar.txt': 1}, 'aun': {'El arte de amar.txt': 11}, 'cuando': {'El arte de amar.txt': 75}, 'amigos': {'El arte de amar.txt': 1}, 'advirtiesen.': {'El arte de amar.txt': 1}, '¡debilidad': {'El arte de amar.txt': 1}, 'humana,': {'El arte de amar.txt': 1}, 'eximen': {'El arte de amar.txt': 1}, 'mayores': {'El arte de amar.txt': 3}, 'hombres!': {'El arte de amar.txt': 1}, 'gozó': {'El arte de amar.txt': 1}, 'roma': {'El arte de amar.txt': 3}, 'honores': {'El arte de amar.txt': 1}, 'beneficios': {'El arte de amar.txt': 1}, 'augusto': {'El arte de amar.txt': 4}, 'acostumbraba': {'El arte de amar.txt': 1}, 'remunerar': {'El arte de amar.txt': 1}, 'grandes': {'El arte de amar.txt': 4}, 'talentos,': {'El arte de amar.txt': 1}, 'hubiera': {'El arte de amar.txt': 13}, 'acaso': {'El arte de amar.txt': 11}, 'llegado': {'El arte de amar.txt': 4}, 'mayor': {'El arte de amar.txt': 10}, 'fortuna': {'El arte de amar.txt': 2}, 'poetas': {'El arte de amar.txt': 5}, 'contemporáneos;': {'El arte de amar.txt': 1}, 'desgracia,': {'El arte de amar.txt': 1}, 'al': {'El arte de amar.txt': 173}, 'hombre': {'El arte de amar.txt': 7}, 'dado': {'El arte de amar.txt': 6}, 'pocas': {'El arte de amar.txt': 2}, 'veces': {'El arte de amar.txt': 44}, 'evitar,': {'El arte de amar.txt': 1}, 'proporcionó': {'El arte de amar.txt': 1}, 'amores': {'El arte de amar.txt': 4}, 'julia,': {'El arte de amar.txt': 1}, 'hija': {'El arte de amar.txt': 6}, 'tiberio,': {'El arte de amar.txt': 1}, 'quien': {'El arte de amar.txt': 28}, 'escribió': {'El arte de amar.txt': 1}, 'epístolas': {'El arte de amar.txt': 1}, 'amatorias,': {'El arte de amar.txt': 2}, 'cuales': {'El arte de amar.txt': 8}, 'miró': {'El arte de amar.txt': 3}, 'delito': {'El arte de amar.txt': 4}, 'lesa': {'El arte de amar.txt': 1}, 'majestad,': {'El arte de amar.txt': 1}, 'mandó': {'El arte de amar.txt': 1}, 'quemar,': {'El arte de amar.txt': 1}, 'desterrando': {'El arte de amar.txt': 1}, 'villa': {'El arte de amar.txt': 1}, 'tomos': {'El arte de amar.txt': 1}, 'ponto': {'El arte de amar.txt': 1}, 'euxino.': {'El arte de amar.txt': 1}, 'allí': {'El arte de amar.txt': 20}, 'murió': {'El arte de amar.txt': 1}, 'edad': {'El arte de amar.txt': 7}, 'cerca': {'El arte de amar.txt': 2}, 'sesenta': {'El arte de amar.txt': 1}, 'años,': {'El arte de amar.txt': 6}, 'haber': {'El arte de amar.txt': 10}, 'podido': {'El arte de amar.txt': 2}, 'alcanzar': {'El arte de amar.txt': 1}, 'regreso': {'El arte de amar.txt': 1}, 'seno': {'El arte de amar.txt': 2}, 'familia,': {'El arte de amar.txt': 1}, 'amada': {'El arte de amar.txt': 4}, 'patria.': {'El arte de amar.txt': 1}, 'copiosas': {'El arte de amar.txt': 1}, 'producciones': {'El arte de amar.txt': 1}, 'merecen': {'El arte de amar.txt': 1}, 'lugar': {'El arte de amar.txt': 5}, 'poesías': {'El arte de amar.txt': 2}, 'galantes,': {'El arte de amar.txt': 1}, 'imitó': {'El arte de amar.txt': 1}, 'griegos,': {'El arte de amar.txt': 1}, 'aficionadísimos': {'El arte de amar.txt': 1}, 'composiciones': {'El arte de amar.txt': 3}, 'licenciosas,': {'El arte de amar.txt': 1}, 'puede': {'El arte de amar.txt': 11}, 'ver': {'El arte de amar.txt': 8}, 'safo,': {'El arte de amar.txt': 1}, 'anacreonte': {'El arte de amar.txt': 2}, 'varios.': {'El arte de amar.txt': 1}, 'apareció': {'El arte de amar.txt': 2}, '_arte': {'El arte de amar.txt': 6}, 'amar_,': {'El arte de amar.txt': 2}, 'debió': {'El arte de amar.txt': 1}, 'causar': {'El arte de amar.txt': 1}, 'mucho': {'El arte de amar.txt': 7}, 'ruido': {'El arte de amar.txt': 3}, 'aquella': {'El arte de amar.txt': 13}, 'capital': {'El arte de amar.txt': 1}, 'orbe': {'El arte de amar.txt': 3}, 'conocido,': {'El arte de amar.txt': 1}, 'porque': {'El arte de amar.txt': 55}, 'aunque': {'El arte de amar.txt': 28}, 'corrupción': {'El arte de amar.txt': 1}, 'costumbres,': {'El arte de amar.txt': 2}, 'riquezas': {'El arte de amar.txt': 3}, 'lujo,': {'El arte de amar.txt': 1}, 'había': {'El arte de amar.txt': 16}, 'colmo,': {'El arte de amar.txt': 1}, 'duraban': {'El arte de amar.txt': 1}, 'todavía': {'El arte de amar.txt': 1}, 'ciertos': {'El arte de amar.txt': 1}, 'usos': {'El arte de amar.txt': 1}, 'leyes,': {'El arte de amar.txt': 5}, 'sombra': {'El arte de amar.txt': 5}, 'antigua': {'El arte de amar.txt': 1}, 'austeridad': {'El arte de amar.txt': 1}, 'republicana,': {'El arte de amar.txt': 1}, 'apariencia': {'El arte de amar.txt': 3}, 'condenaban': {'El arte de amar.txt': 1}, 'toda': {'El arte de amar.txt': 10}, 'relajación': {'El arte de amar.txt': 1}, 'desorden;': {'El arte de amar.txt': 1}, 'sería': {'El arte de amar.txt': 4}, 'ciertamente': {'El arte de amar.txt': 3}, 'cosa': {'El arte de amar.txt': 3}, 'extraña': {'El arte de amar.txt': 1}, 'preceptivo,': {'El arte de amar.txt': 1}, 'enseñaba': {'El arte de amar.txt': 2}, 'práctica': {'El arte de amar.txt': 2}, 'misma': {'El arte de amar.txt': 19}, 'corrupción,': {'El arte de amar.txt': 1}, 'si': {'El arte de amar.txt': 118}, 'capaz': {'El arte de amar.txt': 3}, 'introducirla,': {'El arte de amar.txt': 1}, 'lo': {'El arte de amar.txt': 105}, 'menos': {'El arte de amar.txt': 17}, 'suponía': {'El arte de amar.txt': 1}, 'hacía': {'El arte de amar.txt': 3}, 'pública': {'El arte de amar.txt': 1}, 'interiormente': {'El arte de amar.txt': 1}, 'contagiaba': {'El arte de amar.txt': 1}, 'indicio': {'El arte de amar.txt': 3}, 'decadencia.': {'El arte de amar.txt': 1}, 'cierto': {'El arte de amar.txt': 4}, 'halló': {'El arte de amar.txt': 2}, 'tan': {'El arte de amar.txt': 19}, 'eficaz,': {'El arte de amar.txt': 1}, 'cometer': {'El arte de amar.txt': 1}, 'adulterios_:': {'El arte de amar.txt': 1}, 'juicio': {'El arte de amar.txt': 7}, 'que,': {'El arte de amar.txt': 9}, 'según': {'El arte de amar.txt': 7}, 'unos,': {'El arte de amar.txt': 1}, 'verdadera': {'El arte de amar.txt': 2}, 'causa': {'El arte de amar.txt': 9}, 'destierro': {'El arte de amar.txt': 1}, 'autor,': {'El arte de amar.txt': 2}, 'otros,': {'El arte de amar.txt': 2}, 'pretexto': {'El arte de amar.txt': 2}, 'para': {'El arte de amar.txt': 135}, 'castigarle': {'El arte de amar.txt': 1}, 'agravios': {'El arte de amar.txt': 2}, 'privados.': {'El arte de amar.txt': 1}, 'sea': {'El arte de amar.txt': 23}, 'esto': {'El arte de amar.txt': 30}, 'fuere,': {'El arte de amar.txt': 1}, 've': {'El arte de amar.txt': 3}, 'castigado': {'El arte de amar.txt': 2}, 'culpas': {'El arte de amar.txt': 1}, 'amorosas,': {'El arte de amar.txt': 2}, 'seguramente': {'El arte de amar.txt': 1}, 'arrastraba': {'El arte de amar.txt': 1}, 'natural': {'El arte de amar.txt': 3}, 'propensión.': {'El arte de amar.txt': 1}, 'español': {'El arte de amar.txt': 1}, 'impropiedad': {'El arte de amar.txt': 1}, 'podríamos': {'El arte de amar.txt': 1}, 'llamar': {'El arte de amar.txt': 3}, 'enamorar_,': {'El arte de amar.txt': 1}, 'cortejar_,': {'El arte de amar.txt': 1}, 'está': {'El arte de amar.txt': 21}, 'dividido': {'El arte de amar.txt': 1}, 'libros.': {'El arte de amar.txt': 1}, 'primero': {'El arte de amar.txt': 5}, 'enseñan': {'El arte de amar.txt': 2}, 'dos': {'El arte de amar.txt': 18}, 'cosas:': {'El arte de amar.txt': 2}, 'habían': {'El arte de amar.txt': 5}, 'buscar': {'El arte de amar.txt': 3}, 'mujeres': {'El arte de amar.txt': 25}, 'quisiesen': {'El arte de amar.txt': 1}, 'amar,': {'El arte de amar.txt': 3}, 'modo': {'El arte de amar.txt': 15}, 'propiciar': {'El arte de amar.txt': 4}, 'poseer': {'El arte de amar.txt': 1}, 'corazón.': {'El arte de amar.txt': 3}, 'segundo': {'El arte de amar.txt': 1}, 'dan': {'El arte de amar.txt': 6}, 'preceptos': {'El arte de amar.txt': 5}, 'duradero.': {'El arte de amar.txt': 2}, 'tercero,': {'El arte de amar.txt': 1}, 'hablando': {'El arte de amar.txt': 1}, 'mujeres,': {'El arte de amar.txt': 11}, 'les': {'El arte de amar.txt': 20}, 'dicta': {'El arte de amar.txt': 3}, 'reglas': {'El arte de amar.txt': 3}, 'amar': {'El arte de amar.txt': 4}, 'competir': {'El arte de amar.txt': 1}, 'hombres.': {'El arte de amar.txt': 7}, 'plan,': {'El arte de amar.txt': 1}, 'forma': {'El arte de amar.txt': 3}, 'pasión': {'El arte de amar.txt': 4}, 'amorosa': {'El arte de amar.txt': 3}, 'una': {'El arte de amar.txt': 68}, 'guerra': {'El arte de amar.txt': 5}, 'hombres': {'El arte de amar.txt': 19}, 'mujeres:': {'El arte de amar.txt': 1}, 'verdad': {'El arte de amar.txt': 4}, 'muy': {'El arte de amar.txt': 14}, 'propia': {'El arte de amar.txt': 2}, 'sublime,': {'El arte de amar.txt': 1}, 'tomada': {'El arte de amar.txt': 2}, 'ingeniosamente': {'El arte de amar.txt': 1}, 'naturaleza': {'El arte de amar.txt': 6}, 'preocupaciones': {'El arte de amar.txt': 1}, 'sexos.': {'El arte de amar.txt': 1}, 'tiene': {'El arte de amar.txt': 18}, 'todas': {'El arte de amar.txt': 14}, 'cualidades': {'El arte de amar.txt': 2}, 'didascálico:': {'El arte de amar.txt': 1}, 'brillan': {'El arte de amar.txt': 1}, 'principios,': {'El arte de amar.txt': 1}, 'invención': {'El arte de amar.txt': 2}, 'orden': {'El arte de amar.txt': 3}, 'cuanto': {'El arte de amar.txt': 12}, 'arte;': {'El arte de amar.txt': 3}, 'locución,': {'El arte de amar.txt': 1}, 'belleza,': {'El arte de amar.txt': 1}, 'elegancia,': {'El arte de amar.txt': 1}, 'armonía,': {'El arte de amar.txt': 1}, 'laconismo': {'El arte de amar.txt': 1}, 'pureza': {'El arte de amar.txt': 1}, 'latina.': {'El arte de amar.txt': 1}, 'episodios,': {'El arte de amar.txt': 1}, 'parte': {'El arte de amar.txt': 19}, 'accesoria,': {'El arte de amar.txt': 1}, 'mérito,': {'El arte de amar.txt': 1}, 'enlace,': {'El arte de amar.txt': 1}, 'delicadeza': {'El arte de amar.txt': 1}, 'hermosura,': {'El arte de amar.txt': 3}, 'mi': {'El arte de amar.txt': 61}, 'concepto': {'El

Por ejemplo la pabra nota aparece 2 veces en el documento `El arte de amar.txt`

In [3]:
# Representacion en tabla
import pandas as pd

df = pd.DataFrame(list(indice_invertido.items()), columns=['Palabra', 'Archivos'])
df

            Palabra                       Archivos
0              nota     {'El arte de amar.txt': 2}
1                de  {'El arte de amar.txt': 1004}
2     transcripción     {'El arte de amar.txt': 2}
3                 *     {'El arte de amar.txt': 6}
4               las   {'El arte de amar.txt': 467}
...             ...                            ...
8165        cisnes.     {'El arte de amar.txt': 1}
8166     discípulas     {'El arte de amar.txt': 1}
8167           mías     {'El arte de amar.txt': 1}
8168       escriban     {'El arte de amar.txt': 1}
8169         _fin._     {'El arte de amar.txt': 1}

[8170 rows x 2 columns]

#### **Calculo de la Frecuencia de Terminos (TF)**

In [4]:
import math 
#diccionario para guardar los valores de TF calculados
tf_documento = {}

# recorrer la clave (palabra) y su valor (el sub-diccionario de documentos)
for palabra, documentos in indice_invertido.items():
    
    # frecuencia  (f) buscando el documento en el sub-diccionario
    f = documentos[nombre_documento] 
    
    # formula TF
    tf = 1 + math.log10(f) 
    
    # Guardar el resultado en nuevo diccionario
    tf_documento[palabra] = tf

print(tf_documento)

{'nota': 1.3010299956639813, 'de': 4.001733712809001, 'transcripción': 1.3010299956639813, '*': 1.7781512503836436, 'las': 3.6693168805661123, 'cursivas': 1.0, 'se': 3.5185139398778875, 'muestran': 1.3010299956639813, 'entre': 2.4471580313422194, '_subrayados_.': 1.0, 'los': 3.725094521081469, 'errores': 1.3010299956639813, 'imprenta': 1.0, 'han': 2.1760912590556813, 'sido': 1.9542425094393248, 'corregidos.': 1.0, 'la': 3.921166050637739, 'ortografía': 1.0, 'del': 3.250420002308894, 'texto': 1.3010299956639813, 'original': 1.6020599913279625, 'ha': 2.653212513775344, 'modernizada': 1.3010299956639813, 'acuerdo': 1.0, 'con': 3.6483600109809315, 'normas': 1.0, 'publicadas': 1.0, 'en': 3.727541257028556, '2010': 1.0, 'por': 3.3283796034387376, 'real': 1.0, 'academia': 1.0, 'española.': 1.0, 'también': 2.5440680443502757, 'nombres': 1.4771212547196624, 'propios,': 1.0, 'tanto': 2.146128035678238, 'lugares': 1.6020599913279625, 'como': 3.0043213737826426, 'personajes.': 1.0, 'notas': 1.3010299956639813, 'a': 3.800717078282385, 'pie': 1.6989700043360187, 'página': 1.0, 'renemeradas': 1.0, 'y': 3.888179493918325, 'colocadas': 1.0, 'tras': 1.3010299956639813, 'el': 3.8555191556678, 'párrafo': 1.0, 'que': 3.800717078282385, 'contiene': 1.4771212547196624, 'su': 3.357934847000454, 'llamada.': 1.0, 'páginas': 1.0, 'blanco': 1.7781512503836436, 'eliminadas.': 1.0, 'arte': 2.3979400086720375, 'amar.': 1.7781512503836436, 'traductor': 1.0, 'ovidio': 1.9542425094393248, 'sus': 3.146128035678238, 'obras': 1.3010299956639813, 'escrito': 1.3010299956639813, 'otras': 2.361727836017593, 'plumas': 1.4771212547196624, 'más': 2.9867717342662448, 'bien': 2.4471580313422194, 'cortadas': 1.0, 'mía;': 1.0, 'así': 2.57978359661681, 'fuera': 1.7781512503836436, 'temeridad': 1.3010299956639813, 'querer': 1.0, 'añadir,': 1.0, 'o': 2.6720978579357175, 'superfluidad': 1.0, 'copiar': 1.0, 'eruditos': 1.0, 'emprendieron': 1.0, 'aquel': 2.380211241711606, 'trabajo.': 1.0, 'demás': 1.845098040014257, 'comentarios': 1.0, 'rapsodias': 1.0, 'no': 3.5327543789924976, 'son': 2.591064607026499, 'ya': 2.6989700043360187, 'gusto': 1.4771212547196624, 'nuestro': 1.9030899869919435, 'siglo;': 1.0, 'cual,': 1.0, 'todos,': 1.4771212547196624, 'aspira': 1.0, 'instruirse': 1.0, 'solidez': 1.0, 'es': 3.1335389083702174, 'necesario': 1.6989700043360187, 'recurra': 1.0, 'fuentes,': 1.0, 'sin': 2.8260748027008264, 'contentarse': 1.3010299956639813, 'vagas': 1.0, 'repeticiones,': 1.3010299956639813, 'noticias': 1.0, 'tal': 2.204119982655925, 'vez': 2.255272505103306, 'corrompidas.': 1.0, 'pero': 2.8750612633917, 'yo': 2.5051499783199063, 'traduzco': 1.0, 'un': 2.929418925714293, 'poema': 1.6020599913279625, 'ovidio,': 1.0, 'andar': 1.4771212547196624, 'manos': 2.146128035678238, 'mis': 2.462397997898956, 'lectores': 1.0, 'habrá': 1.6989700043360187, 'muchos': 2.079181246047625, 'oído': 1.3010299956639813, 'siquiera': 1.0, 'nombre;': 1.4771212547196624, 'otros': 2.278753600952829, 'apenas': 2.0413926851582254, 'tienen': 2.0, 'idea': 1.3010299956639813, 'superficial': 1.0, 'él': 2.342422680822206, 'poesías.': 1.0, 'he': 2.4313637641589874, 'aquí': 2.230448921378274, 'qué': 2.4471580313422194, 'puedo': 1.3010299956639813, 'pasar': 1.4771212547196624, 'todo': 2.462397997898956, 'silencio': 1.4771212547196624, 'algunas': 2.0413926851582254, 'circunstancias': 1.3010299956639813, 'este': 2.6627578316815743, 'meritísimo': 1.0, 'autor.': 1.0, 'p.': 1.0, 'nasón,': 1.0, 'caballero': 1.0, 'romano,': 1.0, 'nació': 1.4771212547196624, 'sulmona,': 1.0, 'ciudad': 1.6989700043360187, 'abruzo,': 1.0, 'cuarenta': 1.0, 'tres': 1.9030899869919435, 'años': 1.7781512503836436, 'antes': 2.113943352306837, 'era': 2.57978359661681, 'vulgar,': 1.0, 'mismo': 2.380211241711606, 'día': 2.255272505103306, 'fue': 2.5314789170422554, 'muerto': 1.3010299956639813, 'elocuente': 1.4771212547196624, 'cicerón.': 1.0, 'roma,': 1.3010299956639813, 'donde': 2.3222192947339195, 'llevado': 1.0, 'corta': 1.0, 'edad,': 1.6020599913279625, 'dio': 1.845098040014257, 'letras': 1.6989700043360187, 'bajo': 1.6020599913279625, 'dirección': 1.0, 'plocio': 1.0, 'gripo;': 1.0, 'mostrando': 1.0, 'agudo': 1.0, 'ingenio,': 1.3010299956639813, 'dieciséis': 1.0, 'le': 2.740362689494244, 'enviaron': 1.0, 'atenas,': 1.3010299956639813, 'estudió': 1.0, 'ciencias,': 1.0, 'perfeccionó': 1.3010299956639813, 'lengua': 1.845098040014257, 'griega.': 1.0, 'escuelas': 1.0, 'atenienses': 1.0, 'eran': 2.0, 'entonces': 2.380211241711606, 'frecuentadas': 1.0, 'juventud': 1.4771212547196624, 'romana,': 1.0, 'autor': 1.4771212547196624, 'latino': 1.3010299956639813, 'formase': 1.0, 'ellas.': 1.6989700043360187, 'quiso': 1.0, 'padre': 2.0413926851582254, 'obligarle': 1.0, 'seguir': 1.3010299956639813, 'carrera': 1.3010299956639813, 'foro,': 1.6020599913279625, 'efecto': 1.6020599913279625, 'obedecerle': 1.0, 'siguió': 1.0, 'algún': 1.9030899869919435, 'tiempo,': 1.4771212547196624, 'hasta': 2.0413926851582254, 'padre,': 1.845098040014257, 'abandonó': 1.0, 'deliciosas': 1.0, 'musas,': 1.3010299956639813, 'llamaba': 1.3010299956639813, 'innata': 1.0, 'inclinación.': 1.0, 'tuvo': 1.4771212547196624, 'maestros': 1.0, 'filosofía': 1.4771212547196624, 'porcio': 1.0, 'latrón,': 1.0, 'retórica': 1.0, 'marcelo': 1.0, 'fusco,': 1.0, 'gramática': 1.0, 'julio': 1.0, 'grecino,': 1.0, 'profesores': 1.0, 'llevaban': 1.0, 'aplauso': 1.6020599913279625, 'roma.': 1.4771212547196624, 'bueno': 1.3010299956639813, 'e': 1.7781512503836436, 'ingenioso': 1.0, 'orador,': 1.0, 'afluente': 1.0, 'patético': 1.0, 'poeta,': 1.3010299956639813, 'engrandecía': 1.0, 'animaba': 1.0, 'cuantos': 1.4771212547196624, 'asuntos': 1.0, 'encomendaba': 1.0, 'pluma;': 1.0, 'demasiadas': 1.0, 'flores': 1.6020599913279625, 'exornó': 1.0, 'versos,': 1.6020599913279625, 'prodigadas': 1.0, 'facilidad': 1.0, 'ardiente': 1.0, 'fecunda': 1.0, 'imaginación,': 1.0, 'apartaron': 1.0, 'noble': 1.0, 'sencilla': 1.3010299956639813, 'majestad': 1.0, 'arte.': 1.6989700043360187, 'dicen': 1.6989700043360187, 'tenía': 1.845098040014257, 'amor': 2.5314789170422554, 'propio,': 1.0, 'solo': 2.462397997898956, 'desconocía,': 1.0, 'sino': 2.414973347970818, 'amaba': 1.3010299956639813, 'defectos,': 1.0, 'negándose': 1.0, 'corregirlos,': 1.0, 'aun': 2.0413926851582254, 'cuando': 2.8750612633917, 'amigos': 1.0, 'advirtiesen.': 1.0, '¡debilidad': 1.0, 'humana,': 1.0, 'eximen': 1.0, 'mayores': 1.4771212547196624, 'hombres!': 1.0, 'gozó': 1.0, 'roma': 1.4771212547196624, 'honores': 1.0, 'beneficios': 1.0, 'augusto': 1.6020599913279625, 'acostumbraba': 1.0, 'remunerar': 1.0, 'grandes': 1.6020599913279625, 'talentos,': 1.0, 'hubiera': 2.113943352306837, 'acaso': 2.0413926851582254, 'llegado': 1.6020599913279625, 'mayor': 2.0, 'fortuna': 1.3010299956639813, 'poetas': 1.6989700043360187, 'contemporáneos;': 1.0, 'desgracia,': 1.0, 'al': 3.2380461031287955, 'hombre': 1.845098040014257, 'dado': 1.7781512503836436, 'pocas': 1.3010299956639813, 'veces': 2.6434526764861874, 'evitar,': 1.0, 'proporcionó': 1.0, 'amores': 1.6020599913279625, 'julia,': 1.0, 'hija': 1.7781512503836436, 'tiberio,': 1.0, 'quien': 2.4471580313422194, 'escribió': 1.0, 'epístolas': 1.0, 'amatorias,': 1.3010299956639813, 'cuales': 1.9030899869919435, 'miró': 1.4771212547196624, 'delito': 1.6020599913279625, 'lesa': 1.0, 'majestad,': 1.0, 'mandó': 1.0, 'quemar,': 1.0, 'desterrando': 1.0, 'villa': 1.0, 'tomos': 1.0, 'ponto': 1.0, 'euxino.': 1.0, 'allí': 2.3010299956639813, 'murió': 1.0, 'edad': 1.845098040014257, 'cerca': 1.3010299956639813, 'sesenta': 1.0, 'años,': 1.7781512503836436, 'haber': 2.0, 'podido': 1.3010299956639813, 'alcanzar': 1.0, 'regreso': 1.0, 'seno': 1.3010299956639813, 'familia,': 1.0, 'amada': 1.6020599913279625, 'patria.': 1.0, 'copiosas': 1.0, 'producciones': 1.0, 'merecen': 1.0, 'lugar': 1.6989700043360187, 'poesías': 1.3010299956639813, 'galantes,': 1.0, 'imitó': 1.0, 'griegos,': 1.0, 'aficionadísimos': 1.0, 'composiciones': 1.4771212547196624, 'licenciosas,': 1.0, 'puede': 2.0413926851582254, 'ver': 1.9030899869919435, 'safo,': 1.0, 'anacreonte': 1.3010299956639813, 'varios.': 1.0, 'apareció': 1.3010299956639813, '_arte': 1.7781512503836436, 'amar_,': 1.3010299956639813, 'debió': 1.0, 'causar': 1.0, 'mucho': 1.845098040014257, 'ruido': 1.4771212547196624, 'aquella': 2.113943352306837, 'capital': 1.0, 'orbe': 1.4771212547196624, 'conocido,': 1.0, 'porque': 2.740362689494244, 'aunque': 2.4471580313422194, 'corrupción': 1.0, 'costumbres,': 1.3010299956639813, 'riquezas': 1.4771212547196624, 'lujo,': 1.0, 'había': 2.204119982655925, 'colmo,': 1.0, 'duraban': 1.0, 'todavía': 1.0, 'ciertos': 1.0, 'usos': 1.0, 'leyes,': 1.6989700043360187, 'sombra': 1.6989700043360187, 'antigua': 1.0, 'austeridad': 1.0, 'republicana,': 1.0, 'apariencia': 1.4771212547196624, 'condenaban': 1.0, 'toda': 2.0, 'relajación': 1.0, 'desorden;': 1.0, 'sería': 1.6020599913279625, 'ciertamente': 1.4771212547196624, 'cosa': 1.4771212547196624, 'extraña': 1.0, 'preceptivo,': 1.0, 'enseñaba': 1.3010299956639813, 'práctica': 1.3010299956639813, 'misma': 2.278753600952829, 'corrupción,': 1.0, 'si': 3.0718820073061255, 'capaz': 1.4771212547196624, 'introducirla,': 1.0, 'lo': 3.0211892990699383, 'menos': 2.230448921378274, 'suponía': 1.0, 'hacía': 1.4771212547196624, 'pública': 1.0, 'interiormente': 1.0, 'contagiaba': 1.0, 'indicio': 1.4771212547196624, 'decadencia.': 1.0, 'cierto': 1.6020599913279625, 'halló': 1.3010299956639813, 'tan': 2.278753600952829, 'eficaz,': 1.0, 'cometer': 1.0, 'adulterios_:': 1.0, 'juicio': 1.845098040014257, 'que,': 1.9542425094393248, 'según': 1.845098040014257, 'unos,': 1.0, 'verdadera': 1.3010299956639813, 'causa': 1.9542425094393248, 'destierro': 1.0, 'autor,': 1.3010299956639813, 'otros,': 1.3010299956639813, 'pretexto': 1.3010299956639813, 'para': 3.130333768495006, 'castigarle': 1.0, 'agravios': 1.3010299956639813, 'privados.': 1.0, 'sea': 2.361727836017593, 'esto': 2.4771212547196626, 'fuere,': 1.0, 've': 1.4771212547196624, 'castigado': 1.3010299956639813, 'culpas': 1.0, 'amorosas,': 1.3010299956639813, 'seguramente': 1.0, 'arrastraba': 1.0, 'natural': 1.4771212547196624, 'propensión.': 1.0, 'español': 1.0, 'impropiedad': 1.0, 'podríamos': 1.0, 'llamar': 1.4771212547196624, 'enamorar_,': 1.0, 'cortejar_,': 1.0, 'está': 2.3222192947339195, 'dividido': 1.0, 'libros.': 1.0, 'primero': 1.6989700043360187, 'enseñan': 1.3010299956639813, 'dos': 2.255272505103306, 'cosas:': 1.3010299956639813, 'habían': 1.6989700043360187, 'buscar': 1.4771212547196624, 'mujeres': 2.3979400086720375, 'quisiesen': 1.0, 'amar,': 1.4771212547196624, 'modo': 2.1760912590556813, 'propiciar': 1.6020599913279625, 'poseer': 1.0, 'corazón.': 1.4771212547196624, 'segundo': 1.0, 'dan': 1.7781512503836436, 'preceptos': 1.6989700043360187, 'duradero.': 1.3010299956639813, 'tercero,': 1.0, 'hablando': 1.0, 'mujeres,': 2.0413926851582254, 'les': 2.3010299956639813, 'dicta': 1.4771212547196624, 'reglas': 1.4771212547196624, 'amar': 1.6020599913279625, 'competir': 1.0, 'hombres.': 1.845098040014257, 'plan,': 1.0, 'forma': 1.4771212547196624, 'pasión': 1.6020599913279625, 'amorosa': 1.4771212547196624, 'una': 2.8325089127062366, 'guerra': 1.6989700043360187, 'hombres': 2.278753600952829, 'mujeres:': 1.0, 'verdad': 1.6020599913279625, 'muy': 2.146128035678238, 'propia': 1.3010299956639813, 'sublime,': 1.0, 'tomada': 1.3010299956639813, 'ingeniosamente': 1.0, 'naturaleza': 1.7781512503836436, 'preocupaciones': 1.0, 'sexos.': 1.0, 'tiene': 2.255272505103306, 'todas': 2.146128035678238, 'cualidades': 1.3010299956639813, 'didascálico:': 1.0, 'brillan': 1.0, 'principios,': 1.0, 'invención': 1.3010299956639813, 'orden': 1.4771212547196624, 'cuanto': 2.079181246047625, 'arte;': 1.4771212547196624, 'locución,': 1.0, 'belleza,': 1.0, 'elegancia,': 1.0, 'armonía,': 1.0, 'laconismo': 1.0, 'pureza': 1.0, 'latina.': 1.0, 'episodios,': 1.0, 'parte': 2.278753600952829, 'accesoria,': 1.0, 'mérito,': 1.0, 'enlace,': 1.0, 'delicadeza': 1.0, 'hermosura,': 1.4771212547196624, 'mi': 2.785329835010767, 'concepto': 1.0, 'exceden': 1.3010299956639813, 'cuerpo': 2.0413926851582254, 'obra.': 1.9030899869919435, '¡ah,': 1.4771212547196624, 'me': 2.7160033436347994, 'hubiese': 1.3010299956639813, 'conservar': 1.4771212547196624, 'traducción': 1.4771212547196624, 'belleza': 1.6020599913279625, 'confusión': 1.0, 'presuntuosos': 1.0, 'modernos,': 1.0, 'creen': 1.0, 'igualar': 1.0, 'padres': 1.0, 'buen': 1.7781512503836436, 'desdeñando': 1.0, 'estudio': 1.6020599913279625, 'lengua!': 1.0, '¿y': 1.9030899869919435, 'quién': 1.9542425094393248, 'podrá': 1.3010299956639813, 'alabar': 1.4771212547196624, 'dignamente': 1.0, 'trata': 1.3010299956639813, 'amor,': 1.9542425094393248, 'conveniente': 1.4771212547196624, 'poesía,': 1.0, 'modernos': 1.0, 'nos': 2.079181246047625, 'escasos': 1.3010299956639813, 'ejemplos,': 1.0, 'antiguos': 1.6989700043360187, 'poseían': 1.0, 'sabían': 1.0, 'emplear': 1.3010299956639813, 'magisterio?': 1.0, 'usa': 1.0, 'esta': 2.690196080028514, 'composición': 1.0, 'versos': 2.113943352306837, 'elegíacos,': 1.0, 'carácter': 1.3010299956639813, 'sencillos,': 1.0, 'tiernos': 1.3010299956639813, 'sentenciosos.': 1.0, 'procurado': 1.4771212547196624, 'ceñirme': 1.0, 'original:': 1.3010299956639813, 'vestir': 1.3010299956639813, 'latín': 1.0, 'castellano,': 1.0, 'latín:': 1.0, 'prosa': 1.0, 'sabor': 1.0, 'poético,': 1.0, 'tono': 1.0, 'elevado': 1.3010299956639813, 'metafórico': 1.0, 'empresa': 1.3010299956639813, 'harto': 1.3010299956639813, 'inaccesible': 1.0, 'débiles': 1.0, 'fuerzas.': 1.0, 'verá': 1.0, 'gracia': 1.6989700043360187, 'poética': 1.3010299956639813, 'original,': 1.3010299956639813, 'consiste': 1.4771212547196624, 'sonoridad': 1.0, 'métrica,': 1.0, 'transposiciones,': 1.0, 'conjunciones,': 1.0, 'voces': 1.4771212547196624, 'equivalente,': 1.0, 'transiciones,': 1.0, 'alusiones': 1.0, 'peculiares': 1.0, 'tiempos': 1.3010299956639813, 'fin,': 1.0, 'alguna': 2.0413926851582254, 'aquellas': 1.845098040014257, 'ni': 3.041392685158225, 'pueden': 1.845098040014257, 'conservar,': 1.0, 'tendrían': 1.0, 'mérito': 1.0, 'lenguas': 1.4771212547196624, 'vivas;': 1.0, 'conservadas,': 1.0, 'serían': 1.3010299956639813, 'opinión': 1.3010299956639813, 'juiciosos': 1.0, 'ripio': 1.0, 'pedantería.': 1.0, 'diferencia': 1.0, 'regla': 1.3010299956639813, 'fundamental,': 1.0, 'eso': 1.6020599913279625, 'duda': 1.6020599913279625, 'viciosas': 1.0, 'traducciones': 1.0, 'servilmente': 1.0, 'literales,': 1.0, 'excesivamente': 1.0, 'libres.': 1.0, 'otra': 2.079181246047625, 'debe': 1.4771212547196624, 'ostentar': 1.0, 'sostener': 1.0, 'estilo': 1.6989700043360187, 'poético;': 1.0, 'contrario,': 1.0, 'perteneciendo': 1.0, 'género': 1.6020599913279625, 'didascálico,': 1.0, 'forzado': 1.0, 'imitar': 1.0, 'naturalidad': 1.0, 'prosaica': 1.0, 'hacer': 1.7781512503836436, 'claros': 1.0, 'preceptos,': 1.3010299956639813, 'reservando': 1.0, 'episodios': 1.0, 'pompa,': 1.0, 'sublimidad': 1.0, 'riqueza.': 1.0, 'pues': 2.7634279935629373, 'véase': 1.0, 'episódica': 1.0, 'resalta': 1.0, 'traducción;': 1.0, 'hallarán': 1.6020599913279625, 'poesía': 1.0, 'altisonante,': 1.0, 'invención,': 1.0, 'variedad,': 1.0, 'propiedad': 1.0, 'fluidez.': 1.0, 'estoy': 1.6020599913279625, 'persuadido': 1.0, 'presente': 1.4771212547196624, 'excede': 1.0, 'extranjeras': 1.0, 'visto,': 1.0, 'única': 1.6020599913279625, 'castellana': 1.0, 'verso': 1.0, 'imprimió,': 1.0, 'hecho': 1.4771212547196624, 'rara,': 1.0, 'raros': 1.0, 'saben': 1.0, 'hay;': 1.0, 'ninguna': 1.845098040014257, 'conviene': 2.0, 'debe.': 1.0, 'redundancia,': 1.0, 'inexactitud,': 1.0, 'mal': 2.204119982655925, 'lenguaje': 1.3010299956639813, 'arbitrariedad': 1.0, 'principales': 1.0, 'defectos:': 1.0, 'palabra,': 1.0, 'traducir': 1.0, 'hallan': 1.3010299956639813, 'quebrantadas': 1.0, 'ellas': 2.0413926851582254, 'abiertamente.': 1.0, 'basta:': 1.0, 'ánimo': 1.4771212547196624, 'criticar,': 1.0, 'presentar': 1.0, 'público': 1.0, 'adelantar': 1.0, 'sobre': 2.342422680822206, 'precedieron.': 1.0, 'llamado': 1.3010299956639813, 'amatorio_,': 1.0, 'verdadero': 1.3010299956639813, 'título,': 1.0, 'manuscritos': 1.0, 'existen': 1.0, 'poema,': 1.0, 'autoridad': 1.0, 'varios': 1.0, 'escritores': 1.3010299956639813, 'hablaron': 1.0, 'él,': 1.6020599913279625, 'citan.': 1.0, 'aún': 1.9030899869919435, 'tenemos': 1.3010299956639813, 'ejemplar': 1.0, 'correcto': 1.0, 'ovidio:': 1.0, 'todos': 2.1760912590556813, 'códices': 1.0, 'estan': 1.4771212547196624, 'llenos': 1.6989700043360187, 'variantes,': 1.0, 'ponen': 1.3010299956639813, 'perplejidad': 1.3010299956639813, 'peritos': 1.0, 'latina,': 1.0, 'trabajaron': 1.0, 'purificar': 1.0, 'conciliarlo,': 1.0, 'estudiando': 1.0, 'confrontando': 1.0, 'unos': 1.6989700043360187, 'pasajes': 1.0, 'análogos,': 1.0, 'algunos': 1.4771212547196624, 'coinciden': 1.0, 'mismos': 1.7781512503836436, 'pensamientos.': 1.0, 'razón': 1.9030899869919435, 'vi': 1.4771212547196624, 'casi': 1.0, 'precisado': 1.0, 'muchas': 2.6020599913279625, 'adivinar': 1.0, 'sentido': 1.0, 'genuino,': 1.0, 'interpretarlo,': 1.0, 'dejarlo': 1.3010299956639813, 'imperfecto,': 1.0, 'cediendo': 1.3010299956639813, 'necesidad': 1.0, 'leer': 1.3010299956639813, 'halla': 1.6020599913279625, 'escrito,': 1.3010299956639813, 'conformarme': 1.0, 'puntuación': 1.0, 'prosódica': 1.0, 'ortográfica.': 1.0, 'sigo': 1.0, 'edición': 1.0, 'leyden,': 1.0, 'pasa': 1.3010299956639813, 'ilustrada': 1.0, 'correcta,': 1.0, 'confesando': 1.0, 'debido': 1.0, 'mucha': 1.4771212547196624, 'luz': 1.6989700043360187, 'entender': 1.3010299956639813, 'guía': 1.6020599913279625, 'iría': 1.0, 'ciegas,': 1.0, 'ella,': 1.6989700043360187, 'prometo': 1.0, 'entero': 1.0, 'acierto.': 1.0, 'libro': 1.4771212547196624, 'primero.': 1.0, 'romano': 1.0, 'ignora': 1.0, 'lea': 1.0, 'enseñado': 1.3010299956639813, 'lectura,': 1.0, 'ame.': 1.0, 'ligera': 1.6020599913279625, 'nao': 1.3010299956639813, 'vela': 1.6989700043360187, 'remos:': 1.0, 'rigen': 1.0, 'voladores': 1.0, 'carros,': 1.0, 'ser': 2.5185139398778875, 'regido': 1.0, 'amor.': 2.255272505103306, 'automedonte': 1.4771212547196624, 'diestro': 1.0, 'carros': 1.0, 'caballos,': 1.4771212547196624, 'tifis': 1.3010299956639813, 'piloto': 1.3010299956639813, 'nave': 1.3010299956639813, 'argonáutica;': 1.0, 'empero': 1.9030899869919435, 'mí': 2.0413926851582254, 'designó': 1.0, 'venus': 2.3010299956639813, 'maestro': 1.3010299956639813, 'tierno': 1.4771212547196624, 'amor;': 1.3010299956639813, 'llamará': 1.3010299956639813, 'gente.': 1.3010299956639813, 'fiero': 1.0, 'contrasta': 1.0, 'veces;': 1.0, 'mas': 2.255272505103306, 'niño,': 1.0, 'blanda': 1.4771212547196624, 'dispuesto': 1.0, 'tornarse': 1.0, 'dócil.': 1.0, 'quirón': 1.3010299956639813, 'muchacho': 1.7781512503836436, 'aquiles': 1.6020599913279625, 'sonidos': 1.0, 'cítara,': 1.0, 'amansando': 1.0, 'armoniosa': 1.3010299956639813, 'fiereza': 1.0, 'ánimo.': 1.0, 'tantas': 2.0, 'puso': 1.6989700043360187, 'grima': 1.0, 'compañeros': 1.4771212547196624, 'enemigos,': 1.0, 'temía': 1.3010299956639813, 'delante': 1.9542425094393248, 'añoso': 1.0, 'viejo,': 1.3010299956639813, 'presentaba': 1.0, 'obediente': 1.0, 'castigo': 1.3010299956639813, 'ayo': 1.0, 'aterrar': 1.0, 'héctor.': 1.3010299956639813, 'preceptor': 1.4771212547196624, 'aquiles,': 1.6020599913279625, 'uno': 2.230448921378274, 'otro': 2.230448921378274, 'duros,': 1.0, 'prole': 1.3010299956639813, 'diosa;': 1.0, 'toro': 1.7781512503836436, 'sujeta': 1.0, 'cerviz': 1.0, 'peso': 1.0, 'arado,': 1.0, 'briosos': 1.0, 'alazanes': 1.0, 'tascan': 1.0, 'freno.': 1.0, 'cederá': 1.0, 'voluntad;': 1.0, 'vibre': 1.0, 'contra': 1.9542425094393248, 'flechas,': 1.0, 'abrase': 1.0, 'pecho': 2.0413926851582254, 'teas.': 1.0, 'cruelmente': 1.0, 'hirió,': 1.0, 'violencia': 1.3010299956639813, 'atormentó,': 1.0, 'mejor': 1.7781512503836436, 'vengaré': 1.0, 'heridas.': 1.4771212547196624, 'mentiré,': 1.0, '¡oh': 1.845098040014257, 'apolo!,': 1.0, 'diciendo': 1.4771212547

In [5]:
# Representacion en tabla
df_tf = pd.DataFrame(list(tf_documento.items()), columns=['Palabra', 'TF'])
df_tf

            Palabra        TF
0              nota  1.301030
1                de  4.001734
2     transcripción  1.301030
3                 *  1.778151
4               las  3.669317
...             ...       ...
8165        cisnes.  1.000000
8166     discípulas  1.000000
8167           mías  1.000000
8168       escriban  1.000000
8169         _fin._  1.000000

[8170 rows x 2 columns]

Por ejemplo la frecuancia del termino 'nota' es 1.301

#### **Calculo de la frecuencia inversa del documento (IDF)**

In [6]:
idf_documento = {}
N = 1 # en esta ocasion se lo define en uno porque el ejemplo se hace en un solo documento

# Recorremos índice invertido
for palabra, documentos in indice_invertido.items():
    
    # Calculo df: ¿En cuántos documentos (claves) aparece la palabra?
    df = len(documentos)
    
    # Calculo IDF 
    idf = math.log10(N / df)
    
    # Guardar el resultado en el diccionario
    idf_documento[palabra] = idf
    
print (idf_documento)

{'nota': 0.0, 'de': 0.0, 'transcripción': 0.0, '*': 0.0, 'las': 0.0, 'cursivas': 0.0, 'se': 0.0, 'muestran': 0.0, 'entre': 0.0, '_subrayados_.': 0.0, 'los': 0.0, 'errores': 0.0, 'imprenta': 0.0, 'han': 0.0, 'sido': 0.0, 'corregidos.': 0.0, 'la': 0.0, 'ortografía': 0.0, 'del': 0.0, 'texto': 0.0, 'original': 0.0, 'ha': 0.0, 'modernizada': 0.0, 'acuerdo': 0.0, 'con': 0.0, 'normas': 0.0, 'publicadas': 0.0, 'en': 0.0, '2010': 0.0, 'por': 0.0, 'real': 0.0, 'academia': 0.0, 'española.': 0.0, 'también': 0.0, 'nombres': 0.0, 'propios,': 0.0, 'tanto': 0.0, 'lugares': 0.0, 'como': 0.0, 'personajes.': 0.0, 'notas': 0.0, 'a': 0.0, 'pie': 0.0, 'página': 0.0, 'renemeradas': 0.0, 'y': 0.0, 'colocadas': 0.0, 'tras': 0.0, 'el': 0.0, 'párrafo': 0.0, 'que': 0.0, 'contiene': 0.0, 'su': 0.0, 'llamada.': 0.0, 'páginas': 0.0, 'blanco': 0.0, 'eliminadas.': 0.0, 'arte': 0.0, 'amar.': 0.0, 'traductor': 0.0, 'ovidio': 0.0, 'sus': 0.0, 'obras': 0.0, 'escrito': 0.0, 'otras': 0.0, 'plumas': 0.0, 'más': 0.0, 'bien': 0.0, 'cortadas': 0.0, 'mía;': 0.0, 'así': 0.0, 'fuera': 0.0, 'temeridad': 0.0, 'querer': 0.0, 'añadir,': 0.0, 'o': 0.0, 'superfluidad': 0.0, 'copiar': 0.0, 'eruditos': 0.0, 'emprendieron': 0.0, 'aquel': 0.0, 'trabajo.': 0.0, 'demás': 0.0, 'comentarios': 0.0, 'rapsodias': 0.0, 'no': 0.0, 'son': 0.0, 'ya': 0.0, 'gusto': 0.0, 'nuestro': 0.0, 'siglo;': 0.0, 'cual,': 0.0, 'todos,': 0.0, 'aspira': 0.0, 'instruirse': 0.0, 'solidez': 0.0, 'es': 0.0, 'necesario': 0.0, 'recurra': 0.0, 'fuentes,': 0.0, 'sin': 0.0, 'contentarse': 0.0, 'vagas': 0.0, 'repeticiones,': 0.0, 'noticias': 0.0, 'tal': 0.0, 'vez': 0.0, 'corrompidas.': 0.0, 'pero': 0.0, 'yo': 0.0, 'traduzco': 0.0, 'un': 0.0, 'poema': 0.0, 'ovidio,': 0.0, 'andar': 0.0, 'manos': 0.0, 'mis': 0.0, 'lectores': 0.0, 'habrá': 0.0, 'muchos': 0.0, 'oído': 0.0, 'siquiera': 0.0, 'nombre;': 0.0, 'otros': 0.0, 'apenas': 0.0, 'tienen': 0.0, 'idea': 0.0, 'superficial': 0.0, 'él': 0.0, 'poesías.': 0.0, 'he': 0.0, 'aquí': 0.0, 'qué': 0.0, 'puedo': 0.0, 'pasar': 0.0, 'todo': 0.0, 'silencio': 0.0, 'algunas': 0.0, 'circunstancias': 0.0, 'este': 0.0, 'meritísimo': 0.0, 'autor.': 0.0, 'p.': 0.0, 'nasón,': 0.0, 'caballero': 0.0, 'romano,': 0.0, 'nació': 0.0, 'sulmona,': 0.0, 'ciudad': 0.0, 'abruzo,': 0.0, 'cuarenta': 0.0, 'tres': 0.0, 'años': 0.0, 'antes': 0.0, 'era': 0.0, 'vulgar,': 0.0, 'mismo': 0.0, 'día': 0.0, 'fue': 0.0, 'muerto': 0.0, 'elocuente': 0.0, 'cicerón.': 0.0, 'roma,': 0.0, 'donde': 0.0, 'llevado': 0.0, 'corta': 0.0, 'edad,': 0.0, 'dio': 0.0, 'letras': 0.0, 'bajo': 0.0, 'dirección': 0.0, 'plocio': 0.0, 'gripo;': 0.0, 'mostrando': 0.0, 'agudo': 0.0, 'ingenio,': 0.0, 'dieciséis': 0.0, 'le': 0.0, 'enviaron': 0.0, 'atenas,': 0.0, 'estudió': 0.0, 'ciencias,': 0.0, 'perfeccionó': 0.0, 'lengua': 0.0, 'griega.': 0.0, 'escuelas': 0.0, 'atenienses': 0.0, 'eran': 0.0, 'entonces': 0.0, 'frecuentadas': 0.0, 'juventud': 0.0, 'romana,': 0.0, 'autor': 0.0, 'latino': 0.0, 'formase': 0.0, 'ellas.': 0.0, 'quiso': 0.0, 'padre': 0.0, 'obligarle': 0.0, 'seguir': 0.0, 'carrera': 0.0, 'foro,': 0.0, 'efecto': 0.0, 'obedecerle': 0.0, 'siguió': 0.0, 'algún': 0.0, 'tiempo,': 0.0, 'hasta': 0.0, 'padre,': 0.0, 'abandonó': 0.0, 'deliciosas': 0.0, 'musas,': 0.0, 'llamaba': 0.0, 'innata': 0.0, 'inclinación.': 0.0, 'tuvo': 0.0, 'maestros': 0.0, 'filosofía': 0.0, 'porcio': 0.0, 'latrón,': 0.0, 'retórica': 0.0, 'marcelo': 0.0, 'fusco,': 0.0, 'gramática': 0.0, 'julio': 0.0, 'grecino,': 0.0, 'profesores': 0.0, 'llevaban': 0.0, 'aplauso': 0.0, 'roma.': 0.0, 'bueno': 0.0, 'e': 0.0, 'ingenioso': 0.0, 'orador,': 0.0, 'afluente': 0.0, 'patético': 0.0, 'poeta,': 0.0, 'engrandecía': 0.0, 'animaba': 0.0, 'cuantos': 0.0, 'asuntos': 0.0, 'encomendaba': 0.0, 'pluma;': 0.0, 'demasiadas': 0.0, 'flores': 0.0, 'exornó': 0.0, 'versos,': 0.0, 'prodigadas': 0.0, 'facilidad': 0.0, 'ardiente': 0.0, 'fecunda': 0.0, 'imaginación,': 0.0, 'apartaron': 0.0, 'noble': 0.0, 'sencilla': 0.0, 'majestad': 0.0, 'arte.': 0.0, 'dicen': 0.0, 'tenía': 0.0, 'amor': 0.0, 'propio,': 0.0, 'solo': 0.0, 'desconocía,': 0.0, 'sino': 0.0, 'amaba': 0.0, 'defectos,': 0.0, 'negándose': 0.0, 'corregirlos,': 0.0, 'aun': 0.0, 'cuando': 0.0, 'amigos': 0.0, 'advirtiesen.': 0.0, '¡debilidad': 0.0, 'humana,': 0.0, 'eximen': 0.0, 'mayores': 0.0, 'hombres!': 0.0, 'gozó': 0.0, 'roma': 0.0, 'honores': 0.0, 'beneficios': 0.0, 'augusto': 0.0, 'acostumbraba': 0.0, 'remunerar': 0.0, 'grandes': 0.0, 'talentos,': 0.0, 'hubiera': 0.0, 'acaso': 0.0, 'llegado': 0.0, 'mayor': 0.0, 'fortuna': 0.0, 'poetas': 0.0, 'contemporáneos;': 0.0, 'desgracia,': 0.0, 'al': 0.0, 'hombre': 0.0, 'dado': 0.0, 'pocas': 0.0, 'veces': 0.0, 'evitar,': 0.0, 'proporcionó': 0.0, 'amores': 0.0, 'julia,': 0.0, 'hija': 0.0, 'tiberio,': 0.0, 'quien': 0.0, 'escribió': 0.0, 'epístolas': 0.0, 'amatorias,': 0.0, 'cuales': 0.0, 'miró': 0.0, 'delito': 0.0, 'lesa': 0.0, 'majestad,': 0.0, 'mandó': 0.0, 'quemar,': 0.0, 'desterrando': 0.0, 'villa': 0.0, 'tomos': 0.0, 'ponto': 0.0, 'euxino.': 0.0, 'allí': 0.0, 'murió': 0.0, 'edad': 0.0, 'cerca': 0.0, 'sesenta': 0.0, 'años,': 0.0, 'haber': 0.0, 'podido': 0.0, 'alcanzar': 0.0, 'regreso': 0.0, 'seno': 0.0, 'familia,': 0.0, 'amada': 0.0, 'patria.': 0.0, 'copiosas': 0.0, 'producciones': 0.0, 'merecen': 0.0, 'lugar': 0.0, 'poesías': 0.0, 'galantes,': 0.0, 'imitó': 0.0, 'griegos,': 0.0, 'aficionadísimos': 0.0, 'composiciones': 0.0, 'licenciosas,': 0.0, 'puede': 0.0, 'ver': 0.0, 'safo,': 0.0, 'anacreonte': 0.0, 'varios.': 0.0, 'apareció': 0.0, '_arte': 0.0, 'amar_,': 0.0, 'debió': 0.0, 'causar': 0.0, 'mucho': 0.0, 'ruido': 0.0, 'aquella': 0.0, 'capital': 0.0, 'orbe': 0.0, 'conocido,': 0.0, 'porque': 0.0, 'aunque': 0.0, 'corrupción': 0.0, 'costumbres,': 0.0, 'riquezas': 0.0, 'lujo,': 0.0, 'había': 0.0, 'colmo,': 0.0, 'duraban': 0.0, 'todavía': 0.0, 'ciertos': 0.0, 'usos': 0.0, 'leyes,': 0.0, 'sombra': 0.0, 'antigua': 0.0, 'austeridad': 0.0, 'republicana,': 0.0, 'apariencia': 0.0, 'condenaban': 0.0, 'toda': 0.0, 'relajación': 0.0, 'desorden;': 0.0, 'sería': 0.0, 'ciertamente': 0.0, 'cosa': 0.0, 'extraña': 0.0, 'preceptivo,': 0.0, 'enseñaba': 0.0, 'práctica': 0.0, 'misma': 0.0, 'corrupción,': 0.0, 'si': 0.0, 'capaz': 0.0, 'introducirla,': 0.0, 'lo': 0.0, 'menos': 0.0, 'suponía': 0.0, 'hacía': 0.0, 'pública': 0.0, 'interiormente': 0.0, 'contagiaba': 0.0, 'indicio': 0.0, 'decadencia.': 0.0, 'cierto': 0.0, 'halló': 0.0, 'tan': 0.0, 'eficaz,': 0.0, 'cometer': 0.0, 'adulterios_:': 0.0, 'juicio': 0.0, 'que,': 0.0, 'según': 0.0, 'unos,': 0.0, 'verdadera': 0.0, 'causa': 0.0, 'destierro': 0.0, 'autor,': 0.0, 'otros,': 0.0, 'pretexto': 0.0, 'para': 0.0, 'castigarle': 0.0, 'agravios': 0.0, 'privados.': 0.0, 'sea': 0.0, 'esto': 0.0, 'fuere,': 0.0, 've': 0.0, 'castigado': 0.0, 'culpas': 0.0, 'amorosas,': 0.0, 'seguramente': 0.0, 'arrastraba': 0.0, 'natural': 0.0, 'propensión.': 0.0, 'español': 0.0, 'impropiedad': 0.0, 'podríamos': 0.0, 'llamar': 0.0, 'enamorar_,': 0.0, 'cortejar_,': 0.0, 'está': 0.0, 'dividido': 0.0, 'libros.': 0.0, 'primero': 0.0, 'enseñan': 0.0, 'dos': 0.0, 'cosas:': 0.0, 'habían': 0.0, 'buscar': 0.0, 'mujeres': 0.0, 'quisiesen': 0.0, 'amar,': 0.0, 'modo': 0.0, 'propiciar': 0.0, 'poseer': 0.0, 'corazón.': 0.0, 'segundo': 0.0, 'dan': 0.0, 'preceptos': 0.0, 'duradero.': 0.0, 'tercero,': 0.0, 'hablando': 0.0, 'mujeres,': 0.0, 'les': 0.0, 'dicta': 0.0, 'reglas': 0.0, 'amar': 0.0, 'competir': 0.0, 'hombres.': 0.0, 'plan,': 0.0, 'forma': 0.0, 'pasión': 0.0, 'amorosa': 0.0, 'una': 0.0, 'guerra': 0.0, 'hombres': 0.0, 'mujeres:': 0.0, 'verdad': 0.0, 'muy': 0.0, 'propia': 0.0, 'sublime,': 0.0, 'tomada': 0.0, 'ingeniosamente': 0.0, 'naturaleza': 0.0, 'preocupaciones': 0.0, 'sexos.': 0.0, 'tiene': 0.0, 'todas': 0.0, 'cualidades': 0.0, 'didascálico:': 0.0, 'brillan': 0.0, 'principios,': 0.0, 'invención': 0.0, 'orden': 0.0, 'cuanto': 0.0, 'arte;': 0.0, 'locución,': 0.0, 'belleza,': 0.0, 'elegancia,': 0.0, 'armonía,': 0.0, 'laconismo': 0.0, 'pureza': 0.0, 'latina.': 0.0, 'episodios,': 0.0, 'parte': 0.0, 'accesoria,': 0.0, 'mérito,': 0.0, 'enlace,': 0.0, 'delicadeza': 0.0, 'hermosura,': 0.0, 'mi': 0.0, 'concepto': 0.0, 'exceden': 0.0, 'cuerpo': 0.0, 'obra.': 0.0, '¡ah,': 0.0, 'me': 0.0, 'hubiese': 0.0, 'conservar': 0.0, 'traducción': 0.0, 'belleza': 0.0, 'confusión': 0.0, 'presuntuosos': 0.0, 'modernos,': 0.0, 'creen': 0.0, 'igualar': 0.0, 'padres': 0.0, 'buen': 0.0, 'desdeñando': 0.0, 'estudio': 0.0, 'lengua!': 0.0, '¿y': 0.0, 'quién': 0.0, 'podrá': 0.0, 'alabar': 0.0, 'dignamente': 0.0, 'trata': 0.0, 'amor,': 0.0, 'conveniente': 0.0, 'poesía,': 0.0, 'modernos': 0.0, 'nos': 0.0, 'escasos': 0.0, 'ejemplos,': 0.0, 'antiguos': 0.0, 'poseían': 0.0, 'sabían': 0.0, 'emplear': 0.0, 'magisterio?': 0.0, 'usa': 0.0, 'esta': 0.0, 'composición': 0.0, 'versos': 0.0, 'elegíacos,': 0.0, 'carácter': 0.0, 'sencillos,': 0.0, 'tiernos': 0.0, 'sentenciosos.': 0.0, 'procurado': 0.0, 'ceñirme': 0.0, 'original:': 0.0, 'vestir': 0.0, 'latín': 0.0, 'castellano,': 0.0, 'latín:': 0.0, 'prosa': 0.0, 'sabor': 0.0, 'poético,': 0.0, 'tono': 0.0, 'elevado': 0.0, 'metafórico': 0.0, 'empresa': 0.0, 'harto': 0.0, 'inaccesible': 0.0, 'débiles': 0.0, 'fuerzas.': 0.0, 'verá': 0.0, 'gracia': 0.0, 'poética': 0.0, 'original,': 0.0, 'consiste': 0.0, 'sonoridad': 0.0, 'métrica,': 0.0, 'transposiciones,': 0.0, 'conjunciones,': 0.0, 'voces': 0.0, 'equivalente,': 0.0, 'transiciones,': 0.0, 'alusiones': 0.0, 'peculiares': 0.0, 'tiempos': 0.0, 'fin,': 0.0, 'alguna': 0.0, 'aquellas': 0.0, 'ni': 0.0, 'pueden': 0.0, 'conservar,': 0.0, 'tendrían': 0.0, 'mérito': 0.0, 'lenguas': 0.0, 'vivas;': 0.0, 'conservadas,': 0.0, 'serían': 0.0, 'opinión': 0.0, 'juiciosos': 0.0, 'ripio': 0.0, 'pedantería.': 0.0, 'diferencia': 0.0, 'regla': 0.0, 'fundamental,': 0.0, 'eso': 0.0, 'duda': 0.0, 'viciosas': 0.0, 'traducciones': 0.0, 'servilmente': 0.0, 'literales,': 0.0, 'excesivamente': 0.0, 'libres.': 0.0, 'otra': 0.0, 'debe': 0.0, 'ostentar': 0.0, 'sostener': 0.0, 'estilo': 0.0, 'poético;': 0.0, 'contrario,': 0.0, 'perteneciendo': 0.0, 'género': 0.0, 'didascálico,': 0.0, 'forzado': 0.0, 'imitar': 0.0, 'naturalidad': 0.0, 'prosaica': 0.0, 'hacer': 0.0, 'claros': 0.0, 'preceptos,': 0.0, 'reservando': 0.0, 'episodios': 0.0, 'pompa,': 0.0, 'sublimidad': 0.0, 'riqueza.': 0.0, 'pues': 0.0, 'véase': 0.0, 'episódica': 0.0, 'resalta': 0.0, 'traducción;': 0.0, 'hallarán': 0.0, 'poesía': 0.0, 'altisonante,': 0.0, 'invención,': 0.0, 'variedad,': 0.0, 'propiedad': 0.0, 'fluidez.': 0.0, 'estoy': 0.0, 'persuadido': 0.0, 'presente': 0.0, 'excede': 0.0, 'extranjeras': 0.0, 'visto,': 0.0, 'única': 0.0, 'castellana': 0.0, 'verso': 0.0, 'imprimió,': 0.0, 'hecho': 0.0, 'rara,': 0.0, 'raros': 0.0, 'saben': 0.0, 'hay;': 0.0, 'ninguna': 0.0, 'conviene': 0.0, 'debe.': 0.0, 'redundancia,': 0.0, 'inexactitud,': 0.0, 'mal': 0.0, 'lenguaje': 0.0, 'arbitrariedad': 0.0, 'principales': 0.0, 'defectos:': 0.0, 'palabra,': 0.0, 'traducir': 0.0, 'hallan': 0.0, 'quebrantadas': 0.0, 'ellas': 0.0, 'abiertamente.': 0.0, 'basta:': 0.0, 'ánimo': 0.0, 'criticar,': 0.0, 'presentar': 0.0, 'público': 0.0, 'adelantar': 0.0, 'sobre': 0.0, 'precedieron.': 0.0, 'llamado': 0.0, 'amatorio_,': 0.0, 'verdadero': 0.0, 'título,': 0.0, 'manuscritos': 0.0, 'existen': 0.0, 'poema,': 0.0, 'autoridad': 0.0, 'varios': 0.0, 'escritores': 0.0, 'hablaron': 0.0, 'él,': 0.0, 'citan.': 0.0, 'aún': 0.0, 'tenemos': 0.0, 'ejemplar': 0.0, 'correcto': 0.0, 'ovidio:': 0.0, 'todos': 0.0, 'códices': 0.0, 'estan': 0.0, 'llenos': 0.0, 'variantes,': 0.0, 'ponen': 0.0, 'perplejidad': 0.0, 'peritos': 0.0, 'latina,': 0.0, 'trabajaron': 0.0, 'purificar': 0.0, 'conciliarlo,': 0.0, 'estudiando': 0.0, 'confrontando': 0.0, 'unos': 0.0, 'pasajes': 0.0, 'análogos,': 0.0, 'algunos': 0.0, 'coinciden': 0.0, 'mismos': 0.0, 'pensamientos.': 0.0, 'razón': 0.0, 'vi': 0.0, 'casi': 0.0, 'precisado': 0.0, 'muchas': 0.0, 'adivinar': 0.0, 'sentido': 0.0, 'genuino,': 0.0, 'interpretarlo,': 0.0, 'dejarlo': 0.0, 'imperfecto,': 0.0, 'cediendo': 0.0, 'necesidad': 0.0, 'leer': 0.0, 'halla': 0.0, 'escrito,': 0.0, 'conformarme': 0.0, 'puntuación': 0.0, 'prosódica': 0.0, 'ortográfica.': 0.0, 'sigo': 0.0, 'edición': 0.0, 'leyden,': 0.0, 'pasa': 0.0, 'ilustrada': 0.0, 'correcta,': 0.0, 'confesando': 0.0, 'debido': 0.0, 'mucha': 0.0, 'luz': 0.0, 'entender': 0.0, 'guía': 0.0, 'iría': 0.0, 'ciegas,': 0.0, 'ella,': 0.0, 'prometo': 0.0, 'entero': 0.0, 'acierto.': 0.0, 'libro': 0.0, 'primero.': 0.0, 'romano': 0.0, 'ignora': 0.0, 'lea': 0.0, 'enseñado': 0.0, 'lectura,': 0.0, 'ame.': 0.0, 'ligera': 0.0, 'nao': 0.0, 'vela': 0.0, 'remos:': 0.0, 'rigen': 0.0, 'voladores': 0.0, 'carros,': 0.0, 'ser': 0.0, 'regido': 0.0, 'amor.': 0.0, 'automedonte': 0.0, 'diestro': 0.0, 'carros': 0.0, 'caballos,': 0.0, 'tifis': 0.0, 'piloto': 0.0, 'nave': 0.0, 'argonáutica;': 0.0, 'empero': 0.0, 'mí': 0.0, 'designó': 0.0, 'venus': 0.0, 'maestro': 0.0, 'tierno': 0.0, 'amor;': 0.0, 'llamará': 0.0, 'gente.': 0.0, 'fiero': 0.0, 'contrasta': 0.0, 'veces;': 0.0, 'mas': 0.0, 'niño,': 0.0, 'blanda': 0.0, 'dispuesto': 0.0, 'tornarse': 0.0, 'dócil.': 0.0, 'quirón': 0.0, 'muchacho': 0.0, 'aquiles': 0.0, 'sonidos': 0.0, 'cítara,': 0.0, 'amansando': 0.0, 'armoniosa': 0.0, 'fiereza': 0.0, 'ánimo.': 0.0, 'tantas': 0.0, 'puso': 0.0, 'grima': 0.0, 'compañeros': 0.0, 'enemigos,': 0.0, 'temía': 0.0, 'delante': 0.0, 'añoso': 0.0, 'viejo,': 0.0, 'presentaba': 0.0, 'obediente': 0.0, 'castigo': 0.0, 'ayo': 0.0, 'aterrar': 0.0, 'héctor.': 0.0, 'preceptor': 0.0, 'aquiles,': 0.0, 'uno': 0.0, 'otro': 0.0, 'duros,': 0.0, 'prole': 0.0, 'diosa;': 0.0, 'toro': 0.0, 'sujeta': 0.0, 'cerviz': 0.0, 'peso': 0.0, 'arado,': 0.0, 'briosos': 0.0, 'alazanes': 0.0, 'tascan': 0.0, 'freno.': 0.0, 'cederá': 0.0, 'voluntad;': 0.0, 'vibre': 0.0, 'contra': 0.0, 'flechas,': 0.0, 'abrase': 0.0, 'pecho': 0.0, 'teas.': 0.0, 'cruelmente': 0.0, 'hirió,': 0.0, 'violencia': 0.0, 'atormentó,': 0.0, 'mejor': 0.0, 'vengaré': 0.0, 'heridas.': 0.0, 'mentiré,': 0.0, '¡oh': 0.0, 'apolo!,': 0.0, 'diciendo': 0.0, 'tú': 0.0, 'inspiraste': 0.0, 'arte,': 0.0, 'sé': 0.0, 'canto': 0.0, 'volantes': 0.0, 'aves;': 0.0, 'aparecieron': 0.0, 'clío': 0.0, 'hermanas,': 0.0, 'guardaba': 0.0, 'rebaños': 0.0, 'valles': 0.0, 'ascra.': 0.0, 'obra:': 0.0, 'creed': 0.0, 'experto': 0.0, 'poeta.': 0.0, 'cantaré': 0.0, 'verdaderos:': 0.0, 'favorece': 0.0, 'designios,': 0.0, 'madre': 0.0, 'enseñarán': 0.0, 'alguno,': 0.0, 'sí': 0.0, 'hurtos': 0.0, 'permitidos.': 0.0, 'huid': 0.0, 'embargo,': 0.0, 'vírgenes': 0.0, 'delicadas,': 0.0, 'dechado': 0.0, 'pudor,': 0.0, 'ocultáis': 0.0, 'pies': 0.0, 'talares': 0.0, 'vestiduras[1].': 0.0, '[1]': 0.0, 'matronas.': 0.0, 'ahora': 0.0, 'os': 0.0, 'alistáis': 0.0, 'primera': 0.0, 'nuevas': 0.0, 'banderas,': 0.0, 'trabajad': 0.0, 'hallar': 0.0, 'ante': 0.0, 'cosas': 0.0, 'objeto': 0.0, 'queráis': 0.0, 'amar:': 0.0, 'luego': 0.0, 'conquistar': 0.0, 'corazón': 0.0, 'agrade;': 0.0, 'últimamente,': 0.0, 'larga': 0.0, 'duración.': 0.0, 'método:': 0.0, 'campo': 0.0, 'recorrerá': 0.0, 'carro,': 0.0, 'límite': 0.0, 'rozarán': 0.0, 'ruedas.': 0.0, 'mientras': 0.0, 'podéis,': 0.0, 'ligaduras': 0.0, 'andáis': 0.0, 'partes,': 0.0, 'escoged': 0.0, 'muchacha': 0.0, 'diréis:': 0.0, 'eres': 0.0, 'agrada.': 0.0, 'descenderá': 0.0, 'vosotros': 0.0, 'diáfanas': 0.0, 'regiones,': 0.0, 'buscareisla': 0.0, 'adrede': 0.0, 'vuestros': 0.0, 'ojos.': 0.0, 'cazador': 0.0, 'sabe': 0.0, 'tender': 0.0, 'lazos': 0.0, 'ciervos:': 0.0, 'valle': 0.0, 'madriguera': 0.0, 'rugiente': 0.0, 'jabalí:': 0.0, 'pajarero': 0.0, 'sonle': 0.0, 'conocidos': 0.0, 'árboles': 0.0, 'posan': 0.0, 'pájaros,': 0.0, 'echa': 0.0, 'redes': 0.0, 'conoce': 0.0, 'cuáles': 0.0, 'aguas': 0.0, 'abundan': 0.0, 'peces.': 0.0, 'buscan': 0.0, 'permanente': 0.0, 'aprendan': 0.0, 'desde': 0.0, 'parajes': 0.0, 'frecuentan': 0.0, 'mujeres.': 0.0, 'será': 0.0, 'emprender': 0.0, 'dilatados': 0.0, 'viajes,': 0.0, 'atravesar': 0.0, 'mares': 0.0, 'procelosos;': 0.0, 'perseo': 0.0, 'haya': 0.0, 'traído': 0.0, 'andrómeda': 0.0, 'indios': 0.0, 'atezados,': 0.0, 'troyano': 0.0, 'paris': 0.0, 'venido': 0.0, 'robar': 0.0, 'griega': 0.0, 'elena.': 0.0, 'ofrecerá': 0.0, 'tales': 0.0, 'lindas': 0.0, 'mozas': 0.0, 'pueblan,': 0.0, 'decimos,': 0.0, 'mundo.': 0.0, 'fértil': 0.0, 'granos': 0.0, 'campiña': 0.0, 'gárgaro,': 0.0, 'uvas': 0.0, 'metimna,': 0.0, 'surcan': 0.0, 'mar': 0.0, 'peces,': 0.0, 'oculta': 0.0, 'aves': 0.0, 'frondosidad': 0.0, 'árboles,': 0.0, 'esmaltan': 0.0, 'cielo': 0.0, 'estrellas': 0.0, 'muchachas': 0.0, 'reside': 0.0, 'hijo': 0.0, 'eneas.': 0.0, 'inclinan': 0.0, 'están': 0.0, 'primeros': 0.0, 'imperfectos': 0.0, 'verdaderamente': 0.0, 'niñas.': 0.0, 'gustan': 0.0, 'jóvenes,': 0.0, 'faltarán': 0.0, 'placenteras': 0.0, 'pondrán': 0.0, 'deseo.': 0.0, 'casualidad': 0.0, 'sean': 0.0, 'llevados': 0.0, 'adulta': 0.0, 'cuerda,': 0.0, 'créanme': 0.0, 'turba': 0.0, 'copiosísima.': 0.0, 'paseaos': 0.0, 'vagarosos': 0.0, 'ardientes': 0.0, 'días': 0.0, 'estío': 0.0, 'pórtico': 0.0, 'pompeyo': 0.0, 'munificencia': 0.0, 'añadió': 0.0, 'madre,': 0.0, 'suntuoso': 0.0, 'edificio': 0.0, 'peregrinos': 0.0, 'mármoles.': 0.0, 'id': 0.0, 'adornado': 0.0, 'cuadros': 0.0, 'antigüedad,': 0.0, 'nombre': 0.0, 'fundadora': 0.0, 'livia:': 0.0, 'pintadas': 0.0, 'danaides,': 0.0, 'osaron': 0.0, 'fraguar': 0.0, 'muerte': 0.0, 'míseros': 0.0, 'primos,': 0.0, 'desposados': 0.0, 'ellas,': 0.0, 'cruel': 0.0, 'espada': 0.0, 'desnuda.': 0.0, 'tampoco': 0.0, 'evitéis': 0.0, 'templo': 0.0, 'adonis': 0.0, 'llorado': 0.0, 'venus:': 0.0, 'sacrificios': 0.0, 'celebrados': 0.0, 'séptimo': 0.0, 'judaico': 0.0, 'siro:': 0.0, 'olvidéis': 0.0, 'menfítica': 0.0, 'isis': 0.0, 'vestimenta': 0.0, 'lino,': 0.0, 'hizo': 0.0, 'ella': 0.0, 'júpiter[2].': 0.0, '[2]': 0.0, 'ío': 0.0, 'torpes': 0.0, 'júpiter:': 0.0, 'juno': 0.0, 'perseguía': 0.0, 'celos,': 0.0, 'librarla': 0.0, 'indignación,': 0.0, 'convirtió': 0.0, 'júpiter': 0.0, 'vaca,': 0.0, 'figura': 0.0, 'huyó': 0.0, 'egipto.': 0.0, '¿quién': 0.0, 'creería?,': 0.0, 'propósito': 0.0, 'casos': 0.0, 'amorosos:': 0.0, 'sutil': 0.0, 'foro': 0.0, 'llama': 0.0, 'fuente': 0.0, 'apia,': 0.0, 'dominada': 0.0, 'adyacente': 0.0, 'construido': 0.0, 'mármol,': 0.0, 'hiende': 0.0, 'aire': 0.0, 'saltantes': 0.0, 'aguas.': 0.0, 'frecuencia': 0.0, 'causídico': 0.0, 'deja': 0.0, 'coger': 0.0, 'defiende': 0.0, 'mismo.': 0.0, 'faltan': 0.0, 'palabras': 0.0, 'elocuente,': 0.0, 'nuevos': 0.0, 'negocios': 0.0, 'ocupan,': 0.0, 'causa.': 0.0, 'poco': 0.0, 'patrono,': 0.0, 'desea': 0.0, 'cliente.': 0.0, 'ríe': 0.0, 'cercano.': 0.0, 'cazad': 0.0, 'principalmente': 0.0, 'públicos': 0.0, 'teatros,': 0.0, 'sitios': 0.0, 'favorables': 0.0, 'designios.': 0.0, 'hallaréis': 0.0, 'entretenimiento:': 0.0, 'disfrutar': 0.0, 'vez,': 0.0, 'escojáis': 0.0, 'poseerlas.': 0.0, 'manera': 0.0, 'hormigas': 0.0, 'numeroso': 0.0, 'escuadrón': 0.0, 'van': 0.0, 'vuelven': 0.0, 'cesar,': 0.0, 'cargadas': 0.0, 'sustento,': 0.0, 'abejas': 0.0, 'revuelan': 0.0, 'amenos': 0.0, 'olorosos': 0.0, 'sotos,': 0.0, 'buscando': 0.0, 'tomillo': 0.0, 'flores,': 0.0, 'concurren': 0.0, 'ataviadísimas': 0.0, 'juegos': 0.0, 'solemnes.': 0.0, 'afluencia': 0.0, 'embarazo': 0.0, 'elección.': 0.0, 'vienen': 0.0, 'ver,': 0.0, 'vistas.': 0.0, 'peligroso': 0.0, 'casto': 0.0, 'pudor.': 0.0, 'tú,': 0.0, 'rómulo!,': 0.0, 'instituiste': 0.0, 'espectáculos': 0.0, 'perturbados': 0.0, 'robada': 0.0, 'sabina': 0.0, 'deleitó': 0.0, 'tus': 0.0, 'vacantes': 0.0, 'ciudadanos.': 0.0, 'teatros': 0.0, 'estaban': 0.0, 'decorados': 0.0, 'mármoles': 0.0, 'colgaduras,': 0.0, 'competían': 0.0, 'escena': 0.0, 'vistosos': 0.0, 'colores.': 0.0, 'artificio,': 0.0, 'adornaba': 0.0, 'simplemente': 0.0, 'enramadas': 0.0, 'verde': 0.0, 'hojarasca': 0.0, 'producía': 0.0, 'nemoroso': 0.0, 'palatino.': 0.0, 'pueblo': 0.0, 'sentaba': 0.0, 'gradas': 0.0, 'hechas': 0.0, 'césped,': 0.0, 'llevando': 0.0, 'coronadas': 0.0, 'hojas': 0.0, 'verdes': 0.0, 'desgreñadas': 0.0, 'cabelleras.': 0.0, 'miraban': 0.0, 'romanos': 0.0, 'sabinas,': 0.0, 'reparando': 0.0, 'cada': 0.0, 'gusto,': 0.0, 'revolviendo': 0.0, 'deseos.': 0.0, 'flautista': 0.0, 'etrusco

In [7]:
# Representacion en tabla
df_idf = pd.DataFrame(list(idf_documento.items()), columns=['Palabra', 'IDF'])
df_idf

            Palabra  IDF
0              nota  0.0
1                de  0.0
2     transcripción  0.0
3                 *  0.0
4               las  0.0
...             ...  ...
8165        cisnes.  0.0
8166     discípulas  0.0
8167           mías  0.0
8168       escriban  0.0
8169         _fin._  0.0

[8170 rows x 2 columns]

Como se hace el ejercicio en un solo documento $(N/df_t)=1$ y $log(1)=0$. Lo que se interpreta como terminos demasiados comunes (la diferencia se ve con mas documentos)

#### **Matriz TF - IDF**

In [8]:
tfidf_documento = {}

#Podemos iterar sobre tf_documento porque tiene exactamente las mismas palabras que idf_documento
for palabra in tf_documento:
    
    # Extraer los valores numericos de ambos diccionarios para esa palabra en especifico
    tf = tf_documento[palabra]
    idf = idf_documento[palabra]
    
    # calculo TF-IDF
    w = tf * idf
    
    # Guardar en el nuevo diccionario
    tfidf_documento[palabra] = w

print(tfidf_documento)

{'nota': 0.0, 'de': 0.0, 'transcripción': 0.0, '*': 0.0, 'las': 0.0, 'cursivas': 0.0, 'se': 0.0, 'muestran': 0.0, 'entre': 0.0, '_subrayados_.': 0.0, 'los': 0.0, 'errores': 0.0, 'imprenta': 0.0, 'han': 0.0, 'sido': 0.0, 'corregidos.': 0.0, 'la': 0.0, 'ortografía': 0.0, 'del': 0.0, 'texto': 0.0, 'original': 0.0, 'ha': 0.0, 'modernizada': 0.0, 'acuerdo': 0.0, 'con': 0.0, 'normas': 0.0, 'publicadas': 0.0, 'en': 0.0, '2010': 0.0, 'por': 0.0, 'real': 0.0, 'academia': 0.0, 'española.': 0.0, 'también': 0.0, 'nombres': 0.0, 'propios,': 0.0, 'tanto': 0.0, 'lugares': 0.0, 'como': 0.0, 'personajes.': 0.0, 'notas': 0.0, 'a': 0.0, 'pie': 0.0, 'página': 0.0, 'renemeradas': 0.0, 'y': 0.0, 'colocadas': 0.0, 'tras': 0.0, 'el': 0.0, 'párrafo': 0.0, 'que': 0.0, 'contiene': 0.0, 'su': 0.0, 'llamada.': 0.0, 'páginas': 0.0, 'blanco': 0.0, 'eliminadas.': 0.0, 'arte': 0.0, 'amar.': 0.0, 'traductor': 0.0, 'ovidio': 0.0, 'sus': 0.0, 'obras': 0.0, 'escrito': 0.0, 'otras': 0.0, 'plumas': 0.0, 'más': 0.0, 'bien': 0.0, 'cortadas': 0.0, 'mía;': 0.0, 'así': 0.0, 'fuera': 0.0, 'temeridad': 0.0, 'querer': 0.0, 'añadir,': 0.0, 'o': 0.0, 'superfluidad': 0.0, 'copiar': 0.0, 'eruditos': 0.0, 'emprendieron': 0.0, 'aquel': 0.0, 'trabajo.': 0.0, 'demás': 0.0, 'comentarios': 0.0, 'rapsodias': 0.0, 'no': 0.0, 'son': 0.0, 'ya': 0.0, 'gusto': 0.0, 'nuestro': 0.0, 'siglo;': 0.0, 'cual,': 0.0, 'todos,': 0.0, 'aspira': 0.0, 'instruirse': 0.0, 'solidez': 0.0, 'es': 0.0, 'necesario': 0.0, 'recurra': 0.0, 'fuentes,': 0.0, 'sin': 0.0, 'contentarse': 0.0, 'vagas': 0.0, 'repeticiones,': 0.0, 'noticias': 0.0, 'tal': 0.0, 'vez': 0.0, 'corrompidas.': 0.0, 'pero': 0.0, 'yo': 0.0, 'traduzco': 0.0, 'un': 0.0, 'poema': 0.0, 'ovidio,': 0.0, 'andar': 0.0, 'manos': 0.0, 'mis': 0.0, 'lectores': 0.0, 'habrá': 0.0, 'muchos': 0.0, 'oído': 0.0, 'siquiera': 0.0, 'nombre;': 0.0, 'otros': 0.0, 'apenas': 0.0, 'tienen': 0.0, 'idea': 0.0, 'superficial': 0.0, 'él': 0.0, 'poesías.': 0.0, 'he': 0.0, 'aquí': 0.0, 'qué': 0.0, 'puedo': 0.0, 'pasar': 0.0, 'todo': 0.0, 'silencio': 0.0, 'algunas': 0.0, 'circunstancias': 0.0, 'este': 0.0, 'meritísimo': 0.0, 'autor.': 0.0, 'p.': 0.0, 'nasón,': 0.0, 'caballero': 0.0, 'romano,': 0.0, 'nació': 0.0, 'sulmona,': 0.0, 'ciudad': 0.0, 'abruzo,': 0.0, 'cuarenta': 0.0, 'tres': 0.0, 'años': 0.0, 'antes': 0.0, 'era': 0.0, 'vulgar,': 0.0, 'mismo': 0.0, 'día': 0.0, 'fue': 0.0, 'muerto': 0.0, 'elocuente': 0.0, 'cicerón.': 0.0, 'roma,': 0.0, 'donde': 0.0, 'llevado': 0.0, 'corta': 0.0, 'edad,': 0.0, 'dio': 0.0, 'letras': 0.0, 'bajo': 0.0, 'dirección': 0.0, 'plocio': 0.0, 'gripo;': 0.0, 'mostrando': 0.0, 'agudo': 0.0, 'ingenio,': 0.0, 'dieciséis': 0.0, 'le': 0.0, 'enviaron': 0.0, 'atenas,': 0.0, 'estudió': 0.0, 'ciencias,': 0.0, 'perfeccionó': 0.0, 'lengua': 0.0, 'griega.': 0.0, 'escuelas': 0.0, 'atenienses': 0.0, 'eran': 0.0, 'entonces': 0.0, 'frecuentadas': 0.0, 'juventud': 0.0, 'romana,': 0.0, 'autor': 0.0, 'latino': 0.0, 'formase': 0.0, 'ellas.': 0.0, 'quiso': 0.0, 'padre': 0.0, 'obligarle': 0.0, 'seguir': 0.0, 'carrera': 0.0, 'foro,': 0.0, 'efecto': 0.0, 'obedecerle': 0.0, 'siguió': 0.0, 'algún': 0.0, 'tiempo,': 0.0, 'hasta': 0.0, 'padre,': 0.0, 'abandonó': 0.0, 'deliciosas': 0.0, 'musas,': 0.0, 'llamaba': 0.0, 'innata': 0.0, 'inclinación.': 0.0, 'tuvo': 0.0, 'maestros': 0.0, 'filosofía': 0.0, 'porcio': 0.0, 'latrón,': 0.0, 'retórica': 0.0, 'marcelo': 0.0, 'fusco,': 0.0, 'gramática': 0.0, 'julio': 0.0, 'grecino,': 0.0, 'profesores': 0.0, 'llevaban': 0.0, 'aplauso': 0.0, 'roma.': 0.0, 'bueno': 0.0, 'e': 0.0, 'ingenioso': 0.0, 'orador,': 0.0, 'afluente': 0.0, 'patético': 0.0, 'poeta,': 0.0, 'engrandecía': 0.0, 'animaba': 0.0, 'cuantos': 0.0, 'asuntos': 0.0, 'encomendaba': 0.0, 'pluma;': 0.0, 'demasiadas': 0.0, 'flores': 0.0, 'exornó': 0.0, 'versos,': 0.0, 'prodigadas': 0.0, 'facilidad': 0.0, 'ardiente': 0.0, 'fecunda': 0.0, 'imaginación,': 0.0, 'apartaron': 0.0, 'noble': 0.0, 'sencilla': 0.0, 'majestad': 0.0, 'arte.': 0.0, 'dicen': 0.0, 'tenía': 0.0, 'amor': 0.0, 'propio,': 0.0, 'solo': 0.0, 'desconocía,': 0.0, 'sino': 0.0, 'amaba': 0.0, 'defectos,': 0.0, 'negándose': 0.0, 'corregirlos,': 0.0, 'aun': 0.0, 'cuando': 0.0, 'amigos': 0.0, 'advirtiesen.': 0.0, '¡debilidad': 0.0, 'humana,': 0.0, 'eximen': 0.0, 'mayores': 0.0, 'hombres!': 0.0, 'gozó': 0.0, 'roma': 0.0, 'honores': 0.0, 'beneficios': 0.0, 'augusto': 0.0, 'acostumbraba': 0.0, 'remunerar': 0.0, 'grandes': 0.0, 'talentos,': 0.0, 'hubiera': 0.0, 'acaso': 0.0, 'llegado': 0.0, 'mayor': 0.0, 'fortuna': 0.0, 'poetas': 0.0, 'contemporáneos;': 0.0, 'desgracia,': 0.0, 'al': 0.0, 'hombre': 0.0, 'dado': 0.0, 'pocas': 0.0, 'veces': 0.0, 'evitar,': 0.0, 'proporcionó': 0.0, 'amores': 0.0, 'julia,': 0.0, 'hija': 0.0, 'tiberio,': 0.0, 'quien': 0.0, 'escribió': 0.0, 'epístolas': 0.0, 'amatorias,': 0.0, 'cuales': 0.0, 'miró': 0.0, 'delito': 0.0, 'lesa': 0.0, 'majestad,': 0.0, 'mandó': 0.0, 'quemar,': 0.0, 'desterrando': 0.0, 'villa': 0.0, 'tomos': 0.0, 'ponto': 0.0, 'euxino.': 0.0, 'allí': 0.0, 'murió': 0.0, 'edad': 0.0, 'cerca': 0.0, 'sesenta': 0.0, 'años,': 0.0, 'haber': 0.0, 'podido': 0.0, 'alcanzar': 0.0, 'regreso': 0.0, 'seno': 0.0, 'familia,': 0.0, 'amada': 0.0, 'patria.': 0.0, 'copiosas': 0.0, 'producciones': 0.0, 'merecen': 0.0, 'lugar': 0.0, 'poesías': 0.0, 'galantes,': 0.0, 'imitó': 0.0, 'griegos,': 0.0, 'aficionadísimos': 0.0, 'composiciones': 0.0, 'licenciosas,': 0.0, 'puede': 0.0, 'ver': 0.0, 'safo,': 0.0, 'anacreonte': 0.0, 'varios.': 0.0, 'apareció': 0.0, '_arte': 0.0, 'amar_,': 0.0, 'debió': 0.0, 'causar': 0.0, 'mucho': 0.0, 'ruido': 0.0, 'aquella': 0.0, 'capital': 0.0, 'orbe': 0.0, 'conocido,': 0.0, 'porque': 0.0, 'aunque': 0.0, 'corrupción': 0.0, 'costumbres,': 0.0, 'riquezas': 0.0, 'lujo,': 0.0, 'había': 0.0, 'colmo,': 0.0, 'duraban': 0.0, 'todavía': 0.0, 'ciertos': 0.0, 'usos': 0.0, 'leyes,': 0.0, 'sombra': 0.0, 'antigua': 0.0, 'austeridad': 0.0, 'republicana,': 0.0, 'apariencia': 0.0, 'condenaban': 0.0, 'toda': 0.0, 'relajación': 0.0, 'desorden;': 0.0, 'sería': 0.0, 'ciertamente': 0.0, 'cosa': 0.0, 'extraña': 0.0, 'preceptivo,': 0.0, 'enseñaba': 0.0, 'práctica': 0.0, 'misma': 0.0, 'corrupción,': 0.0, 'si': 0.0, 'capaz': 0.0, 'introducirla,': 0.0, 'lo': 0.0, 'menos': 0.0, 'suponía': 0.0, 'hacía': 0.0, 'pública': 0.0, 'interiormente': 0.0, 'contagiaba': 0.0, 'indicio': 0.0, 'decadencia.': 0.0, 'cierto': 0.0, 'halló': 0.0, 'tan': 0.0, 'eficaz,': 0.0, 'cometer': 0.0, 'adulterios_:': 0.0, 'juicio': 0.0, 'que,': 0.0, 'según': 0.0, 'unos,': 0.0, 'verdadera': 0.0, 'causa': 0.0, 'destierro': 0.0, 'autor,': 0.0, 'otros,': 0.0, 'pretexto': 0.0, 'para': 0.0, 'castigarle': 0.0, 'agravios': 0.0, 'privados.': 0.0, 'sea': 0.0, 'esto': 0.0, 'fuere,': 0.0, 've': 0.0, 'castigado': 0.0, 'culpas': 0.0, 'amorosas,': 0.0, 'seguramente': 0.0, 'arrastraba': 0.0, 'natural': 0.0, 'propensión.': 0.0, 'español': 0.0, 'impropiedad': 0.0, 'podríamos': 0.0, 'llamar': 0.0, 'enamorar_,': 0.0, 'cortejar_,': 0.0, 'está': 0.0, 'dividido': 0.0, 'libros.': 0.0, 'primero': 0.0, 'enseñan': 0.0, 'dos': 0.0, 'cosas:': 0.0, 'habían': 0.0, 'buscar': 0.0, 'mujeres': 0.0, 'quisiesen': 0.0, 'amar,': 0.0, 'modo': 0.0, 'propiciar': 0.0, 'poseer': 0.0, 'corazón.': 0.0, 'segundo': 0.0, 'dan': 0.0, 'preceptos': 0.0, 'duradero.': 0.0, 'tercero,': 0.0, 'hablando': 0.0, 'mujeres,': 0.0, 'les': 0.0, 'dicta': 0.0, 'reglas': 0.0, 'amar': 0.0, 'competir': 0.0, 'hombres.': 0.0, 'plan,': 0.0, 'forma': 0.0, 'pasión': 0.0, 'amorosa': 0.0, 'una': 0.0, 'guerra': 0.0, 'hombres': 0.0, 'mujeres:': 0.0, 'verdad': 0.0, 'muy': 0.0, 'propia': 0.0, 'sublime,': 0.0, 'tomada': 0.0, 'ingeniosamente': 0.0, 'naturaleza': 0.0, 'preocupaciones': 0.0, 'sexos.': 0.0, 'tiene': 0.0, 'todas': 0.0, 'cualidades': 0.0, 'didascálico:': 0.0, 'brillan': 0.0, 'principios,': 0.0, 'invención': 0.0, 'orden': 0.0, 'cuanto': 0.0, 'arte;': 0.0, 'locución,': 0.0, 'belleza,': 0.0, 'elegancia,': 0.0, 'armonía,': 0.0, 'laconismo': 0.0, 'pureza': 0.0, 'latina.': 0.0, 'episodios,': 0.0, 'parte': 0.0, 'accesoria,': 0.0, 'mérito,': 0.0, 'enlace,': 0.0, 'delicadeza': 0.0, 'hermosura,': 0.0, 'mi': 0.0, 'concepto': 0.0, 'exceden': 0.0, 'cuerpo': 0.0, 'obra.': 0.0, '¡ah,': 0.0, 'me': 0.0, 'hubiese': 0.0, 'conservar': 0.0, 'traducción': 0.0, 'belleza': 0.0, 'confusión': 0.0, 'presuntuosos': 0.0, 'modernos,': 0.0, 'creen': 0.0, 'igualar': 0.0, 'padres': 0.0, 'buen': 0.0, 'desdeñando': 0.0, 'estudio': 0.0, 'lengua!': 0.0, '¿y': 0.0, 'quién': 0.0, 'podrá': 0.0, 'alabar': 0.0, 'dignamente': 0.0, 'trata': 0.0, 'amor,': 0.0, 'conveniente': 0.0, 'poesía,': 0.0, 'modernos': 0.0, 'nos': 0.0, 'escasos': 0.0, 'ejemplos,': 0.0, 'antiguos': 0.0, 'poseían': 0.0, 'sabían': 0.0, 'emplear': 0.0, 'magisterio?': 0.0, 'usa': 0.0, 'esta': 0.0, 'composición': 0.0, 'versos': 0.0, 'elegíacos,': 0.0, 'carácter': 0.0, 'sencillos,': 0.0, 'tiernos': 0.0, 'sentenciosos.': 0.0, 'procurado': 0.0, 'ceñirme': 0.0, 'original:': 0.0, 'vestir': 0.0, 'latín': 0.0, 'castellano,': 0.0, 'latín:': 0.0, 'prosa': 0.0, 'sabor': 0.0, 'poético,': 0.0, 'tono': 0.0, 'elevado': 0.0, 'metafórico': 0.0, 'empresa': 0.0, 'harto': 0.0, 'inaccesible': 0.0, 'débiles': 0.0, 'fuerzas.': 0.0, 'verá': 0.0, 'gracia': 0.0, 'poética': 0.0, 'original,': 0.0, 'consiste': 0.0, 'sonoridad': 0.0, 'métrica,': 0.0, 'transposiciones,': 0.0, 'conjunciones,': 0.0, 'voces': 0.0, 'equivalente,': 0.0, 'transiciones,': 0.0, 'alusiones': 0.0, 'peculiares': 0.0, 'tiempos': 0.0, 'fin,': 0.0, 'alguna': 0.0, 'aquellas': 0.0, 'ni': 0.0, 'pueden': 0.0, 'conservar,': 0.0, 'tendrían': 0.0, 'mérito': 0.0, 'lenguas': 0.0, 'vivas;': 0.0, 'conservadas,': 0.0, 'serían': 0.0, 'opinión': 0.0, 'juiciosos': 0.0, 'ripio': 0.0, 'pedantería.': 0.0, 'diferencia': 0.0, 'regla': 0.0, 'fundamental,': 0.0, 'eso': 0.0, 'duda': 0.0, 'viciosas': 0.0, 'traducciones': 0.0, 'servilmente': 0.0, 'literales,': 0.0, 'excesivamente': 0.0, 'libres.': 0.0, 'otra': 0.0, 'debe': 0.0, 'ostentar': 0.0, 'sostener': 0.0, 'estilo': 0.0, 'poético;': 0.0, 'contrario,': 0.0, 'perteneciendo': 0.0, 'género': 0.0, 'didascálico,': 0.0, 'forzado': 0.0, 'imitar': 0.0, 'naturalidad': 0.0, 'prosaica': 0.0, 'hacer': 0.0, 'claros': 0.0, 'preceptos,': 0.0, 'reservando': 0.0, 'episodios': 0.0, 'pompa,': 0.0, 'sublimidad': 0.0, 'riqueza.': 0.0, 'pues': 0.0, 'véase': 0.0, 'episódica': 0.0, 'resalta': 0.0, 'traducción;': 0.0, 'hallarán': 0.0, 'poesía': 0.0, 'altisonante,': 0.0, 'invención,': 0.0, 'variedad,': 0.0, 'propiedad': 0.0, 'fluidez.': 0.0, 'estoy': 0.0, 'persuadido': 0.0, 'presente': 0.0, 'excede': 0.0, 'extranjeras': 0.0, 'visto,': 0.0, 'única': 0.0, 'castellana': 0.0, 'verso': 0.0, 'imprimió,': 0.0, 'hecho': 0.0, 'rara,': 0.0, 'raros': 0.0, 'saben': 0.0, 'hay;': 0.0, 'ninguna': 0.0, 'conviene': 0.0, 'debe.': 0.0, 'redundancia,': 0.0, 'inexactitud,': 0.0, 'mal': 0.0, 'lenguaje': 0.0, 'arbitrariedad': 0.0, 'principales': 0.0, 'defectos:': 0.0, 'palabra,': 0.0, 'traducir': 0.0, 'hallan': 0.0, 'quebrantadas': 0.0, 'ellas': 0.0, 'abiertamente.': 0.0, 'basta:': 0.0, 'ánimo': 0.0, 'criticar,': 0.0, 'presentar': 0.0, 'público': 0.0, 'adelantar': 0.0, 'sobre': 0.0, 'precedieron.': 0.0, 'llamado': 0.0, 'amatorio_,': 0.0, 'verdadero': 0.0, 'título,': 0.0, 'manuscritos': 0.0, 'existen': 0.0, 'poema,': 0.0, 'autoridad': 0.0, 'varios': 0.0, 'escritores': 0.0, 'hablaron': 0.0, 'él,': 0.0, 'citan.': 0.0, 'aún': 0.0, 'tenemos': 0.0, 'ejemplar': 0.0, 'correcto': 0.0, 'ovidio:': 0.0, 'todos': 0.0, 'códices': 0.0, 'estan': 0.0, 'llenos': 0.0, 'variantes,': 0.0, 'ponen': 0.0, 'perplejidad': 0.0, 'peritos': 0.0, 'latina,': 0.0, 'trabajaron': 0.0, 'purificar': 0.0, 'conciliarlo,': 0.0, 'estudiando': 0.0, 'confrontando': 0.0, 'unos': 0.0, 'pasajes': 0.0, 'análogos,': 0.0, 'algunos': 0.0, 'coinciden': 0.0, 'mismos': 0.0, 'pensamientos.': 0.0, 'razón': 0.0, 'vi': 0.0, 'casi': 0.0, 'precisado': 0.0, 'muchas': 0.0, 'adivinar': 0.0, 'sentido': 0.0, 'genuino,': 0.0, 'interpretarlo,': 0.0, 'dejarlo': 0.0, 'imperfecto,': 0.0, 'cediendo': 0.0, 'necesidad': 0.0, 'leer': 0.0, 'halla': 0.0, 'escrito,': 0.0, 'conformarme': 0.0, 'puntuación': 0.0, 'prosódica': 0.0, 'ortográfica.': 0.0, 'sigo': 0.0, 'edición': 0.0, 'leyden,': 0.0, 'pasa': 0.0, 'ilustrada': 0.0, 'correcta,': 0.0, 'confesando': 0.0, 'debido': 0.0, 'mucha': 0.0, 'luz': 0.0, 'entender': 0.0, 'guía': 0.0, 'iría': 0.0, 'ciegas,': 0.0, 'ella,': 0.0, 'prometo': 0.0, 'entero': 0.0, 'acierto.': 0.0, 'libro': 0.0, 'primero.': 0.0, 'romano': 0.0, 'ignora': 0.0, 'lea': 0.0, 'enseñado': 0.0, 'lectura,': 0.0, 'ame.': 0.0, 'ligera': 0.0, 'nao': 0.0, 'vela': 0.0, 'remos:': 0.0, 'rigen': 0.0, 'voladores': 0.0, 'carros,': 0.0, 'ser': 0.0, 'regido': 0.0, 'amor.': 0.0, 'automedonte': 0.0, 'diestro': 0.0, 'carros': 0.0, 'caballos,': 0.0, 'tifis': 0.0, 'piloto': 0.0, 'nave': 0.0, 'argonáutica;': 0.0, 'empero': 0.0, 'mí': 0.0, 'designó': 0.0, 'venus': 0.0, 'maestro': 0.0, 'tierno': 0.0, 'amor;': 0.0, 'llamará': 0.0, 'gente.': 0.0, 'fiero': 0.0, 'contrasta': 0.0, 'veces;': 0.0, 'mas': 0.0, 'niño,': 0.0, 'blanda': 0.0, 'dispuesto': 0.0, 'tornarse': 0.0, 'dócil.': 0.0, 'quirón': 0.0, 'muchacho': 0.0, 'aquiles': 0.0, 'sonidos': 0.0, 'cítara,': 0.0, 'amansando': 0.0, 'armoniosa': 0.0, 'fiereza': 0.0, 'ánimo.': 0.0, 'tantas': 0.0, 'puso': 0.0, 'grima': 0.0, 'compañeros': 0.0, 'enemigos,': 0.0, 'temía': 0.0, 'delante': 0.0, 'añoso': 0.0, 'viejo,': 0.0, 'presentaba': 0.0, 'obediente': 0.0, 'castigo': 0.0, 'ayo': 0.0, 'aterrar': 0.0, 'héctor.': 0.0, 'preceptor': 0.0, 'aquiles,': 0.0, 'uno': 0.0, 'otro': 0.0, 'duros,': 0.0, 'prole': 0.0, 'diosa;': 0.0, 'toro': 0.0, 'sujeta': 0.0, 'cerviz': 0.0, 'peso': 0.0, 'arado,': 0.0, 'briosos': 0.0, 'alazanes': 0.0, 'tascan': 0.0, 'freno.': 0.0, 'cederá': 0.0, 'voluntad;': 0.0, 'vibre': 0.0, 'contra': 0.0, 'flechas,': 0.0, 'abrase': 0.0, 'pecho': 0.0, 'teas.': 0.0, 'cruelmente': 0.0, 'hirió,': 0.0, 'violencia': 0.0, 'atormentó,': 0.0, 'mejor': 0.0, 'vengaré': 0.0, 'heridas.': 0.0, 'mentiré,': 0.0, '¡oh': 0.0, 'apolo!,': 0.0, 'diciendo': 0.0, 'tú': 0.0, 'inspiraste': 0.0, 'arte,': 0.0, 'sé': 0.0, 'canto': 0.0, 'volantes': 0.0, 'aves;': 0.0, 'aparecieron': 0.0, 'clío': 0.0, 'hermanas,': 0.0, 'guardaba': 0.0, 'rebaños': 0.0, 'valles': 0.0, 'ascra.': 0.0, 'obra:': 0.0, 'creed': 0.0, 'experto': 0.0, 'poeta.': 0.0, 'cantaré': 0.0, 'verdaderos:': 0.0, 'favorece': 0.0, 'designios,': 0.0, 'madre': 0.0, 'enseñarán': 0.0, 'alguno,': 0.0, 'sí': 0.0, 'hurtos': 0.0, 'permitidos.': 0.0, 'huid': 0.0, 'embargo,': 0.0, 'vírgenes': 0.0, 'delicadas,': 0.0, 'dechado': 0.0, 'pudor,': 0.0, 'ocultáis': 0.0, 'pies': 0.0, 'talares': 0.0, 'vestiduras[1].': 0.0, '[1]': 0.0, 'matronas.': 0.0, 'ahora': 0.0, 'os': 0.0, 'alistáis': 0.0, 'primera': 0.0, 'nuevas': 0.0, 'banderas,': 0.0, 'trabajad': 0.0, 'hallar': 0.0, 'ante': 0.0, 'cosas': 0.0, 'objeto': 0.0, 'queráis': 0.0, 'amar:': 0.0, 'luego': 0.0, 'conquistar': 0.0, 'corazón': 0.0, 'agrade;': 0.0, 'últimamente,': 0.0, 'larga': 0.0, 'duración.': 0.0, 'método:': 0.0, 'campo': 0.0, 'recorrerá': 0.0, 'carro,': 0.0, 'límite': 0.0, 'rozarán': 0.0, 'ruedas.': 0.0, 'mientras': 0.0, 'podéis,': 0.0, 'ligaduras': 0.0, 'andáis': 0.0, 'partes,': 0.0, 'escoged': 0.0, 'muchacha': 0.0, 'diréis:': 0.0, 'eres': 0.0, 'agrada.': 0.0, 'descenderá': 0.0, 'vosotros': 0.0, 'diáfanas': 0.0, 'regiones,': 0.0, 'buscareisla': 0.0, 'adrede': 0.0, 'vuestros': 0.0, 'ojos.': 0.0, 'cazador': 0.0, 'sabe': 0.0, 'tender': 0.0, 'lazos': 0.0, 'ciervos:': 0.0, 'valle': 0.0, 'madriguera': 0.0, 'rugiente': 0.0, 'jabalí:': 0.0, 'pajarero': 0.0, 'sonle': 0.0, 'conocidos': 0.0, 'árboles': 0.0, 'posan': 0.0, 'pájaros,': 0.0, 'echa': 0.0, 'redes': 0.0, 'conoce': 0.0, 'cuáles': 0.0, 'aguas': 0.0, 'abundan': 0.0, 'peces.': 0.0, 'buscan': 0.0, 'permanente': 0.0, 'aprendan': 0.0, 'desde': 0.0, 'parajes': 0.0, 'frecuentan': 0.0, 'mujeres.': 0.0, 'será': 0.0, 'emprender': 0.0, 'dilatados': 0.0, 'viajes,': 0.0, 'atravesar': 0.0, 'mares': 0.0, 'procelosos;': 0.0, 'perseo': 0.0, 'haya': 0.0, 'traído': 0.0, 'andrómeda': 0.0, 'indios': 0.0, 'atezados,': 0.0, 'troyano': 0.0, 'paris': 0.0, 'venido': 0.0, 'robar': 0.0, 'griega': 0.0, 'elena.': 0.0, 'ofrecerá': 0.0, 'tales': 0.0, 'lindas': 0.0, 'mozas': 0.0, 'pueblan,': 0.0, 'decimos,': 0.0, 'mundo.': 0.0, 'fértil': 0.0, 'granos': 0.0, 'campiña': 0.0, 'gárgaro,': 0.0, 'uvas': 0.0, 'metimna,': 0.0, 'surcan': 0.0, 'mar': 0.0, 'peces,': 0.0, 'oculta': 0.0, 'aves': 0.0, 'frondosidad': 0.0, 'árboles,': 0.0, 'esmaltan': 0.0, 'cielo': 0.0, 'estrellas': 0.0, 'muchachas': 0.0, 'reside': 0.0, 'hijo': 0.0, 'eneas.': 0.0, 'inclinan': 0.0, 'están': 0.0, 'primeros': 0.0, 'imperfectos': 0.0, 'verdaderamente': 0.0, 'niñas.': 0.0, 'gustan': 0.0, 'jóvenes,': 0.0, 'faltarán': 0.0, 'placenteras': 0.0, 'pondrán': 0.0, 'deseo.': 0.0, 'casualidad': 0.0, 'sean': 0.0, 'llevados': 0.0, 'adulta': 0.0, 'cuerda,': 0.0, 'créanme': 0.0, 'turba': 0.0, 'copiosísima.': 0.0, 'paseaos': 0.0, 'vagarosos': 0.0, 'ardientes': 0.0, 'días': 0.0, 'estío': 0.0, 'pórtico': 0.0, 'pompeyo': 0.0, 'munificencia': 0.0, 'añadió': 0.0, 'madre,': 0.0, 'suntuoso': 0.0, 'edificio': 0.0, 'peregrinos': 0.0, 'mármoles.': 0.0, 'id': 0.0, 'adornado': 0.0, 'cuadros': 0.0, 'antigüedad,': 0.0, 'nombre': 0.0, 'fundadora': 0.0, 'livia:': 0.0, 'pintadas': 0.0, 'danaides,': 0.0, 'osaron': 0.0, 'fraguar': 0.0, 'muerte': 0.0, 'míseros': 0.0, 'primos,': 0.0, 'desposados': 0.0, 'ellas,': 0.0, 'cruel': 0.0, 'espada': 0.0, 'desnuda.': 0.0, 'tampoco': 0.0, 'evitéis': 0.0, 'templo': 0.0, 'adonis': 0.0, 'llorado': 0.0, 'venus:': 0.0, 'sacrificios': 0.0, 'celebrados': 0.0, 'séptimo': 0.0, 'judaico': 0.0, 'siro:': 0.0, 'olvidéis': 0.0, 'menfítica': 0.0, 'isis': 0.0, 'vestimenta': 0.0, 'lino,': 0.0, 'hizo': 0.0, 'ella': 0.0, 'júpiter[2].': 0.0, '[2]': 0.0, 'ío': 0.0, 'torpes': 0.0, 'júpiter:': 0.0, 'juno': 0.0, 'perseguía': 0.0, 'celos,': 0.0, 'librarla': 0.0, 'indignación,': 0.0, 'convirtió': 0.0, 'júpiter': 0.0, 'vaca,': 0.0, 'figura': 0.0, 'huyó': 0.0, 'egipto.': 0.0, '¿quién': 0.0, 'creería?,': 0.0, 'propósito': 0.0, 'casos': 0.0, 'amorosos:': 0.0, 'sutil': 0.0, 'foro': 0.0, 'llama': 0.0, 'fuente': 0.0, 'apia,': 0.0, 'dominada': 0.0, 'adyacente': 0.0, 'construido': 0.0, 'mármol,': 0.0, 'hiende': 0.0, 'aire': 0.0, 'saltantes': 0.0, 'aguas.': 0.0, 'frecuencia': 0.0, 'causídico': 0.0, 'deja': 0.0, 'coger': 0.0, 'defiende': 0.0, 'mismo.': 0.0, 'faltan': 0.0, 'palabras': 0.0, 'elocuente,': 0.0, 'nuevos': 0.0, 'negocios': 0.0, 'ocupan,': 0.0, 'causa.': 0.0, 'poco': 0.0, 'patrono,': 0.0, 'desea': 0.0, 'cliente.': 0.0, 'ríe': 0.0, 'cercano.': 0.0, 'cazad': 0.0, 'principalmente': 0.0, 'públicos': 0.0, 'teatros,': 0.0, 'sitios': 0.0, 'favorables': 0.0, 'designios.': 0.0, 'hallaréis': 0.0, 'entretenimiento:': 0.0, 'disfrutar': 0.0, 'vez,': 0.0, 'escojáis': 0.0, 'poseerlas.': 0.0, 'manera': 0.0, 'hormigas': 0.0, 'numeroso': 0.0, 'escuadrón': 0.0, 'van': 0.0, 'vuelven': 0.0, 'cesar,': 0.0, 'cargadas': 0.0, 'sustento,': 0.0, 'abejas': 0.0, 'revuelan': 0.0, 'amenos': 0.0, 'olorosos': 0.0, 'sotos,': 0.0, 'buscando': 0.0, 'tomillo': 0.0, 'flores,': 0.0, 'concurren': 0.0, 'ataviadísimas': 0.0, 'juegos': 0.0, 'solemnes.': 0.0, 'afluencia': 0.0, 'embarazo': 0.0, 'elección.': 0.0, 'vienen': 0.0, 'ver,': 0.0, 'vistas.': 0.0, 'peligroso': 0.0, 'casto': 0.0, 'pudor.': 0.0, 'tú,': 0.0, 'rómulo!,': 0.0, 'instituiste': 0.0, 'espectáculos': 0.0, 'perturbados': 0.0, 'robada': 0.0, 'sabina': 0.0, 'deleitó': 0.0, 'tus': 0.0, 'vacantes': 0.0, 'ciudadanos.': 0.0, 'teatros': 0.0, 'estaban': 0.0, 'decorados': 0.0, 'mármoles': 0.0, 'colgaduras,': 0.0, 'competían': 0.0, 'escena': 0.0, 'vistosos': 0.0, 'colores.': 0.0, 'artificio,': 0.0, 'adornaba': 0.0, 'simplemente': 0.0, 'enramadas': 0.0, 'verde': 0.0, 'hojarasca': 0.0, 'producía': 0.0, 'nemoroso': 0.0, 'palatino.': 0.0, 'pueblo': 0.0, 'sentaba': 0.0, 'gradas': 0.0, 'hechas': 0.0, 'césped,': 0.0, 'llevando': 0.0, 'coronadas': 0.0, 'hojas': 0.0, 'verdes': 0.0, 'desgreñadas': 0.0, 'cabelleras.': 0.0, 'miraban': 0.0, 'romanos': 0.0, 'sabinas,': 0.0, 'reparando': 0.0, 'cada': 0.0, 'gusto,': 0.0, 'revolviendo': 0.0, 'deseos.': 0.0, 'flautista': 0.0, 'etrusco

In [9]:
# Representacion en tabla
df_tfidf = pd.DataFrame(list(tfidf_documento.items()), columns=['Palabra', 'TF-IDF'])
df_tfidf

            Palabra  TF-IDF
0              nota     0.0
1                de     0.0
2     transcripción     0.0
3                 *     0.0
4               las     0.0
...             ...     ...
8165        cisnes.     0.0
8166     discípulas     0.0
8167           mías     0.0
8168       escriban     0.0
8169         _fin._     0.0

[8170 rows x 2 columns]

Como el resultado es 0 se concluye que son terminos demasiados comunes, por el mismo hecho de que solo lo hacemos sobre un documento.

### Paso 2: Construir el corpus `Gutenberg 1000`

El corpus `Gutenberg 1000` es un corpus compuesto por 1000 libros de Gutenberg Project

In [10]:
import os

path = "data"
files = os.listdir(path)
N_archivos = len(files)
print("La carpeta",path, "tiene", N_archivos, "documentos")

La carpeta data tiene 1000 documentos

### Paso 3: Calcular la matriz TF-IDF para el corpus `Gutenberg 1000`

Primero se creo un indice invertido para conocer el numero de veces que aparece un termino en los documentos

In [11]:
# diccionario principal
indice_invertido = {}

# Bucle externo: Recorre cada archivo de la lista
for nombre_documento in files:
    
    ruta_completa = os.path.join(path, nombre_documento)
    
    # Abrir y leer el archivo actual
    with open(ruta_completa, "r", encoding="utf-8") as documento:
        contenido = documento.read()
        
    # convertir a minusculas y separar palabraas
    lista_de_palabras = contenido.lower().split()
    
    # Bucle interno: Recorre las palabras del archivo actual
    for palabra in lista_de_palabras:
        
        # Escenario A: La palabra es completamente nueva en todo nuestro índice
        if palabra not in indice_invertido:
            indice_invertido[palabra] = {nombre_documento: 1}
            
        # Escenario B: La palabra ya existe, pero es la primera vez que aparece en ESTE documento en específico
        elif nombre_documento not in indice_invertido[palabra]:
            indice_invertido[palabra][nombre_documento] = 1
            
        # Escenario C: La palabra existe y ya la habíamos visto en ESTE documento, sumamos 1
        else:
            indice_invertido[palabra][nombre_documento] += 1

In [12]:
print(indice_invertido.get("amor"))

{'7 de julio.txt': 2, 'A First Spanish Reader.txt': 1, 'A Flor De Piel Frases.txt': 1, 'A History of Magic and Experimental Science, Volume 1 (of 2) During the First Thirteen Centuries of .txt': 1, 'A los pies de Venus (los Borgia)  $b novela.txt': 35, 'A vuela pluma colección de artículos literarios y políticos.txt': 49, 'A.M.D.G..txt': 8, 'Abel Sánchez Una Historia de Pasión.txt': 7, 'Actas capitulares desde el 21 hasta el 25 de mayo de 1810 en Buenos Aires.txt': 1, 'Adriana Zumarán (novela).txt': 71, 'Adán y Eva en el paraíso.txt': 40, 'Agua de Nieve (Novela).txt': 63, 'Aguas fuertes.txt': 14, 'Al primer vuelo.txt': 7, 'Algo de todo.txt': 52, 'Alma vasca.txt': 14, 'Amar es vencer.txt': 22, 'Amaury.txt': 111, 'Amistad funesta Novela.txt': 29, 'Amor y llanto  $b colección de leyendas históricas originales.txt': 82, 'Amor y Pedagogía.txt': 43, 'Amores elegías amatorias.txt': 56, 'Amparo (Memorias de un loco).txt': 52, 'Américo Vespucio.txt': 3, 'Andanzas y visiones españolas.txt': 32, 'Angelina (novela mexicana).txt': 72, 'Antaño i Ogaño Novelas i Cuentos de la Vida Hispano-Americana.txt': 95, 'Antología de prosistas castellanos.txt': 24, 'Antología portorriqueña Prosa y verso.txt': 48, 'Antonio Azorín pequeño libro en que se habla de la vida de este peregrino señor.txt': 9, 'Apuntes biograficos de escritores, oradores y hombres de estado de la Republica Argentina.txt': 23, 'Apuntes para una Gramática Valenciana Popular.txt': 5, 'Argentina, Legend and History.txt': 16, 'Ariel.txt': 15, 'Arroz y tartana.txt': 21, 'Ausías March y su época.txt': 65, 'Autobiografía Obras Completas Vol. XV.txt': 20, 'Azul... Obras Completas Vol. IV.txt': 28, 'Años de juventud del doctor Angélico.txt': 44, 'Bailén.txt': 4, 'Belarmino y Apolonio.txt': 28, 'Biografia del libertador Simon Bolívar, ó La independencia de la América del sud Reseña histórico-bi.txt': 9, 'Bocetos al temple. Tipos trashumantes  $b Obras completas - Vol. VIII.txt': 7, 'Bocetos californianos.txt': 7, 'Buena Nueva de acuerdo a Juan Traducción de dominio público abierta a mejoras.txt': 4, 'Buena Nueva de acuerdo a Lucas Traducción de dominio público abierta a mejoras.txt': 1, 'Buena Nueva de acuerdo a Mateo Traducción de dominio público abierta a mejoras.txt': 1, 'Bug-Jargal.txt': 17, 'Cabezas Pensadores y Artistas, Políticos Obras Completas Vol. XXII.txt': 22, 'Cabos sueltos Literatura y lingüística.txt': 12, 'Cancionero de Lope de Stúñiga Códice del siglo XV..txt': 111, 'Candido, o El Optimismo.txt': 4, 'Canto a la Argentina, Oda a Mitre y otros poemas Obras Completas Vol. IX.txt': 4, 'Cantos de Vida y Esperanza, Los Cisnes y otros poemas. Obras Completas Vol. VII.txt': 22, 'Carlos Broschi.txt': 35, 'Cartas americanas. Primera serie.txt': 41, 'Cartas de mi molino.txt': 7, 'Catalogo de los Objetos Etnologicos y Arqueologicos Exhibidos por la Expedición Hemenway.txt': 1, 'Catálogo Monumental de España; Provincia de Álava Inventario general de los monumentos históricos y .txt': 1, 'Cañas y barro Novela.txt': 8, 'Cecilia Valdés o la Loma del Ángel.txt': 32, 'Cenizas.txt': 33, 'Cincuenta y cuatro Canciones Españolas del siglo XVI Cancionero de Uppsala.txt': 5, 'Claros varones de Castilla, y Letras.txt': 22, 'Clemencia Novela de costumbres.txt': 86, 'Clásicos Castellanos Libro de Buen Amor.txt': 215, 'Cocina cómica Recetas de guisos y postres, poesías culinarias, y otros excesos.txt': 1, 'Cocina moderna.txt': 1, 'Colección de Documentos Inéditos Relativos al Descubrimiento, Conquista y Organización de las Antigu.txt': 6, 'Colección de viages y expediciónes à los campos de Buenos Aires y a las costas de Patagonia.txt': 4, 'Colon en Puerto-Rico.txt': 2, 'Comedia llamada Selvagia, Comedia Serafina.txt': 80, 'Comedias El remedio en la desdicha; El mejor alcalde, el rey.txt': 89, 'Comedias escogidas.txt': 26, 'Comedias inéditas.txt': 171, 'Comedias, tomo 1 de 3  $b Los Acarnienses, los Caballeros, las Nubes.txt': 5, 'Comedias, tomo 2 de 3  $b Las Avispas, la Paz, las Aves, Lisístrata.txt': 14, 'Comedias, tomo 3 de 3  $b Las Fiestas de Ceres, las Ranas, las Junteras, Pluto.txt': 7, 'Comentario del coronel Francisco Verdugo, de la guerra de Frisia, en xiv años que fue gobernador y c.txt': 1, 'Comentarios a la Constitucion de los Estados Unidos de América.txt': 1, 'Compendio de la historia general de América. Tomo I.txt': 5, 'Compendio del viaje del joven Anacarsis a la Grecia (1 de 2).txt': 23, 'Compendio del viaje del joven Anacarsis a la Grecia (2 de 2).txt': 13, 'Con la Pluma y con el Sable Crónica de 1820 a 1823.txt': 11, 'Contestaciones y Consideraciones Al Pueblo y Congreso Norte-Americanos.txt': 1, 'Contigo Pan y Cebolla.txt': 3, 'Corazón  $b (diario de un niño).txt': 12, 'Correspondencia Oficial e Inedita sobre la Demarcacion de Limites entre el Paraguay y el Brasil.txt': 1, 'Cosas de España; tomo 1 (El país de lo imprevisto).txt': 9, 'Cosas de España; tomo 2 (El país de lo imprevisto).txt': 10, 'Cosas nuevas y viejas (apuntes sevillanos).txt': 8, 'Cosas que fueron Cuadros de costumbres.txt': 23, 'Cristóbal Colón y el descubrimiento de América, Tomo 1 Historia de la geografía del nuevo continente.txt': 1, 'Cristóbal Colón y el descubrimiento de América, Tomo 2 Historia de la geografía del nuevo continente.txt': 5, 'Crónica de la conquista de Granada (1 de 2).txt': 8, 'Crónica de la conquista de Granada (2 de 2).txt': 5, 'Crónicas de Marianela.txt': 77, 'Cuando la tierra era niña.txt': 7, 'Cuentos Clásicos del Norte, Primera Serie.txt': 5, 'Cuentos Clásicos del Norte, Segunda Serie.txt': 7, 'Cuentos de Amor de Locura y de Muerte.txt': 42, 'Cuentos de amor.txt': 34, 'Cuentos de Fray Mocho.txt': 13, 'Cuentos de la Alhambra.txt': 16, 'Cuentos de mi tiempo.txt': 13, 'Cuentos de navidad y reyes; cuentos de la patria; cuentos antiguos.txt': 14, 'Cuentos de poeta.txt': 40, 'Cuentos escogidos.txt': 18, 'Cuentos ilustrados.txt': 10, 'Cuentos ingenuos.txt': 12, 'Cuentos populares en Chile.txt': 5, 'Cuentos valencianos.txt': 6, 'Cuentos y crónicas Obras Completas Vol. XIV.txt': 24, 'Cuentos y diálogos.txt': 59, 'Cuestiones políticas y económicas.txt': 1, 'Curiosidades antiguas sevillanas (serie segunda).txt': 8, 'Cádiz.txt': 22, 'Córdoba.txt': 37, 'Dafnis y Cloe; leyendas del antiguo Oriente (fragmentos).txt': 87, 'De carne y hueso; cuentos.txt': 22, 'De Las Islas Filipinas.txt': 2, 'De Oñate a La Granja.txt': 12, 'De Sobremesa; crónicas, Cuarta Parte (de 5).txt': 9, 'De Sobremesa; crónicas, Primera Parte (de 5).txt': 19, 'De Sobremesa; crónicas, Quinta Parte (de 5).txt': 61, 'De Sobremesa; crónicas, Segunda Parte (de 5).txt': 15, 'De Sobremesa; crónicas, Tercera Parte (de 5).txt': 16, 'De tal palo, tal astilla.txt': 31, 'De varios colores.txt': 49, 'Defensa obligada contra acusaciones gratuitas.txt': 4, 'Del libro impreso al libro digital.txt': 1, 'Del Plata al Niagara.txt': 9, 'Del sentimiento trágico de la vida.txt': 147, 'Derroteros y viages à la Ciudad Encantada, ó de los Césares. Que se creia existiese en la Cordillera.txt': 2, 'Descripcion é historia del castillo de la aljafería sito  extramuros de la ciudad de Zaragoza.txt': 1, 'Descripción colonial, libro primero (12).txt': 9, 'Descripción colonial, libro segundo (22).txt': 3, 'Descripción Geografica, Histórica y Estadística de Bolivia, Tomo 1..txt': 1, 'Despertar Para Morir (Novela).txt': 68, 'Diario de la expedicion de 1822 a los campos del sud de Buenos Aires Desde Moron hasta la Sierra de .txt': 3, 'Diario de la expedicion reduccional del ano 1780, mandada practicar por orden del Virey de Buenos Ai.txt': 7, 'Diario de un viage a la costa de la mar Magallanica.txt': 1, 'Diario de un viage a Salinas Grandes, en los campos del sud de Buenos Aires.txt': 2, 'Diario del piloto de la Real Armada, D. Basilio Villarino, del reconocimiento, que hizo del Río Negr.txt': 2, 'Diario del viaje al rio Bermejo.txt': 1, 'Diario histórico de la rebelion y guerra de los pueblos Guaranis situados en la costa oriental del R.txt': 2, 'Diccionario Bagobo-Español.txt': 1, 'Diccionario Ingles-Español-Tagalog Con partes de la oracion y pronunciacion figurada.txt': 2, 'Divertidas aventuras del nieto de Juan Moreira.txt': 22, 'Divinas palabras  $b Tragicomedia de aldea.txt': 1, 'Doble error  $b Novela.txt': 8, 'Doctor Sutilis (Cuentos).txt': 46, 'Documentos para la historia del virreinato del Rio de la Plata, tomo 1.txt': 14, 'Don Francisco de Quevedo Drama en Cuatro Actos.txt': 7, 'Don Juan Tenorio.txt': 18, 'Don Quijote.txt': 101, 'Don Álvaro, o, La fuerza del Sino.txt': 6, 'Doña Clarines y Mañana de Sol.txt': 10, 'Doña Luz.txt': 125, 'Doña Perfecta.txt': 13, 'Dramas (1 de 2) Hernani; El Rey se divierte; Los Burgraves.txt': 47, 'Dramas (2 de 2) Lucrecia Borgia; María Tudor; La Esmeralda; Ruy Blas.txt': 49, 'Dramas de Guillermo Shakspeare [vol. 1].txt': 90, 'Dramas de Guillermo Shakspeare [vol. 4].txt': 57, 'Dulce Dueño.txt': 37, 'Dulce Nombre (Novela).txt': 30, 'Dulce y sabrosa.txt': 74, 'Edipo rey; Edipo en Colona; Antígona.txt': 5, 'Educación común en el Estado de Buenos-Aires.txt': 1, 'El 19 de marzo y el 2 de mayo.txt': 10, 'El Abate Constantin.txt': 16, 'El abuelo (Novela en cinco jornadas).txt': 15, 'El amigo Manso.txt': 30, 'El amor, el dandysmo y la intriga.txt': 16, 'El anacronópete; Viaje a China; Metempsicosis.txt': 9, 'El aprendiz de conspirador.txt': 2, 'El Arroyo.txt': 12, 'El arte de amar.txt': 34, 'El buey suelto... Cuadros edificantes de la vida de un solterón.txt': 21, 'El caballero encantado (cuento real... inverosí\xadmil).txt': 21, 'El Campesino Puertorriqueño Sus Condiciones Físicas, Intelectuales y Morales, Causas que la Determin.txt': 15, 'El Canto Errante Obras Completas Vol. XVI.txt': 14, 'El capital Resumido y acompañado de un estudio sobre el Socialismo científico.txt': 1, 'El Capitán Veneno The Hispanic Series.txt': 3, 'El caso extraño del Doctor Jekyll.txt': 8, 'El castigo sin venganza  $b Tragedia.txt': 49, 'El cisne de Vilamorta.txt': 19, 'El clavo.txt': 10, 'El cocinero de su majestad Memorias del tiempo de Felipe III.txt': 212, 'El Comendador Mendoza Obras Completas Tomo VII.txt': 68, 'El conde de Candespina (1 de 2)  $b novela histórica original.txt': 12, 'El conde de Candespina (2 de 2)  $b novela histórica original.txt': 14, 'El conde Lucanor.txt': 40, 'El Consejo de los Dioses.txt': 1, 'El corazón juglar.txt': 7, 'El crimen y el castigo.txt': 32, 'El Criterio.txt': 25, 'El criticón (tomo 1 de 2).txt': 10, 'El cuarto poder.txt': 33, 'El deseo.txt': 28, 'El Diablo Cojuelo.txt': 10, 'El Doctor Centeno (novela completa).txt': 12, 'El Doctor Centeno (Tomo I).txt': 4, 'El Doctor Centeno (Tomo II).txt': 8, 'El doncel de don Enrique el doliente, Tomo I (de 4) Historia caballeresca del siglo quince.txt': 7, 'El doncel de don Enrique el doliente, Tomo II (de 4) Historia caballeresca del siglo quince.txt': 10, 'El doncel de don Enrique el doliente, Tomo III (de 4) Historia caballeresca del siglo quince.txt': 22, 'El doncel de don Enrique el doliente, Tomo IV (de 4) Historia caballeresca del siglo quince.txt': 13, 'El ebook tiene 40 años (1971-2011).txt': 2, 'El enemigo.txt': 55, 'El equipaje del rey José.txt': 14, 'El Escuadrón del Brigante.txt': 8, 'El espejo de la muerte  $b Cuentos cortos.txt': 40, 'El Estudiante de Salamanca and Other Selections.txt': 46, 'El Filibusterismo (Continuación del Noli me tángere).txt': 15, 'El Folk-lore Filipino (Tomo I).txt': 53, 'El Gaucho Martín Fierro.txt': 6, 'El Grande Oriente.txt': 9, 'El Gíbaro  $b Cuadro de costumbres de la isla de Puerto Rico.txt': 8, 'El Hombre Mediocre Ensayo de psicologia y moral.txt': 24, 'El idilio de un enfermo.txt': 15, 'El imperio jesuítico.txt': 8, 'El infierno del amor leyenda fantastica.txt': 43, 'El intruso.txt': 29, 'El Jayón Drama en tres actos.txt': 10, 'El legado del ignorantismo Conferencia dada el 23 de abril de 1920 ante la Asamblea de Maestros en B.txt': 4, 'El libro de las mil noches y una noche; t. 1.txt': 24, 'El libro de las mil noches y una noche; t. 2.txt': 18, 'El libro de las mil noches y una noche; t. 3.txt': 18, 'El libro de las mil noches y una noche; t. 6.txt': 15, 'El libro de las mil noches y una noche; t. 7.txt': 7, 'El libro de las mil noches y una noche; t. 8.txt': 7, 'El libro de las tierras vírgenes.txt': 5, 'El libro rojo, 1520-1867, Tomo I.txt': 17, 'El libro rojo, 1520-1867, Tomo II.txt': 17, 'El lindo don Diego  $b Comedia.txt': 26, 'El maestrante.txt': 33, 'El manco de Lepanto episodio de la vida del príncipe de los ingenios, Miguel de Cervantes-Saavedra.txt': 132, 'El Mandarín.txt': 7, 'El Manuscrito de mi madre aumentado con las comentarios, prólogo y epílogo.txt': 15, 'El Mar.txt': 27, 'El Marqués de Bradomín Coloquios Románticos.txt': 15, 'El misterio de un hombre pequeñito novela.txt': 30, 'El molino silencioso; Las bodas de Yolanda.txt': 12, 'El Mulato Plácido o El Poeta Mártir.txt': 40, 'El Niño de la Bola Novela.txt': 31, 'El origen del pensamiento.txt': 17, 'El papa del mar.txt': 15, 'El paraiso de las mujeres Novela.txt': 20, 'El paraíso perdido.txt': 66, 'El Payador, Vol. I Hijo de la Pampa.txt': 33, 'El pecado y la noche.txt': 30, 'El pintor de Salzburgo.txt': 17, 'El poema de la Pampa Martín Fierro y el criollismo español.txt': 10, 'El prisionero de Zenda.txt': 23, 'El proceso.txt': 3, 'El proletario en España y el Negro en Cuba.txt': 7, 'El Protestantismo comparado con el Catolicismo en sus relaciones con la Civilización Europea (Vols 1.txt': 31, 'El préstamo de la difunta.txt': 10, 'El Quijote apócrifo.txt': 35, 'El sabor de la tierruca.txt': 20, 'El Sabor de la Venganza.txt': 5, 'El señor de Bembibre.txt': 47, 'El Señor y los demás son Cuentos.txt': 68, 'El señorito Octavio.txt': 32, 'El sombrero de tres picos Historia verdadera de un sucedido que anda en romances escrita ahora tal y.txt': 4, 'El Superhombre y otras novedades.txt': 44, 'El sí de las niñas.txt': 8, 'El teatro por dentro Autores, comediantes, escenas de la vida de bastidores, etc..txt': 12, 'El terror de 1824.txt': 11, 'El Tesoro de Gastón Novela.txt': 4, 'El tesoro misterioso.txt': 21, 'El tratado de la pintura.txt': 5, 'El Tratado de París Conferencias pronunciadas en el círculo de la Unión mercantil en los días 22, 24.txt': 7, 'El trovador.txt': 22, 'El Viaje a Nicaragua é Historia de mis libros Obras Completas, Vol. XVII.txt': 17, 'El árbol de la ciencia novela.txt': 12, 'Electra.txt': 15, 'En el fondo del abismo La justicia infalible.txt': 8, 'En las orillas del Sar.txt': 36, 'En tranvía  $b Cuentos dramáticos.txt': 20, 'En viaje (1881-1882).txt': 5, 'Eneida; v. 2 de 2.txt': 18, 'Eneida; v.1 de 2.txt': 45, 'England under the Angevin Kings, Volumes I and II.txt': 2, 'Entre naranjos.txt': 68, 'Entretiens  Interviews  Entrevistas.txt': 1, 'Entrevistas (1998-2001).txt': 1, 'Es mi hombre Tragedia grotesca en tres actos.txt': 1, 'Esbozos y rasguños.txt': 18, 'Escenas Montañesas.txt': 8, 'Escritos políticos, económicos y literarios.txt': 8, 'Escuela de Humorismo Novelas.—Cuentos..txt': 14, 'Espasmo.txt': 160, 'España Contemporánea Obras Completas Vol. XIX.txt': 39, 'España y América  $b estudios históricos y literarios.txt': 15, 'España y los Estados Unidos de Norte América  $b a propósito de la guerra.txt': 4, 'Estados Unidos.txt': 4, 'Estampas de viaje España en los días de la guerra.txt': 10, 'Estudio descriptivo de los monumentos árabes de Granada, Sevilla y Córdoba ó sea La Alhambra, el Alc.txt': 5, 'Estudios americanos (primera serie).txt': 5, 'Estudios históricos del reinado de Felipe II.txt': 16, 'Expedición de Catalanes y Aragoneses al Oriente.txt': 14, 'Facundo.txt': 7, 'Fausto Primera parte.txt': 26, 'Fernando IV de Castilla, o, Dos muertes a un tiempo  $b Novela histórica del siglo XIV.txt': 20, 'Fiebre de amor (Dominique).txt': 16, 'Figuras americanas Galería de hombres illustres.txt': 9, 'Filipinas Dentro De Cien Años (Estudio Politico-Social).txt': 7, 'Filosofía Americana Ensayos.txt': 21, 'Filosofía Fundamental, Tomo I.txt': 1, 'Filosofía Fundamental, Tomo III.txt': 1, 'Filosofía Fundamental, Tomo IV.txt': 45, 'Flor de mayo.txt': 2, 'Florante Versión castellana del poema tagalo con un ensayo crítico.txt': 45, 'Fortuna.txt': 1, 'Fortunata y Jacinta dos historias de casadas.txt': 107, 'Fuente Ovejuna.txt': 17, 'Fábulas y cuentos en verso Selección.txt': 7, 'Fábulas.txt': 9, 'Fígaro (Artículos selectos).txt': 23, 'Ganarás el pan....txt': 39, 'Genio y figura.txt': 61, 'Germana.txt': 27, 'Gerona.txt': 5, 'Gloria (novela completa).txt': 84, 'Gloria (primera parte).txt': 33, 'Gloria (segunda parte).txt': 51, 'Granada, Poema Oriental, precedido de la Leyenda de al-Hamar, Tomo 1.txt': 35, 'Granada, Poema Oriental, precedido de la Leyenda de al-Hamar, Tomo 2.txt': 33, 'Granos de oro Pensamientos Seleccionados en las Obras de José Martí.txt': 23, 'Guerra de Granada Hecha por el rey D. Felipe II, contra los Moriscos de aquel reino, sus rebeldes; S.txt': 5, 'Guerra de razas (Negros contra Blancos en Cuba).txt': 3, 'Guerras civiles de Granada Tomo I.txt': 35, 'Hacia una Moral sin Dogmas Lecciones sobre Emerson y el Eticismo.txt': 11, 'Halma.txt': 24, 'Hamlet Drama en cinco actos.txt': 22, 'Historia de América desde sus tiempos más remotos hasta nuestros días, tomo I.txt': 27, 'Historia de América desde sus tiempos más remotos hasta nuestros días, tomo II.txt': 38, 'Historia de Gil Blas de Santillana Novela (Vol 1 de 3).txt': 25, 'Historia de Gil Blas de Santillana Novela (Vol 2 de 3).txt': 65, 'Historia de Gil Blas de Santillana Novela (Vol 3 de 3).txt': 29, 'Historia de la Conquista de la Habana (1762).txt': 5, 'Historia de la Conquista de Mexico, Volume 2 (of 3) Poblacion y Progresos de la America Septentriona.txt': 4, 'Historia de la célebre Reina de España Doña Juana, llamada vulgarmente, La Loca.txt': 11, 'Historia de la decadencia de España.txt': 44, 'Historia de la guerra del Peloponeso (1 de 2).txt': 8, 'Historia de la guerra del Peloponeso (2 de 2).txt': 5, 'Historia de la instrucción pública en Puerto Rico hasta el año de 1898.txt': 3, 'Historia de la lengua y literatura castellana, Tomo 1  $b Desde los orígenes hasta Carlos V.txt': 48, 'Historia de la lengua y literatura castellana, Tomo 2  $b Época de Carlos V.txt': 32, 'Historia de la literatura y del arte dramático en España, tomo I.txt': 18, 'Historia de la literatura y del arte dramático en España, tomo II.txt': 28, 'Historia de la literatura y del arte dramático en España, tomo III.txt': 100, 'Historia de la literatura y del arte dramático en España, tomo IV.txt': 73, 'Historia de la literatura y del arte dramático en España, tomo V.txt': 60, 'Historia de la vida del Buscón, llamado Don Pablos, ejemplo de vagabundos y espejo de tacaños.txt': 7, 'Historia de las Indias (vol. 1 de 5).txt': 18, 'Historia de las Indias (vol. 2 de 5).txt': 15, 'Historia de las Indias (vol. 3 de 5).txt': 12, 'Historia de las Indias (vol. 4 de 5).txt': 30, 'Historia de las Indias (vol. 5 de 5).txt': 12, 'Historia de los Judíos en España desde los tiempos de su establecimiento hasta principios del presen.txt': 19, 'Historia de los siete murciélagos, leyenda árabe.txt': 77, 'Historia de una parisiense.txt': 20, 'Historia de Venezuela, Tomo I.txt': 12, 'Historia de Venezuela, Tomo II.txt': 9, 'Historia del famoso predicador Fray Gerundio de Campazas, alias Zotes (1 de 2).txt': 9, 'Historia del famoso predicador Fray Gerundio de Campazas, alias Zotes (2 de 2).txt': 11, 'Historia del levantamiento, guerra y revolución de España (1 de 5).txt': 26, 'Historia del levantamiento, guerra y revolución de España (2 de 5).txt': 5, 'Historia del levantamiento, guerra y revolución de España (3 de 5).txt': 8, 'Historia del levantamiento, guerra y revolución de España (5 de 5).txt': 22, 'Historia del Paraguay, Río de La Plata y Tucumán.txt': 13, 'Historia natural y moral de las Indias (vol. 1 of 2).txt': 1, 'Historia natural y moral de las Indias (vol. 2 of 2).txt': 3, 'Hombres y glorias de América.txt': 15, 'Honor de artista.txt': 19, 'I. Origen de los indios de América. II. Origen y civilizaciones de los in

Lo que se interpreta es que la palabra amor aparece 2 veces en el documento `7 de julio.txt`, etc.

In [13]:
# Representacion en tabla
import pandas as pd

df = pd.DataFrame(list(indice_invertido.items()), columns=['Palabra', 'Archivos'])
df

                  Palabra                                           Archivos
0                produced  {'20 poemas para ser leídos en el tranvía.txt'...
1                    from  {'20 poemas para ser leídos en el tranvía.txt'...
2                  images  {'20 poemas para ser leídos en el tranvía.txt'...
3               available  {'20 poemas para ser leídos en el tranvía.txt'...
4                      at  {'20 poemas para ser leídos en el tranvía.txt'...
...                   ...                                                ...
2543979           cegama!                          {'Zumalacárregui.txt': 1}
2543980         cegama...                          {'Zumalacárregui.txt': 1}
2543981         morimos»,                          {'Zumalacárregui.txt': 1}
2543982      encomiéndale                          {'Zumalacárregui.txt': 1}
2543983  «zumalacárregui»                          {'Zumalacárregui.txt': 1}

[2543984 rows x 2 columns]

#### **Calculo de la Frecuencia de Terminos (TF)**

In [30]:
import math 
#diccionario para guardar los valores de TF calculados
tf_documento = {}

# Bucle externo: recorre la palabra y su sub-diccionario (que contiene varios documentos)
for palabra, documentos in indice_invertido.items():
    
    #sub-diccionario vacío para guardar los TF de esta palabra en específico
    tf_documento[palabra] = {}
    
    # Bucle interno: recorre cada documento donde apareció esta palabra
    # 'nombre_doc' será el nombre del archivo y 'f' será su conteo bruto
    for nombre_doc, f in documentos.items():
        
        # Formula TF
        tf = 1 + math.log10(f) 
        
        # Resultados en un nuevo diccionario
        tf_documento[palabra][nombre_doc] = tf

In [15]:
print(tf_documento.get("amor"))

{'7 de julio.txt': 1.3010299956639813, 'A First Spanish Reader.txt': 1.0, 'A Flor De Piel Frases.txt': 1.0, 'A History of Magic and Experimental Science, Volume 1 (of 2) During the First Thirteen Centuries of .txt': 1.0, 'A los pies de Venus (los Borgia)  $b novela.txt': 2.5440680443502757, 'A vuela pluma colección de artículos literarios y políticos.txt': 2.690196080028514, 'A.M.D.G..txt': 1.9030899869919435, 'Abel Sánchez Una Historia de Pasión.txt': 1.845098040014257, 'Actas capitulares desde el 21 hasta el 25 de mayo de 1810 en Buenos Aires.txt': 1.0, 'Adriana Zumarán (novela).txt': 2.8512583487190755, 'Adán y Eva en el paraíso.txt': 2.6020599913279625, 'Agua de Nieve (Novela).txt': 2.7993405494535817, 'Aguas fuertes.txt': 2.146128035678238, 'Al primer vuelo.txt': 1.845098040014257, 'Algo de todo.txt': 2.7160033436347994, 'Alma vasca.txt': 2.146128035678238, 'Amar es vencer.txt': 2.342422680822206, 'Amaury.txt': 3.0453229787866576, 'Amistad funesta Novela.txt': 2.462397997898956, 'Amor y llanto  $b colección de leyendas históricas originales.txt': 2.9138138523837167, 'Amor y Pedagogía.txt': 2.633468455579586, 'Amores elegías amatorias.txt': 2.7481880270062007, 'Amparo (Memorias de un loco).txt': 2.7160033436347994, 'Américo Vespucio.txt': 1.4771212547196624, 'Andanzas y visiones españolas.txt': 2.5051499783199063, 'Angelina (novela mexicana).txt': 2.8573324964312685, 'Antaño i Ogaño Novelas i Cuentos de la Vida Hispano-Americana.txt': 2.9777236052888476, 'Antología de prosistas castellanos.txt': 2.380211241711606, 'Antología portorriqueña Prosa y verso.txt': 2.681241237375587, 'Antonio Azorín pequeño libro en que se habla de la vida de este peregrino señor.txt': 1.9542425094393248, 'Apuntes biograficos de escritores, oradores y hombres de estado de la Republica Argentina.txt': 2.361727836017593, 'Apuntes para una Gramática Valenciana Popular.txt': 1.6989700043360187, 'Argentina, Legend and History.txt': 2.204119982655925, 'Ariel.txt': 2.1760912590556813, 'Arroz y tartana.txt': 2.3222192947339195, 'Ausías March y su época.txt': 2.8129133566428557, 'Autobiografía Obras Completas Vol. XV.txt': 2.3010299956639813, 'Azul... Obras Completas Vol. IV.txt': 2.4471580313422194, 'Años de juventud del doctor Angélico.txt': 2.6434526764861874, 'Bailén.txt': 1.6020599913279625, 'Belarmino y Apolonio.txt': 2.4471580313422194, 'Biografia del libertador Simon Bolívar, ó La independencia de la América del sud Reseña histórico-bi.txt': 1.9542425094393248, 'Bocetos al temple. Tipos trashumantes  $b Obras completas - Vol. VIII.txt': 1.845098040014257, 'Bocetos californianos.txt': 1.845098040014257, 'Buena Nueva de acuerdo a Juan Traducción de dominio público abierta a mejoras.txt': 1.6020599913279625, 'Buena Nueva de acuerdo a Lucas Traducción de dominio público abierta a mejoras.txt': 1.0, 'Buena Nueva de acuerdo a Mateo Traducción de dominio público abierta a mejoras.txt': 1.0, 'Bug-Jargal.txt': 2.230448921378274, 'Cabezas Pensadores y Artistas, Políticos Obras Completas Vol. XXII.txt': 2.342422680822206, 'Cabos sueltos Literatura y lingüística.txt': 2.079181246047625, 'Cancionero de Lope de Stúñiga Códice del siglo XV..txt': 3.0453229787866576, 'Candido, o El Optimismo.txt': 1.6020599913279625, 'Canto a la Argentina, Oda a Mitre y otros poemas Obras Completas Vol. IX.txt': 1.6020599913279625, 'Cantos de Vida y Esperanza, Los Cisnes y otros poemas. Obras Completas Vol. VII.txt': 2.342422680822206, 'Carlos Broschi.txt': 2.5440680443502757, 'Cartas americanas. Primera serie.txt': 2.6127838567197355, 'Cartas de mi molino.txt': 1.845098040014257, 'Catalogo de los Objetos Etnologicos y Arqueologicos Exhibidos por la Expedición Hemenway.txt': 1.0, 'Catálogo Monumental de España; Provincia de Álava Inventario general de los monumentos históricos y .txt': 1.0, 'Cañas y barro Novela.txt': 1.9030899869919435, 'Cecilia Valdés o la Loma del Ángel.txt': 2.5051499783199063, 'Cenizas.txt': 2.5185139398778875, 'Cincuenta y cuatro Canciones Españolas del siglo XVI Cancionero de Uppsala.txt': 1.6989700043360187, 'Claros varones de Castilla, y Letras.txt': 2.342422680822206, 'Clemencia Novela de costumbres.txt': 2.9344984512435675, 'Clásicos Castellanos Libro de Buen Amor.txt': 3.3324384599156054, 'Cocina cómica Recetas de guisos y postres, poesías culinarias, y otros excesos.txt': 1.0, 'Cocina moderna.txt': 1.0, 'Colección de Documentos Inéditos Relativos al Descubrimiento, Conquista y Organización de las Antigu.txt': 1.7781512503836436, 'Colección de viages y expediciónes à los campos de Buenos Aires y a las costas de Patagonia.txt': 1.6020599913279625, 'Colon en Puerto-Rico.txt': 1.3010299956639813, 'Comedia llamada Selvagia, Comedia Serafina.txt': 2.9030899869919438, 'Comedias El remedio en la desdicha; El mejor alcalde, el rey.txt': 2.949390006644913, 'Comedias escogidas.txt': 2.414973347970818, 'Comedias inéditas.txt': 3.2329961103921536, 'Comedias, tomo 1 de 3  $b Los Acarnienses, los Caballeros, las Nubes.txt': 1.6989700043360187, 'Comedias, tomo 2 de 3  $b Las Avispas, la Paz, las Aves, Lisístrata.txt': 2.146128035678238, 'Comedias, tomo 3 de 3  $b Las Fiestas de Ceres, las Ranas, las Junteras, Pluto.txt': 1.845098040014257, 'Comentario del coronel Francisco Verdugo, de la guerra de Frisia, en xiv años que fue gobernador y c.txt': 1.0, 'Comentarios a la Constitucion de los Estados Unidos de América.txt': 1.0, 'Compendio de la historia general de América. Tomo I.txt': 1.6989700043360187, 'Compendio del viaje del joven Anacarsis a la Grecia (1 de 2).txt': 2.361727836017593, 'Compendio del viaje del joven Anacarsis a la Grecia (2 de 2).txt': 2.113943352306837, 'Con la Pluma y con el Sable Crónica de 1820 a 1823.txt': 2.0413926851582254, 'Contestaciones y Consideraciones Al Pueblo y Congreso Norte-Americanos.txt': 1.0, 'Contigo Pan y Cebolla.txt': 1.4771212547196624, 'Corazón  $b (diario de un niño).txt': 2.079181246047625, 'Correspondencia Oficial e Inedita sobre la Demarcacion de Limites entre el Paraguay y el Brasil.txt': 1.0, 'Cosas de España; tomo 1 (El país de lo imprevisto).txt': 1.9542425094393248, 'Cosas de España; tomo 2 (El país de lo imprevisto).txt': 2.0, 'Cosas nuevas y viejas (apuntes sevillanos).txt': 1.9030899869919435, 'Cosas que fueron Cuadros de costumbres.txt': 2.361727836017593, 'Cristóbal Colón y el descubrimiento de América, Tomo 1 Historia de la geografía del nuevo continente.txt': 1.0, 'Cristóbal Colón y el descubrimiento de América, Tomo 2 Historia de la geografía del nuevo continente.txt': 1.6989700043360187, 'Crónica de la conquista de Granada (1 de 2).txt': 1.9030899869919435, 'Crónica de la conquista de Granada (2 de 2).txt': 1.6989700043360187, 'Crónicas de Marianela.txt': 2.886490725172482, 'Cuando la tierra era niña.txt': 1.845098040014257, 'Cuentos Clásicos del Norte, Primera Serie.txt': 1.6989700043360187, 'Cuentos Clásicos del Norte, Segunda Serie.txt': 1.845098040014257, 'Cuentos de Amor de Locura y de Muerte.txt': 2.623249290397901, 'Cuentos de amor.txt': 2.5314789170422554, 'Cuentos de Fray Mocho.txt': 2.113943352306837, 'Cuentos de la Alhambra.txt': 2.204119982655925, 'Cuentos de mi tiempo.txt': 2.113943352306837, 'Cuentos de navidad y reyes; cuentos de la patria; cuentos antiguos.txt': 2.146128035678238, 'Cuentos de poeta.txt': 2.6020599913279625, 'Cuentos escogidos.txt': 2.255272505103306, 'Cuentos ilustrados.txt': 2.0, 'Cuentos ingenuos.txt': 2.079181246047625, 'Cuentos populares en Chile.txt': 1.6989700043360187, 'Cuentos valencianos.txt': 1.7781512503836436, 'Cuentos y crónicas Obras Completas Vol. XIV.txt': 2.380211241711606, 'Cuentos y diálogos.txt': 2.7708520116421442, 'Cuestiones políticas y económicas.txt': 1.0, 'Curiosidades antiguas sevillanas (serie segunda).txt': 1.9030899869919435, 'Cádiz.txt': 2.342422680822206, 'Córdoba.txt': 2.568201724066995, 'Dafnis y Cloe; leyendas del antiguo Oriente (fragmentos).txt': 2.9395192526186182, 'De carne y hueso; cuentos.txt': 2.342422680822206, 'De Las Islas Filipinas.txt': 1.3010299956639813, 'De Oñate a La Granja.txt': 2.079181246047625, 'De Sobremesa; crónicas, Cuarta Parte (de 5).txt': 1.9542425094393248, 'De Sobremesa; crónicas, Primera Parte (de 5).txt': 2.278753600952829, 'De Sobremesa; crónicas, Quinta Parte (de 5).txt': 2.785329835010767, 'De Sobremesa; crónicas, Segunda Parte (de 5).txt': 2.1760912590556813, 'De Sobremesa; crónicas, Tercera Parte (de 5).txt': 2.204119982655925, 'De tal palo, tal astilla.txt': 2.4913616938342726, 'De varios colores.txt': 2.690196080028514, 'Defensa obligada contra acusaciones gratuitas.txt': 1.6020599913279625, 'Del libro impreso al libro digital.txt': 1.0, 'Del Plata al Niagara.txt': 1.9542425094393248, 'Del sentimiento trágico de la vida.txt': 3.167317334748176, 'Derroteros y viages à la Ciudad Encantada, ó de los Césares. Que se creia existiese en la Cordillera.txt': 1.3010299956639813, 'Descripcion é historia del castillo de la aljafería sito  extramuros de la ciudad de Zaragoza.txt': 1.0, 'Descripción colonial, libro primero (12).txt': 1.9542425094393248, 'Descripción colonial, libro segundo (22).txt': 1.4771212547196624, 'Descripción Geografica, Histórica y Estadística de Bolivia, Tomo 1..txt': 1.0, 'Despertar Para Morir (Novela).txt': 2.8325089127062366, 'Diario de la expedicion de 1822 a los campos del sud de Buenos Aires Desde Moron hasta la Sierra de .txt': 1.4771212547196624, 'Diario de la expedicion reduccional del ano 1780, mandada practicar por orden del Virey de Buenos Ai.txt': 1.845098040014257, 'Diario de un viage a la costa de la mar Magallanica.txt': 1.0, 'Diario de un viage a Salinas Grandes, en los campos del sud de Buenos Aires.txt': 1.3010299956639813, 'Diario del piloto de la Real Armada, D. Basilio Villarino, del reconocimiento, que hizo del Río Negr.txt': 1.3010299956639813, 'Diario del viaje al rio Bermejo.txt': 1.0, 'Diario histórico de la rebelion y guerra de los pueblos Guaranis situados en la costa oriental del R.txt': 1.3010299956639813, 'Diccionario Bagobo-Español.txt': 1.0, 'Diccionario Ingles-Español-Tagalog Con partes de la oracion y pronunciacion figurada.txt': 1.3010299956639813, 'Divertidas aventuras del nieto de Juan Moreira.txt': 2.342422680822206, 'Divinas palabras  $b Tragicomedia de aldea.txt': 1.0, 'Doble error  $b Novela.txt': 1.9030899869919435, 'Doctor Sutilis (Cuentos).txt': 2.6627578316815743, 'Documentos para la historia del virreinato del Rio de la Plata, tomo 1.txt': 2.146128035678238, 'Don Francisco de Quevedo Drama en Cuatro Actos.txt': 1.845098040014257, 'Don Juan Tenorio.txt': 2.255272505103306, 'Don Quijote.txt': 3.0043213737826426, 'Don Álvaro, o, La fuerza del Sino.txt': 1.7781512503836436, 'Doña Clarines y Mañana de Sol.txt': 2.0, 'Doña Luz.txt': 3.0969100130080562, 'Doña Perfecta.txt': 2.113943352306837, 'Dramas (1 de 2) Hernani; El Rey se divierte; Los Burgraves.txt': 2.6720978579357175, 'Dramas (2 de 2) Lucrecia Borgia; María Tudor; La Esmeralda; Ruy Blas.txt': 2.690196080028514, 'Dramas de Guillermo Shakspeare [vol. 1].txt': 2.954242509439325, 'Dramas de Guillermo Shakspeare [vol. 4].txt': 2.7558748556724915, 'Dulce Dueño.txt': 2.568201724066995, 'Dulce Nombre (Novela).txt': 2.4771212547196626, 'Dulce y sabrosa.txt': 2.8692317197309762, 'Edipo rey; Edipo en Colona; Antígona.txt': 1.6989700043360187, 'Educación común en el Estado de Buenos-Aires.txt': 1.0, 'El 19 de marzo y el 2 de mayo.txt': 2.0, 'El Abate Constantin.txt': 2.204119982655925, 'El abuelo (Novela en cinco jornadas).txt': 2.1760912590556813, 'El amigo Manso.txt': 2.4771212547196626, 'El amor, el dandysmo y la intriga.txt': 2.204119982655925, 'El anacronópete; Viaje a China; Metempsicosis.txt': 1.9542425094393248, 'El aprendiz de conspirador.txt': 1.3010299956639813, 'El Arroyo.txt': 2.079181246047625, 'El arte de amar.txt': 2.5314789170422554, 'El buey suelto... Cuadros edificantes de la vida de un solterón.txt': 2.3222192947339195, 'El caballero encantado (cuento real... inverosí\xadmil).txt': 2.3222192947339195, 'El Campesino Puertorriqueño Sus Condiciones Físicas, Intelectuales y Morales, Causas que la Determin.txt': 2.1760912590556813, 'El Canto Errante Obras Completas Vol. XVI.txt': 2.146128035678238, 'El capital Resumido y acompañado de un estudio sobre el Socialismo científico.txt': 1.0, 'El Capitán Veneno The Hispanic Series.txt': 1.4771212547196624, 'El caso extraño del Doctor Jekyll.txt': 1.9030899869919435, 'El castigo sin venganza  $b Tragedia.txt': 2.690196080028514, 'El cisne de Vilamorta.txt': 2.278753600952829, 'El clavo.txt': 2.0, 'El cocinero de su majestad Memorias del tiempo de Felipe III.txt': 3.326335860928751, 'El Comendador Mendoza Obras Completas Tomo VII.txt': 2.8325089127062366, 'El conde de Candespina (1 de 2)  $b novela histórica original.txt': 2.079181246047625, 'El conde de Candespina (2 de 2)  $b novela histórica original.txt': 2.146128035678238, 'El conde Lucanor.txt': 2.6020599913279625, 'El Consejo de los Dioses.txt': 1.0, 'El corazón juglar.txt': 1.845098040014257, 'El crimen y el castigo.txt': 2.5051499783199063, 'El Criterio.txt': 2.3979400086720375, 'El criticón (tomo 1 de 2).txt': 2.0, 'El cuarto poder.txt': 2.5185139398778875, 'El deseo.txt': 2.4471580313422194, 'El Diablo Cojuelo.txt': 2.0, 'El Doctor Centeno (novela completa).txt': 2.079181246047625, 'El Doctor Centeno (Tomo I).txt': 1.6020599913279625, 'El Doctor Centeno (Tomo II).txt': 1.9030899869919435, 'El doncel de don Enrique el doliente, Tomo I (de 4) Historia caballeresca del siglo quince.txt': 1.845098040014257, 'El doncel de don Enrique el doliente, Tomo II (de 4) Historia caballeresca del siglo quince.txt': 2.0, 'El doncel de don Enrique el doliente, Tomo III (de 4) Historia caballeresca del siglo quince.txt': 2.342422680822206, 'El doncel de don Enrique el doliente, Tomo IV (de 4) Historia caballeresca del siglo quince.txt': 2.113943352306837, 'El ebook tiene 40 años (1971-2011).txt': 1.3010299956639813, 'El enemigo.txt': 2.740362689494244, 'El equipaje del rey José.txt': 2.146128035678238, 'El Escuadrón del Brigante.txt': 1.9030899869919435, 'El espejo de la muerte  $b Cuentos cortos.txt': 2.6020599913279625, 'El Estudiante de Salamanca and Other Selections.txt': 2.6627578316815743, 'El Filibusterismo (Continuación del Noli me tángere).txt': 2.1760912590556813, 'El Folk-lore Filipino (Tomo I).txt': 2.724275869600789, 'El Gaucho Martín Fierro.txt': 1.7781512503836436, 'El Grande Oriente.txt': 1.9542425094393248, 'El Gíbaro  $b Cuadro de costumbres de la isla de Puerto Rico.txt': 1.9030899869919435, 'El Hombre Mediocre Ensayo de psicologia y moral.txt': 2.380211241711606, 'El idilio de un enfermo.txt': 2.1760912590556813, 'El imperio jesuítico.txt': 1.9030899869919435, 'El infierno del amor leyenda fantastica.txt': 2.633468455579586, 'El intruso.txt': 2.462397997898956, 'El Jayón Drama en tres actos.txt': 2.0, 'El legado del ignorantismo Conferencia dada el 23 de abril de 1920 ante la Asamblea de Maestros en B.txt': 1.6020599913279625, 'El libro de las mil noches y una noche; t. 1.txt': 2.380211241711606, 'El libro de las mil noches y una noche; t. 2.txt': 2.255272505103306, 'El libro de las mil noches y una noche; t. 3.txt': 2.255272505103306, 'El libro de las mil noches y una noche; t. 6.txt': 2.1760912590556813, 'El libro de las mil noches y una noche; t. 7.txt': 1.845098040014257, 'El libro de las mil noches y una noche; t. 8.txt': 1.845098040014257, 'El libro de las tierras vírgenes.txt': 1.6989700043360187, 'El libro rojo, 1520-1867, Tomo I.txt': 2.230448921378274, 'El libro rojo, 1520-1867, Tomo II.txt': 2.230448921378274, 'El lindo don Diego  $b Comedia.txt': 2.414973347970818, 'El maestrante.txt': 2.5185139398778875, 'El manco de Lepanto episodio de la vida del príncipe de los ingenios, Miguel de Cervantes-Saavedra.txt': 3.12057393120585, 'El Mandarín.txt': 1.845098040014257, 'El Manuscrito de mi madre aumentado con las comentarios, prólogo y epílogo.txt': 2.1760912590556813, 'El Mar.txt': 2.4313637641589874, 'El Marqués de Bradomín Coloquios Románticos.txt': 2.1760912590556813, 'El misterio de un hombre pequeñito novela.txt': 2.4771212547196626, 'El molino silencioso; Las bodas de Yolanda.txt': 2.079181246047625, 'El Mulato Plácido o El Poeta Mártir.txt': 2.6020599913279625, 'El Niño de la Bola Novela.txt': 2.4913616938342726, 'El origen del pensamiento.txt': 2.230448921378274, 'El papa del mar.txt': 2.1760912590556813, 'El paraiso de las mujeres Novela.txt': 2.3010299956639813, 'El paraíso perdido.txt': 2.8195439355418688, 'El Payador, Vol. I Hijo de la Pampa.txt': 2.5185139398778875, 'El pecado y la noche.txt': 2.4771212547196626, 'El pintor de Salzburgo.txt': 2.230448921378274, 'El poema de la Pampa Martín Fierro y el criollismo español.txt': 2.0, 'El prisionero de Zenda.txt': 2.361727836017593, 'El proceso.txt': 1.4771212547196624, 'El proletario en España y el Negro en Cuba.txt': 1.845098040014257, 'El Protestantismo comparado con el Catolicismo en sus relaciones con la Civilización Europea (Vols 1.txt': 2.4913616938342726, 'El préstamo de la difunta.txt': 2.0, 'El Quijote apócrifo.txt': 2.5440680443502757, 'El sabor de la tierruca.txt': 2.3010299956639813, 'El Sabor de la Venganza.txt': 1.6989700043360187, 'El señor de Bembibre.txt': 2.6720978579357175, 'El Señor y los demás son Cuentos.txt': 2.8325089127062366, 'El señorito Octavio.txt': 2.5051499783199063, 'El sombrero de tres picos Historia verdadera de un sucedido que anda en romances escrita ahora tal y.txt': 1.6020599913279625, 'El Superhombre y otras novedades.txt': 2.6434526764861874, 'El sí de las niñas.txt': 1.9030899869919435, 'El teatro por dentro Autores, comediantes, escenas de la vida de bastidores, etc..txt': 2.079181246047625, 'El terror de 1824.txt': 2.0413926851582254, 'El Tesoro de Gastón Novela.txt': 1.6020599913279625, 'El tesoro misterioso.txt': 2.3222192947339195, 'El tratado de la pintura.txt': 1.6989700043360187, 'El Tratado de París Conferencias pronunciadas en el círculo de la Unión mercantil en los días 22, 24.txt': 1.845098040014257, 'El trovador.txt': 2.342422680822206, 'El Viaje a Nicaragua é Historia de mis libros Obras Completas, Vol. XVII.txt': 2.230448921378274, 'El árbol de la ciencia novela.txt': 2.079181246047625, 'Electra.txt': 2.1760912590556813, 'En el fondo del abismo La justicia infalible.txt': 1.9030899869919435, 'En las orillas del Sar.txt': 2.5563025007672873, 'En tranvía  $b Cuentos dramáticos.txt': 2.3010299956639813, 'En viaje (1881-1882).txt': 1.6989700043360187, 'Eneida; v. 2 de 2.txt': 2.255272505103306, 'Eneida; v.1 de 2.txt': 2.653212513775344, 'England under the Angevin Kings, Volumes I and II.txt': 1.3010299956639813, 'Entre naranjos.txt': 2.8325089127062366, 'Entretiens  Interviews  Entrevistas.txt': 1.0, 'Entrevistas (1998-2001).txt': 1.0, 'Es mi hombre Tragedia grotesca en tres actos.txt': 1.0, 'Esbozos y rasguños.txt': 2.255272505103306, 'Escenas Montañesas.txt': 1.9030899869919435, 'Escritos políticos, económicos y literarios.txt': 1.9030899869919435, 'Escuela de Humorismo Novelas.—Cuentos..txt': 2.146128035678238, 'Espasmo.txt': 3.2041199826559246, 'España Contemporánea Obras Completas Vol. XIX.txt': 2.591064607026499, 'España y América  $b estudios históricos y literarios.txt': 2.1760912590556813, 'España y los Estados Unidos de Norte América  $b a propósito de la guerra.txt': 1.6020599913279625, 'Estados Unidos.txt': 1.6020599913279625, 'Estampas de viaje España en los días de la guerra.txt': 2.0, 'Estudio descriptivo de los monumentos árabes de Granada, Sevilla y Córdoba ó sea La Alhambra, el Alc.txt': 1.6989700043360187, 'Estudios americanos (primera serie).txt': 1.6989700043360187, 'Estudios históricos del reinado de Felipe II.txt': 2.204119982655925, 'Expedición de Catalanes y Aragoneses al Oriente.txt': 2.146128035678238, 'Facundo.txt': 1.845098040014257, 'Fausto Primera parte.txt': 2.414973347970818, 'Fernando IV de Castilla, o, Dos muertes a un tiempo  $b Novela histórica del siglo XIV.txt': 2.3010299956639813, 'Fiebre de amor (Dominique).txt

Por ejemplo la palabra amor tiene una frecuencia de 1.30 en el documento `7 de julio.txt`

In [16]:
# Representacion en tabla
df_tf = pd.DataFrame(list(tf_documento.items()), columns=['Palabra', 'TF'])
df_tf

                  Palabra                                                 TF
0                produced  {'20 poemas para ser leídos en el tranvía.txt'...
1                    from  {'20 poemas para ser leídos en el tranvía.txt'...
2                  images  {'20 poemas para ser leídos en el tranvía.txt'...
3               available  {'20 poemas para ser leídos en el tranvía.txt'...
4                      at  {'20 poemas para ser leídos en el tranvía.txt'...
...                   ...                                                ...
2543979           cegama!                        {'Zumalacárregui.txt': 1.0}
2543980         cegama...                        {'Zumalacárregui.txt': 1.0}
2543981         morimos»,                        {'Zumalacárregui.txt': 1.0}
2543982      encomiéndale                        {'Zumalacárregui.txt': 1.0}
2543983  «zumalacárregui»                        {'Zumalacárregui.txt': 1.0}

[2543984 rows x 2 columns]

#### **Calculo de la frecuencia inversa del documento (IDF)**

In [ ]:
import math 
idf_documento = {}

for palabra, documentos in indice_invertido.items():
    
    # Calculo df: En cuantos documentos (claves) aparece la palabra?
    df = len(documentos)
    
    # IDF 
    idf = math.log10(N_archivos / df)
    
    # Guardar el resultado 
    idf_documento[palabra] = idf

In [32]:
print("IDF de 'amor':", idf_documento.get("amor"))

IDF de 'amor': 0.08354605145007492

In [33]:
# Representacion en tabla
df_idf = pd.DataFrame(list(idf_documento.items()), columns=['Palabra', 'IDF'])
df_idf

                  Palabra       IDF
0                produced  0.756962
1                    from  0.588380
2                  images  0.838632
3               available  0.847712
4                      at  0.514279
...                   ...       ...
2543979           cegama!  3.000000
2543980         cegama...  3.000000
2543981         morimos»,  3.000000
2543982      encomiéndale  3.000000
2543983  «zumalacárregui»  3.000000

[2543984 rows x 2 columns]

#### **Matriz TF - IDF**

In [34]:
tfidf_documento = {}

# Bucle externo: Recorre cada palabra
for palabra in tf_documento:
    
    # Preparamos el sub-diccionario vacío para esta palabra
    tfidf_documento[palabra] = {}
    
    # Extrae el valor numérico del IDF global para esta palabra
    idf = idf_documento[palabra]
    
    # Bucle interno: Recorre los documentos específicos donde aparece esa palabra
    # Aquí 'tf' sí será el valor numérico
    for nombre_doc, tf in tf_documento[palabra].items():
        
        # Calculo TF-IDF
        w = tf * idf
        
        tfidf_documento[palabra][nombre_doc] = w

In [35]:
print("TF-IDF de la palabra 'amor':", tfidf_documento.get("amor"))

TF-IDF de la palabra 'amor': {'7 de julio.txt': 0.10869591895583372, 'A First Spanish Reader.txt': 0.08354605145007492, 'A Flor De Piel Frases.txt': 0.08354605145007492, 'A History of Magic and Experimental Science, Volume 1 (of 2) During the First Thirteen Centuries of .txt': 0.08354605145007492, 'A los pies de Venus (los Borgia)  $b novela.txt': 0.21254683972577962, 'A vuela pluma colección de artículos literarios y políticos.txt': 0.22475526011285207, 'A.M.D.G..txt': 0.15899565396735132, 'Abel Sánchez Una Historia de Pasión.txt': 0.1541506557814635, 'Actas capitulares desde el 21 hasta el 25 de mayo de 1810 en Buenos Aires.txt': 0.08354605145007492, 'Adriana Zumarán (novela).txt': 0.23821137669953954, 'Adán y Eva en el paraíso.txt': 0.21739183791166744, 'Agua de Nieve (Novela).txt': 0.23387384957092994, 'Aguas fuertes.txt': 0.17930052328722232, 'Al primer vuelo.txt': 0.1541506557814635, 'Algo de todo.txt': 0.22691135508588847, 'Alma vasca.txt': 0.17930052328722232, 'Amar es vencer.txt': 0.19570016580979446, 'Amaury.txt': 0.2544247102678055, 'Amistad funesta Novela.txt': 0.20572362982302766, 'Amor y llanto  $b colección de leyendas históricas originales.txt': 0.243437642027191, 'Amor y Pedagogía.txt': 0.22001589108200145, 'Amores elegías amatorias.txt': 0.22960025829873992, 'Amparo (Memorias de un loco).txt': 0.22691135508588847, 'Américo Vespucio.txt': 0.12340764834480814, 'Andanzas y visiones españolas.txt': 0.20929538897886896, 'Angelina (novela mexicana).txt': 0.23871884775681776, 'Antaño i Ogaño Novelas i Cuentos de la Vida Hispano-Americana.txt': 0.24877704953156463, 'Antología de prosistas castellanos.txt': 0.19885725086208453, 'Antología portorriqueña Prosa y verso.txt': 0.22400711836784334, 'Antonio Azorín pequeño libro en que se habla de la vida de este peregrino señor.txt': 0.16326924523954134, 'Apuntes biograficos de escritores, oradores y hombres de estado de la Republica Argentina.txt': 0.19731303529899993, 'Apuntes para una Gramática Valenciana Popular.txt': 0.14194223539439102, 'Argentina, Legend and History.txt': 0.18414552147311014, 'Ariel.txt': 0.18180383228912425, 'Arroz y tartana.txt': 0.19401225267619673, 'Ausías March y su época.txt': 0.23500780401868696, 'Autobiografía Obras Completas Vol. XV.txt': 0.19224197040590865, 'Azul... Obras Completas Vol. IV.txt': 0.2044503907929811, 'Años de juventud del doctor Angélico.txt': 0.22085003331555325, 'Bailén.txt': 0.13384578646159254, 'Belarmino y Apolonio.txt': 0.2044503907929811, 'Biografia del libertador Simon Bolívar, ó La independencia de la América del sud Reseña histórico-bi.txt': 0.16326924523954134, 'Bocetos al temple. Tipos trashumantes  $b Obras completas - Vol. VIII.txt': 0.1541506557814635, 'Bocetos californianos.txt': 0.1541506557814635, 'Buena Nueva de acuerdo a Juan Traducción de dominio público abierta a mejoras.txt': 0.13384578646159254, 'Buena Nueva de acuerdo a Lucas Traducción de dominio público abierta a mejoras.txt': 0.08354605145007492, 'Buena Nueva de acuerdo a Mateo Traducción de dominio público abierta a mejoras.txt': 0.08354605145007492, 'Bug-Jargal.txt': 0.1863452003422334, 'Cabezas Pensadores y Artistas, Políticos Obras Completas Vol. XXII.txt': 0.19570016580979446, 'Cabos sueltos Literatura y lingüística.txt': 0.17370738335632577, 'Cancionero de Lope de Stúñiga Códice del siglo XV..txt': 0.2544247102678055, 'Candido, o El Optimismo.txt': 0.13384578646159254, 'Canto a la Argentina, Oda a Mitre y otros poemas Obras Completas Vol. IX.txt': 0.13384578646159254, 'Cantos de Vida y Esperanza, Los Cisnes y otros poemas. Obras Completas Vol. VII.txt': 0.19570016580979446, 'Carlos Broschi.txt': 0.21254683972577962, 'Cartas americanas. Primera serie.txt': 0.2182877745214322, 'Cartas de mi molino.txt': 0.1541506557814635, 'Catalogo de los Objetos Etnologicos y Arqueologicos Exhibidos por la Expedición Hemenway.txt': 0.08354605145007492, 'Catálogo Monumental de España; Provincia de Álava Inventario general de los monumentos históricos y .txt': 0.08354605145007492, 'Cañas y barro Novela.txt': 0.15899565396735132, 'Cecilia Valdés o la Loma del Ángel.txt': 0.20929538897886896, 'Cenizas.txt': 0.21041189519876888, 'Cincuenta y cuatro Canciones Españolas del siglo XVI Cancionero de Uppsala.txt': 0.14194223539439102, 'Claros varones de Castilla, y Letras.txt': 0.19570016580979446, 'Clemencia Novela de costumbres.txt': 0.24516575858776024, 'Clásicos Castellanos Libro de Buen Amor.txt': 0.2784120750263176, 'Cocina cómica Recetas de guisos y postres, poesías culinarias, y otros excesos.txt': 0.08354605145007492, 'Cocina moderna.txt': 0.08354605145007492, 'Colección de Documentos Inéditos Relativos al Descubrimiento, Conquista y Organización de las Antigu.txt': 0.14855751585056695, 'Colección de viages y expediciónes à los campos de Buenos Aires y a las costas de Patagonia.txt': 0.13384578646159254, 'Colon en Puerto-Rico.txt': 0.10869591895583372, 'Comedia llamada Selvagia, Comedia Serafina.txt': 0.24254170541742626, 'Comedias El remedio en la desdicha; El mejor alcalde, el rey.txt': 0.24640988924149268, 'Comedias escogidas.txt': 0.20176148758012966, 'Comedias inéditas.txt': 0.27010405937671494, 'Comedias, tomo 1 de 3  $b Los Acarnienses, los Caballeros, las Nubes.txt': 0.14194223539439102, 'Comedias, tomo 2 de 3  $b Las Avispas, la Paz, las Aves, Lisístrata.txt': 0.17930052328722232, 'Comedias, tomo 3 de 3  $b Las Fiestas de Ceres, las Ranas, las Junteras, Pluto.txt': 0.1541506557814635, 'Comentario del coronel Francisco Verdugo, de la guerra de Frisia, en xiv años que fue gobernador y c.txt': 0.08354605145007492, 'Comentarios a la Constitucion de los Estados Unidos de América.txt': 0.08354605145007492, 'Compendio de la historia general de América. Tomo I.txt': 0.14194223539439102, 'Compendio del viaje del joven Anacarsis a la Grecia (1 de 2).txt': 0.19731303529899993, 'Compendio del viaje del joven Anacarsis a la Grecia (2 de 2).txt': 0.17661162007437084, 'Con la Pluma y con el Sable Crónica de 1820 a 1823.txt': 0.17055029830403567, 'Contestaciones y Consideraciones Al Pueblo y Congreso Norte-Americanos.txt': 0.08354605145007492, 'Contigo Pan y Cebolla.txt': 0.12340764834480814, 'Corazón  $b (diario de un niño).txt': 0.17370738335632577, 'Correspondencia Oficial e Inedita sobre la Demarcacion de Limites entre el Paraguay y el Brasil.txt': 0.08354605145007492, 'Cosas de España; tomo 1 (El país de lo imprevisto).txt': 0.16326924523954134, 'Cosas de España; tomo 2 (El país de lo imprevisto).txt': 0.16709210290014984, 'Cosas nuevas y viejas (apuntes sevillanos).txt': 0.15899565396735132, 'Cosas que fueron Cuadros de costumbres.txt': 0.19731303529899993, 'Cristóbal Colón y el descubrimiento de América, Tomo 1 Historia de la geografía del nuevo continente.txt': 0.08354605145007492, 'Cristóbal Colón y el descubrimiento de América, Tomo 2 Historia de la geografía del nuevo continente.txt': 0.14194223539439102, 'Crónica de la conquista de Granada (1 de 2).txt': 0.15899565396735132, 'Crónica de la conquista de Granada (2 de 2).txt': 0.14194223539439102, 'Crónicas de Marianela.txt': 0.24115490263542422, 'Cuando la tierra era niña.txt': 0.1541506557814635, 'Cuentos Clásicos del Norte, Primera Serie.txt': 0.14194223539439102, 'Cuentos Clásicos del Norte, Segunda Serie.txt': 0.1541506557814635, 'Cuentos de Amor de Locura y de Muerte.txt': 0.21916212018195555, 'Cuentos de amor.txt': 0.2114950678479922, 'Cuentos de Fray Mocho.txt': 0.17661162007437084, 'Cuentos de la Alhambra.txt': 0.18414552147311014, 'Cuentos de mi tiempo.txt': 0.17661162007437084, 'Cuentos de navidad y reyes; cuentos de la patria; cuentos antiguos.txt': 0.17930052328722232, 'Cuentos de poeta.txt': 0.21739183791166744, 'Cuentos escogidos.txt': 0.18841911274530015, 'Cuentos ilustrados.txt': 0.16709210290014984, 'Cuentos ingenuos.txt': 0.17370738335632577, 'Cuentos populares en Chile.txt': 0.14194223539439102, 'Cuentos valencianos.txt': 0.14855751585056695, 'Cuentos y crónicas Obras Completas Vol. XIV.txt': 0.19885725086208453, 'Cuentos y diálogos.txt': 0.23149374472519818, 'Cuestiones políticas y económicas.txt': 0.08354605145007492, 'Curiosidades antiguas sevillanas (serie segunda).txt': 0.15899565396735132, 'Cádiz.txt': 0.19570016580979446, 'Córdoba.txt': 0.21456311337307227, 'Dafnis y Cloe; leyendas del antiguo Oriente (fragmentos).txt': 0.24558522671776084, 'De carne y hueso; cuentos.txt': 0.19570016580979446, 'De Las Islas Filipinas.txt': 0.10869591895583372, 'De Oñate a La Granja.txt': 0.17370738335632577, 'De Sobremesa; crónicas, Cuarta Parte (de 5).txt': 0.16326924523954134, 'De Sobremesa; crónicas, Primera Parte (de 5).txt': 0.19038086558724854, 'De Sobremesa; crónicas, Quinta Parte (de 5).txt': 0.23270330970123823, 'De Sobremesa; crónicas, Segunda Parte (de 5).txt': 0.18180383228912425, 'De Sobremesa; crónicas, Tercera Parte (de 5).txt': 0.18414552147311014, 'De tal palo, tal astilla.txt': 0.20814343225382395, 'De varios colores.txt': 0.22475526011285207, 'Defensa obligada contra acusaciones gratuitas.txt': 0.13384578646159254, 'Del libro impreso al libro digital.txt': 0.08354605145007492, 'Del Plata al Niagara.txt': 0.16326924523954134, 'Del sentimiento trágico de la vida.txt': 0.26461685700758525, 'Derroteros y viages à la Ciudad Encantada, ó de los Césares. Que se creia existiese en la Cordillera.txt': 0.10869591895583372, 'Descripcion é historia del castillo de la aljafería sito  extramuros de la ciudad de Zaragoza.txt': 0.08354605145007492, 'Descripción colonial, libro primero (12).txt': 0.16326924523954134, 'Descripción colonial, libro segundo (22).txt': 0.12340764834480814, 'Descripción Geografica, Histórica y Estadística de Bolivia, Tomo 1..txt': 0.08354605145007492, 'Despertar Para Morir (Novela).txt': 0.236644935353751, 'Diario de la expedicion de 1822 a los campos del sud de Buenos Aires Desde Moron hasta la Sierra de .txt': 0.12340764834480814, 'Diario de la expedicion reduccional del ano 1780, mandada practicar por orden del Virey de Buenos Ai.txt': 0.1541506557814635, 'Diario de un viage a la costa de la mar Magallanica.txt': 0.08354605145007492, 'Diario de un viage a Salinas Grandes, en los campos del sud de Buenos Aires.txt': 0.10869591895583372, 'Diario del piloto de la Real Armada, D. Basilio Villarino, del reconocimiento, que hizo del Río Negr.txt': 0.10869591895583372, 'Diario del viaje al rio Bermejo.txt': 0.08354605145007492, 'Diario histórico de la rebelion y guerra de los pueblos Guaranis situados en la costa oriental del R.txt': 0.10869591895583372, 'Diccionario Bagobo-Español.txt': 0.08354605145007492, 'Diccionario Ingles-Español-Tagalog Con partes de la oracion y pronunciacion figurada.txt': 0.10869591895583372, 'Divertidas aventuras del nieto de Juan Moreira.txt': 0.19570016580979446, 'Divinas palabras  $b Tragicomedia de aldea.txt': 0.08354605145007492, 'Doble error  $b Novela.txt': 0.15899565396735132, 'Doctor Sutilis (Cuentos).txt': 0.22246290280475875, 'Documentos para la historia del virreinato del Rio de la Plata, tomo 1.txt': 0.17930052328722232, 'Don Francisco de Quevedo Drama en Cuatro Actos.txt': 0.1541506557814635, 'Don Juan Tenorio.txt': 0.18841911274530015, 'Don Quijote.txt': 0.25099918806660443, 'Don Álvaro, o, La fuerza del Sino.txt': 0.14855751585056695, 'Doña Clarines y Mañana de Sol.txt': 0.16709210290014984, 'Doña Luz.txt': 0.2587346032830232, 'Doña Perfecta.txt': 0.17661162007437084, 'Dramas (1 de 2) Hernani; El Rey se divierte; Los Burgraves.txt': 0.22324322511873243, 'Dramas (2 de 2) Lucrecia Borgia; María Tudor; La Esmeralda; Ruy Blas.txt': 0.22475526011285207, 'Dramas de Guillermo Shakspeare [vol. 1].txt': 0.2468152966896163, 'Dramas de Guillermo Shakspeare [vol. 4].txt': 0.23024246248198177, 'Dulce Dueño.txt': 0.21456311337307227, 'Dulce Nombre (Novela).txt': 0.20695369979488307, 'Dulce y sabrosa.txt': 0.23971298087883108, 'Edipo rey; Edipo en Colona; Antígona.txt': 0.14194223539439102, 'Educación común en el Estado de Buenos-Aires.txt': 0.08354605145007492, 'El 19 de marzo y el 2 de mayo.txt': 0.16709210290014984, 'El Abate Constantin.txt': 0.18414552147311014, 'El abuelo (Novela en cinco jornadas).txt': 0.18180383228912425, 'El amigo Manso.txt': 0.20695369979488307, 'El amor, el dandysmo y la intriga.txt': 0.18414552147311014, 'El anacronópete; Viaje a China; Metempsicosis.txt': 0.16326924523954134, 'El aprendiz de conspirador.txt': 0.10869591895583372, 'El Arroyo.txt': 0.17370738335632577, 'El arte de amar.txt': 0.2114950678479922, 'El buey suelto... Cuadros edificantes de la vida de un solterón.txt': 0.19401225267619673, 'El caballero encantado (cuento real... inverosí\xadmil).txt': 0.19401225267619673, 'El Campesino Puertorriqueño Sus Condiciones Físicas, Intelectuales y Morales, Causas que la Determin.txt': 0.18180383228912425, 'El Canto Errante Obras Completas Vol. XVI.txt': 0.17930052328722232, 'El capital Resumido y acompañado de un estudio sobre el Socialismo científico.txt': 0.08354605145007492, 'El Capitán Veneno The Hispanic Series.txt': 0.12340764834480814, 'El caso extraño del Doctor Jekyll.txt': 0.15899565396735132, 'El castigo sin venganza  $b Tragedia.txt': 0.22475526011285207, 'El cisne de Vilamorta.txt': 0.19038086558724854, 'El clavo.txt': 0.16709210290014984, 'El cocinero de su majestad Memorias del tiempo de Felipe III.txt': 0.2779022269773827, 'El Comendador Mendoza Obras Completas Tomo VII.txt': 0.236644935353751, 'El conde de Candespina (1 de 2)  $b novela histórica original.txt': 0.17370738335632577, 'El conde de Candespina (2 de 2)  $b novela histórica original.txt': 0.17930052328722232, 'El conde Lucanor.txt': 0.21739183791166744, 'El Consejo de los Dioses.txt': 0.08354605145007492, 'El corazón juglar.txt': 0.1541506557814635, 'El crimen y el castigo.txt': 0.20929538897886896, 'El Criterio.txt': 0.20033841933870714, 'El criticón (tomo 1 de 2).txt': 0.16709210290014984, 'El cuarto poder.txt': 0.21041189519876888, 'El deseo.txt': 0.2044503907929811, 'El Diablo Cojuelo.txt': 0.16709210290014984, 'El Doctor Centeno (novela completa).txt': 0.17370738335632577, 'El Doctor Centeno (Tomo I).txt': 0.13384578646159254, 'El Doctor Centeno (Tomo II).txt': 0.15899565396735132, 'El doncel de don Enrique el doliente, Tomo I (de 4) Historia caballeresca del siglo quince.txt': 0.1541506557814635, 'El doncel de don Enrique el doliente, Tomo II (de 4) Historia caballeresca del siglo quince.txt': 0.16709210290014984, 'El doncel de don Enrique el doliente, Tomo III (de 4) Historia caballeresca del siglo quince.txt': 0.19570016580979446, 'El doncel de don Enrique el doliente, Tomo IV (de 4) Historia caballeresca del siglo quince.txt': 0.17661162007437084, 'El ebook tiene 40 años (1971-2011).txt': 0.10869591895583372, 'El enemigo.txt': 0.2289464822483518, 'El equipaje del rey José.txt': 0.17930052328722232, 'El Escuadrón del Brigante.txt': 0.15899565396735132, 'El espejo de la muerte  $b Cuentos cortos.txt': 0.21739183791166744, 'El Estudiante de Salamanca and Other Selections.txt': 0.22246290280475875, 'El Filibusterismo (Continuación del Noli me tángere).txt': 0.18180383228912425, 'El Folk-lore Filipino (Tomo I).txt': 0.22760249196586513, 'El Gaucho Martín Fierro.txt': 0.14855751585056695, 'El Grande Oriente.txt': 0.16326924523954134, 'El Gíbaro  $b Cuadro de costumbres de la isla de Puerto Rico.txt': 0.15899565396735132, 'El Hombre Mediocre Ensayo de psicologia y moral.txt': 0.19885725086208453, 'El idilio de un enfermo.txt': 0.18180383228912425, 'El imperio jesuítico.txt': 0.15899565396735132, 'El infierno del amor leyenda fantastica.txt': 0.22001589108200145, 'El intruso.txt': 0.20572362982302766, 'El Jayón Drama en tres actos.txt': 0.16709210290014984, 'El legado del ignorantismo Conferencia dada el 23 de abril de 1920 ante la Asamblea de Maestros en B.txt': 0.13384578646159254, 'El libro de las mil noches y una noche; t. 1.txt': 0.19885725086208453, 'El libro de las mil noches y una noche; t. 2.txt': 0.18841911274530015, 'El libro de las mil noches y una noche; t. 3.txt': 0.18841911274530015, 'El libro de las mil noches y una noche; t. 6.txt': 0.18180383228912425, 'El libro de las mil noches y una noche; t. 7.txt': 0.1541506557814635, 'El libro de las mil noches y una noche; t. 8.txt': 0.1541506557814635, 'El libro de las tierras vírgenes.txt': 0.14194223539439102, 'El libro rojo, 1520-1867, Tomo I.txt': 0.1863452003422334, 'El libro rojo, 1520-1867, Tomo II.txt': 0.1863452003422334, 'El lindo don Diego  $b Comedia.txt': 0.20176148758012966, 'El maestrante.txt': 0.21041189519876888, 'El manco de Lepanto episodio de la vida del príncipe de los ingenios, Miguel de Cervantes-Saavedra.txt': 0.2607116302102865, 'El Mandarín.txt': 0.1541506557814635, 'El Manuscrito de mi madre aumentado con las comentarios, prólogo y epílogo.txt': 0.18180383228912425, 'El Mar.txt': 0.20313084213427457, 'El Marqués de Bradomín Coloquios Románticos.txt': 0.18180383228912425, 'El misterio de un hombre pequeñito novela.txt': 0.20695369979488307, 'El molino silencioso; Las bodas de Yolanda.txt': 0.17370738335632577, 'El Mulato Plácido o El Poeta Mártir.txt': 0.21739183791166744, 'El Niño de la Bola Novela.txt': 0.20814343225382395, 'El origen del pensamiento.txt': 0.1863452003422334, 'El papa del mar.txt': 0.18180383228912425, 'El paraiso de las mujeres Novela.txt': 0.19224197040590865, 'El paraíso perdido.txt': 0.2355617627045277, 'El Payador, Vol. I Hijo de la Pampa.txt': 0.21041189519876888, 'El pecado y la noche.txt': 0.20695369979488307, 'El pintor de Salzburgo.txt': 0.1863452003422334, 'El poema de la Pampa Martín Fierro y el criollismo español.txt': 0.16709210290014984, 'El prisionero de Zenda.txt': 0.19731303529899993, 'El proceso.txt': 0.12340764834480814, 'El proletario en España y el Negro en Cuba.txt': 0.1541506557814635, 'El Protestantismo comparado con el Catolicismo en sus relaciones con la Civilización Europea (Vols 1.txt': 0.20814343225382395, 'El préstamo de la difunta.txt': 0.16709210290014984, 'El Quijote apócrifo.txt': 0.21254683972577962, 'El sabor de la tierruca.txt': 0.19224197040590865, 'El Sabor de la Venganza.txt': 0.14194223539439102, 'El señor de Bembibre.txt': 0.22324322511873243, 'El Señor y los demás son Cuentos.txt': 0.236644935353751, 'El señorito Octavio.txt': 0.20929538897886896, 'El sombrero de tres picos Historia verdadera de un sucedido que anda en romances escrita ahora tal y.txt': 0.13384578646159254, 'El Superhombre y otras novedades.txt': 0.22085003331555325, 'El sí de las niñas.txt': 0.15899565396735132, 'El teatro por dentro Autores, comediantes, escenas de la vida de bastidores, etc..txt': 0.17370738335632577, 'El terror de 1824.txt': 0.17055029830403567, 'El Tesoro de Gastón Novela.txt': 0.13384578646159254, 'El tesoro misterioso.txt': 0.19401225267619673, 'El tratado de la pintura.txt': 0.14194223539439102, 'El Tratado de París Conferencias pronunciadas en el círculo de la Unión mercantil en los días 22, 24.txt': 0.1541506557814635, 'El trovador.txt': 0.19570016580979446, 'El Viaje a Nicaragua é Historia de mis libros Obras Completas, Vol. XVII.txt': 0.1863452003422334, 'El árbol de la ciencia novela.txt': 0.17370738335632577, 'Electra.txt': 0.18180383228912425, 'En el fondo del abismo La justicia infalible.txt': 0.15899565396735132, 'En las orillas del Sar.txt': 0.21356898025105897, 'En tranvía  $b Cuentos dramáticos.txt': 0.19224197040590865, 'En viaje (1881-1882).txt': 0.14194223539439102, 'Eneida; v. 2 de 2.txt': 0.18841911274530015, 'Eneida; v.1 de 2.txt': 0.22166542918385748, 'England under the Angevin Kings, Volumes I and II.txt': 0.10869591895583372, 'Entre naranjos.txt': 0.236644935353751, 'Entretiens  Interviews  Entrevistas.txt': 0.08354605145007492, 'Entrevistas (1998-2001).txt': 0.08354605145007492, 'Es mi hombre Tragedia grotesca en tres actos.txt': 0.08354605145007492, 'Esbozos y rasguños.txt': 0.18841911274530015, 'Escenas Montañesas.txt': 0.15899565396735132, 'Escritos políticos, económicos y literarios.txt': 0.15899565396735132, 'Escuela de Humorismo Novelas.—Cuentos..txt': 

Por ejemplo, la palabra amor tiene un TF-IDF de 0.108 en el documento `7 de julio.txt`

In [37]:
# Representacion en tabla
df_tfidf = pd.DataFrame(list(tfidf_documento.items()), columns=['Palabra', 'TF-IDF'])
df_tfidf

                  Palabra                                             TF-IDF
0                produced  {'20 poemas para ser leídos en el tranvía.txt'...
1                    from  {'20 poemas para ser leídos en el tranvía.txt'...
2                  images  {'20 poemas para ser leídos en el tranvía.txt'...
3               available  {'20 poemas para ser leídos en el tranvía.txt'...
4                      at  {'20 poemas para ser leídos en el tranvía.txt'...
...                   ...                                                ...
2543979           cegama!                        {'Zumalacárregui.txt': 3.0}
2543980         cegama...                        {'Zumalacárregui.txt': 3.0}
2543981         morimos»,                        {'Zumalacárregui.txt': 3.0}
2543982      encomiéndale                        {'Zumalacárregui.txt': 3.0}
2543983  «zumalacárregui»                        {'Zumalacárregui.txt': 3.0}

[2543984 rows x 2 columns]

### Paso 4: Programar una función `buscar()` para el corpus `Gutenberg 1000`

In [ ]:
def buscar(consulta, top_n=5):
    """
    Busca los documentos más relevantes para una consulta dada.
    top_n: Cantidad de resultados a mostrar (por defecto 5)
    """
    # Limpieza y tokenizacion de la consulta
    palabras_consulta = consulta.lower().split()
    
    # Diccionario temporal para acumular la puntuación de los documentos candidatos
    puntuaciones = {}
    
    # Recorremos cada palabra a buscar
    for palabra in palabras_consulta:
        
        # Verificamos si la palabra existe en nuestra matriz TF-IDF
        if palabra in tfidf_documento:
            
            # Extraemos el sub-diccionario (los libros donde aparece y su peso)
            documentos_con_la_palabra = tfidf_documento[palabra]
            
            # Sumamos el peso TF-IDF al acumulado de cada documento
            for nombre_doc, peso in documentos_con_la_palabra.items():
                if nombre_doc not in puntuaciones:
                    puntuaciones[nombre_doc] = 0.0
                
                # Acumulamos el peso (esto es una versión simplificada del producto punto vectorial)
                puntuaciones[nombre_doc] += peso
                
    # Si ninguna palabra de la consulta estaba en los libros
    if not puntuaciones:
        print(f"No se encontraron resultados para: '{consulta}'")
        return
        
    # Ordenar los resultados de mayor a menor puntuación (Ranking)
    # sorted() ordena un diccionario y lo convierte en una lista de tuplas: [('libro1.txt', 2.5), ...]
    resultados_ordenados = sorted(puntuaciones.items(), key=lambda item: item[1], reverse=True)
    
    # Mostrar en pantalla el Top N de resultados
    print(f"--- Top {top_n} resultados para: '{consulta}' ---")
    for posicion, (documento, score) in enumerate(resultados_ordenados[:top_n], start=1):
        print(f"{posicion}. {documento} | Similitud: {score:.4f}")

In [40]:
buscar("guerra")

--- Top 5 resultados para: 'guerra' ---
1. Historia de la guerra del Peloponeso (1 de 2).txt | Similitud: 0.5154
2. Historia de la guerra del Peloponeso (2 de 2).txt | Similitud: 0.4791
3. Historia de América desde sus tiempos más remotos hasta nuestros días, tomo II.txt | Similitud: 0.4694
4. Historia de la decadencia de España.txt | Similitud: 0.4594
5. Los cuatro jinetes del apocalipsis.txt | Similitud: 0.4571